### ISSUE TITLE
[3.1] portable versions causing darc failure

### ISSUE THREAD

**Issue by adaggarwal** [dotnet/source-build#1470]
### Issue:
For the three repos - core-clr, core-setup and corefx; we are trying to get the [same](https://github.com/dotnet/source-build/blob/release/3.1/eng/Version.Details.xml#L44-L53) SHA1 for building portable versions. It seems that its causing darc to fail and that results in 3.1 auto-PRs(core-sdk, source-build-reference-packages) not getting the updates. 

```
fail: Microsoft.DotNet.Darc.Operations.Operation[0]
      Error: Failed to update dependencies to channel .NET Core SDK 3.1.1xx
Microsoft.DotNet.DarcLib.DarcException: The use of the same asset 'Microsoft.NETCore.Runtime.CoreCLR', even with a different version, is currently not supported.
   at Microsoft.DotNet.DarcLib.GitFileManager.UpdateDependencyFiles(IEnumerable`1 itemsToUpdate, String repoUri, String branch, IEnumerable`1 oldDependencies) in /_/src/Microsoft.DotNet.Darc/src/DarcLib/Helpers/GitFileManager.cs:line 223
   at Microsoft.DotNet.DarcLib.Local.UpdateDependenciesAsync(List`1 dependencies, IRemoteFactory remoteFactory) in /_/src/Microsoft.DotNet.Darc/src/DarcLib/Actions/Local.cs:line 66
   at Microsoft.DotNet.Darc.Operations.UpdateDependenciesOperation.ExecuteAsync() in /_/src/Microsoft.DotNet.Darc/src/Darc/Operations/UpdateDependenciesOperation.cs:line 223

```

### Suggestion:
A simple solution could be to clone only a single copy for these repos via `versionDetails` which is already taken care by darc. A copy task can be added to introduce portable clones for the pertinent projects right after the darc task completes.

cc @crummel @dseefeld @dagood

**Comment by dagood** [comment]
Triage notes:
We may be able to use a different package name per copy of the repo. Darc fix would be best though.
