### ISSUE TITLE
CoreFx test failures for System.Text.Encoding.Tests

### ISSUE THREAD

**Issue by adaggarwal** [dotnet/source-build#1479]
There have been consistent failures for System.Text.Encoding.Tests within coreFx Tests suite [Runs in CI under CentOS production job]

Failures:
```
<test name="System.Text.Tests.DecoderConvert2.PosTest11" type="System.Text.Tests.DecoderConvert2" method="PosTest11" time="0.0005395" result="Fail">
        <failure exception-type="Xunit.Sdk.EqualException">
          <message><![CDATA[Assert.Equal() Failure\nExpected: False\nActual:   True]]></message>
          <stack-trace><![CDATA[   at System.Text.Tests.DecoderConvert2.VerificationHelper(Decoder decoder, Byte[] bytes, Int32 byteIndex, Int32 byteCount, Char[] chars, Int32 charIndex, Int32 charCount, Boolean flush, Int32 desiredBytesUsed, Int32 desiredCharsUsed, Boolean desiredCompleted, String errorno) in /_/src/System.Text.Encoding/tests/Decoder/DecoderConvert2.cs:line 322
   at System.Text.Tests.DecoderConvert2.PosTest11() in /_/src/System.Text.Encoding/tests/Decoder/DecoderConvert2.cs:line 292]]></stack-trace>
        </failure>
</test>

<test name="System.Text.Tests.DecoderConvert2.PosTest6" type="System.Text.Tests.DecoderConvert2" method="PosTest6" time="0.0010791" result="Fail">
        <failure exception-type="Xunit.Sdk.EqualException">
          <message><![CDATA[Assert.Equal() Failure\nExpected: False\nActual:   True]]></message>
          <stack-trace><![CDATA[   at System.Text.Tests.DecoderConvert2.PosTest6() in /_/src/System.Text.Encoding/tests/Decoder/DecoderConvert2.cs:line 169]]></stack-trace>
        </failure>
</test>

<test name="System.Text.Tests.EncoderConvert2.EncoderUTF8ConvertMixedASCIIUnicodeCharArrayPartial" type="System.Text.Tests.EncoderConvert2" method="EncoderUTF8ConvertMixedASCIIUnicodeCharArrayPartial" time="0.0031768" result="Fail">
        <failure exception-type="Xunit.Sdk.EqualException">
          <message><![CDATA[Assert.Equal() Failure\nExpected: False\nActual:   True]]></message>
          <stack-trace><![CDATA[   at System.Text.Tests.EncoderConvert2.VerificationHelper(Encoder encoder, Char[] chars, Int32 charIndex, Int32 charCount, Byte[] bytes, Int32 byteIndex, Int32 byteCount, Boolean flush, Int32 expectedCharsUsed, Int32 expectedBytesUsed, Boolean expectedCompleted) in /_/src/System.Text.Encoding/tests/Encoder/EncoderConvert2.cs:line 288
   at System.Text.Tests.EncoderConvert2.EncoderUTF8ConvertMixedASCIIUnicodeCharArrayPartial() in /_/src/System.Text.Encoding/tests/Encoder/EncoderConvert2.cs:line 263]]></stack-trace>
        </failure>
 </test>

<test name="System.Text.Tests.EncoderConvert2.EncoderUTF8ConvertUnicodeCharArrayPartial" type="System.Text.Tests.EncoderConvert2" method="EncoderUTF8ConvertUnicodeCharArrayPartial" time="0.0004101" result="Fail">
        <failure exception-type="Xunit.Sdk.EqualException">
          <message><![CDATA[Assert.Equal() Failure\nExpected: False\nActual:   True]]></message>
          <stack-trace><![CDATA[   at System.Text.Tests.EncoderConvert2.VerificationHelper(Encoder encoder, Char[] chars, Int32 charIndex, Int32 charCount, Byte[] bytes, Int32 byteIndex, Int32 byteCount, Boolean flush, Int32 expectedCharsUsed, Int32 expectedBytesUsed, Boolean expectedCompleted) in /_/src/System.Text.Encoding/tests/Encoder/EncoderConvert2.cs:line 288
   at System.Text.Tests.EncoderConvert2.EncoderUTF8ConvertUnicodeCharArrayPartial() in /_/src/System.Text.Encoding/tests/Encoder/EncoderConvert2.cs:line 228]]></stack-trace>
        </failure>
</test>
```

**Comment by eerhardt** [comment]
Looks like you need the test changes from https://github.com/dotnet/corefx/pull/42832. Coreclr reverted some behavior, and the tests are in corefx. So you'll need a newer corefx.

**Comment by eerhardt** [comment]
Here's the coreclr change in `release/3.1` https://github.com/dotnet/coreclr/pull/27996

**Comment by dagood** [comment]
Triage notes:
We think this kind of mismatch shouldn't happen due to updates being coherent. There may be an issue with package name being the same between two things. Might be related to us doing the 3.1 update manually, however that should also have a coherent result. We also need to research the root cause, why we're out of sync. @adaggarwal to check if this impacts the Feb release.
