### ISSUE TITLE
Fix OSX build in master branch

### ISSUE THREAD

**Issue by dseefeld** [dotnet/source-build#1641]
OSX build for 5.0 is failing in installers repo with the following error:
```
/Users/runner/runners/2.171.1/work/1/s/artifacts/src/installer.b0d47ebe3474026fe5cbef83de2b336d292b6c26/src/redist/targets/GeneratePKG.targets(140,7): SourceArchive '/Users/runner/runners/2.171.1/work/1/s/artifacts/src/installer.b0d47ebe3474026fe5cbef83de2b336d292b6c26/artifacts/obj/redist/Release/downloads/aspnetcore-targeting-pack-5.0.0-preview.4.20257.10.tar.gz does not exist. [/Users/runner/runners/2.171.1/work/1/s/artifacts/src/installer.b0d47ebe3474026fe5cbef83de2b336d292b6c26/src/redist/redist.csproj]
/Users/runner/runners/2.171.1/work/1/s/artifacts/src/installer.b0d47ebe3474026fe5cbef83de2b336d292b6c26/src/redist/targets/GeneratePKG.targets(140,7): error MSB4018: The "ExtractArchiveToDirectory" task failed unexpectedly.
System.IO.IOException: Directory not empty
   at System.IO.FileSystem.RemoveDirectoryInternal(DirectoryInfo directory, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound)
   at System.IO.FileSystem.RemoveDirectory(String fullPath, Boolean recursive)
   at Microsoft.DotNet.Build.Tasks.ExtractArchiveToDirectory.Execute() in /_/src/core-sdk-tasks/ExtractArchiveToDirectory.cs:line 97
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) [/Users/runner/runners/2.171.1/work/1/s/artifacts/src/installer.b0d47ebe3474026fe5cbef83de2b336d292b6c26/src/redist/redist.csproj]
```

**Comment by MichaelSimons** [comment]
MacOS support is being tracked with https://github.com/dotnet/source-build/issues/3034 for .NET 8.0
