### ISSUE TITLE
"System.IO.IOException: The response ended prematurely" while downloading Private.SourceBuilt.Artifacts.0.1.0-3.1.109.tar.gz

### ISSUE THREAD

**Issue by dagood** [dotnet/source-build#1833]
This caused my RHEL8 build of a 3.1.110 tarball to fail:

```
  Progress... 00:11:20.0470994, current file size 47.2% (961,540,096 / 2,036,250,701) ~ 1,413.93 kB/s
  Progress... 00:11:25.0474480, current file size 47.2% (961,540,096 / 2,036,250,701) ~ 1,403.61 kB/s
  Progress... 00:11:30.0471349, current file size 47.2% (961,540,096 / 2,036,250,701) ~ 1,393.44 kB/s
/home/dagood/sb/source-build/build.proj(179,5): error : DownloadFileSB.ErrorDownloading https://dotnetcli.azureedge.net/source-built-artifacts/assets/Private.SourceBuilt.Artifacts.0.1.0-3.1.109.tar.gz System.IO.IOException: The response ended prematurely.
/home/dagood/sb/source-build/build.proj(179,5): error :    at System.Net.Http.HttpConnection.FillAsync()
/home/dagood/sb/source-build/build.proj(179,5): error :    at System.Net.Http.HttpConnection.CopyToContentLengthAsync(Stream destination, UInt64 length, Int32 bufferSize, CancellationToken cancellationToken)
/home/dagood/sb/source-build/build.proj(179,5): error :    at System.Net.Http.HttpConnection.ContentLengthReadStream.CompleteCopyToAsync(Task copyTask, CancellationToken cancellationToken)
/home/dagood/sb/source-build/build.proj(179,5): error :    at Microsoft.Build.Tasks.DownloadFileSB.DownloadAsync(Uri uri, CancellationToken cancellationToken) in /home/dagood/sb/source-build/tools-local/tasks/Microsoft.DotNet.SourceBuild.Tasks.XPlat/DownloadFileSB.cs:line 278
/home/dagood/sb/source-build/build.proj(179,5): error :    at Microsoft.Build.Tasks.DownloadFileSB.ExecuteAsync() in /home/dagood/sb/source-build/tools-local/tasks/Microsoft.DotNet.SourceBuild.Tasks.XPlat/DownloadFileSB.cs:line 122
  DownloadFileSB.Downloading Complete! Elapsed: 00:11:31.7418026

Build FAILED.
```

The root cause is probably just network flakiness, but I'm opening this in case it's not or to track parts of these:

Other things to do:
* Cache these to avoid downloading them all the time. https://github.com/dotnet/source-build/issues/1659
* Download the files at the beginning of the build (when needed) rather than at the end.
* Retry if we hit anything other than a 404.

**Comment by dseefeld** [comment]
Another example of AzDo flakiness.
