### ISSUE TITLE
Failure downloading Private.SourceBuilt.Artifacts: "Connection reset by peer"

### ISSUE THREAD

**Issue by dagood** [dotnet/source-build#1861]
Seems like flakiness, filing to track this instance:

https://github.com/dotnet/source-build/pull/1860

https://dev.azure.com/dnceng/public/_build/results?buildId=876754&view=logs&j=344d6db5-f971-535e-f543-4da382b6dce6&t=7d534279-f415-59fc-884e-7dab83f46b8c&l=4221

```
2020-11-05T18:30:35.5004989Z   DownloadFileSB.Downloading https://dotnetcli.azureedge.net/source-built-artifacts/assets/Private.SourceBuilt.Artifacts.0.1.0-5.0.100-bootstrap.13.tar.gz to /src/artifacts/obj/x64/Release/external-tarballs/Private.SourceBuilt.Artifacts.0.1.0-5.0.100-bootstrap.13.tar.gz
2020-11-05T18:30:40.4980837Z   Progress... 00:00:04.9984437, current file size 27.8% (633,417,728 / 2,276,515,200) ~ 126,722.99 kB/s
2020-11-05T18:30:45.5088583Z   Progress... 00:00:10.0007229, current file size 35.6% (811,483,121 / 2,276,515,200) ~ 81,142.45 kB/s
2020-11-05T18:30:51.3924370Z /src/build.proj(80,5): error : DownloadFileSB.ErrorDownloading https://dotnetcli.azureedge.net/source-built-artifacts/assets/Private.SourceBuilt.Artifacts.0.1.0-5.0.100-bootstrap.13.tar.gz System.Net.NetworkException: The connection was forcibly closed by the remote host.
2020-11-05T18:30:51.3930889Z /src/build.proj(80,5): error :  ---> System.Net.Sockets.SocketException (104): Connection reset by peer
2020-11-05T18:30:51.3932113Z /src/build.proj(80,5): error :    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.CreateException(SocketError error, Boolean forAsyncThrow)
2020-11-05T18:30:51.3933159Z /src/build.proj(80,5): error :    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ReceiveAsync(Socket socket, CancellationToken cancellationToken)
2020-11-05T18:30:51.3934170Z /src/build.proj(80,5): error :    at System.Net.Sockets.Socket.ReceiveAsync(Memory`1 buffer, SocketFlags socketFlags, Boolean fromNetworkStream, CancellationToken cancellationToken)
2020-11-05T18:30:51.3935097Z /src/build.proj(80,5): error :    at System.Net.Sockets.NetworkStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
2020-11-05T18:30:51.3935993Z /src/build.proj(80,5): error :    at System.Net.Security.SslStream.FillBufferAsync[TIOAdapter](TIOAdapter adapter, Int32 numBytesRequired)
2020-11-05T18:30:51.3936869Z /src/build.proj(80,5): error :    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
2020-11-05T18:30:51.3937771Z /src/build.proj(80,5): error :    at System.Net.Security.SslStream.FillBufferAsync[TIOAdapter](TIOAdapter adapter, Int32 numBytesRequired)
2020-11-05T18:30:51.3938648Z /src/build.proj(80,5): error :    at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
2020-11-05T18:30:51.3939531Z /src/build.proj(80,5): error :    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
2020-11-05T18:30:51.3940425Z /src/build.proj(80,5): error :    at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
2020-11-05T18:30:51.3941295Z /src/build.proj(80,5): error :    at System.Net.Security.SslStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
2020-11-05T18:30:51.3942114Z /src/build.proj(80,5): error :    at System.Net.Http.HttpConnection.FillAsync(Boolean async)
2020-11-05T18:30:51.3942904Z /src/build.proj(80,5): error :    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
2020-11-05T18:30:51.3943718Z /src/build.proj(80,5): error :    at System.Net.Http.HttpConnection.FillAsync(Boolean async)
2020-11-05T18:30:51.3944624Z /src/build.proj(80,5): error :    at System.Net.Http.HttpConnection.CopyToContentLengthAsync(Stream destination, Boolean async, UInt64 length, Int32 bufferSize, CancellationToken cancellationToken)
2020-11-05T18:30:51.3945657Z /src/build.proj(80,5): error :    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
2020-11-05T18:30:51.3946607Z /src/build.proj(80,5): error :    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
2020-11-05T18:30:51.3947749Z /src/build.proj(80,5): error :    at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
2020-11-05T18:30:51.3948628Z /src/build.proj(80,5): error :    at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
2020-11-05T18:30:51.3949365Z /src/build.proj(80,5): error :    at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
2020-11-05T18:30:51.3950220Z /src/build.proj(80,5): error :    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetExistingTaskResult(Task`1 task, TResult result)
2020-11-05T18:30:51.3951040Z /src/build.proj(80,5): error :    at System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder.SetResult()
2020-11-05T18:30:51.3952065Z /src/build.proj(80,5): error :    at System.Net.Http.HttpConnection.CopyFromBufferAsync(Stream destination, Boolean async, Int32 count, CancellationToken cancellationToken)
2020-11-05T18:30:51.3953535Z /src/build.proj(80,5): error :    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
2020-11-05T18:30:51.3955751Z /src/build.proj(80,5): error :    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
2020-11-05T18:30:51.3956784Z /src/build.proj(80,5): error :    at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
2020-11-05T18:30:51.3957792Z /src/build.proj(80,5): error :    at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
2020-11-05T18:30:51.3958575Z /src/build.proj(80,5): error :    at System.Threading.Tasks.Task.FinishSlow(Boolean userDelegateExecute)
2020-11-05T18:30:51.3959429Z /src/build.proj(80,5): error :    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
2020-11-05T18:30:51.4024451Z /src/build.proj(80,5): error :    at System.Threading.ThreadPoolWorkQueue.Dispatch()
2020-11-05T18:30:51.4026882Z /src/build.proj(80,5): error : --- End of stack trace from previous location ---
2020-11-05T18:30:51.4027505Z /src/build.proj(80,5): error : 
2020-11-05T18:30:51.4028263Z /src/build.proj(80,5): error :    --- End of inner exception stack trace ---
2020-11-05T18:30:51.4029001Z /src/build.proj(80,5): error :    at System.Net.Security.SslStream.FillBufferAsync[TIOAdapter](TIOAdapter adapter, Int32 numBytesRequired)
2020-11-05T18:30:51.4029787Z /src/build.proj(80,5): error :    at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
2020-11-05T18:30:51.4030515Z /src/build.proj(80,5): error :    at System.Net.Http.HttpConnection.FillAsync(Boolean async)
2020-11-05T18:30:51.4031980Z /src/build.proj(80,5): error :    at System.Net.Http.HttpConnection.CopyToContentLengthAsync(Stream destination, Boolean async, UInt64 length, Int32 bufferSize, CancellationToken cancellationToken)
2020-11-05T18:30:51.4032846Z /src/build.proj(80,5): error :    at System.Net.Http.HttpConnection.ContentLengthReadStream.CompleteCopyToAsync(Task copyTask, CancellationToken cancellationToken)
2020-11-05T18:30:51.4034136Z /src/build.proj(80,5): error :    at Microsoft.Build.Tasks.DownloadFileSB.DownloadAsync(Uri uri, CancellationToken cancellationToken) in /src/tools-local/tasks/Microsoft.DotNet.SourceBuild.Tasks.XPlat/DownloadFileSB.cs:line 278
2020-11-05T18:30:51.4035439Z /src/build.proj(80,5): error :    at Microsoft.Build.Tasks.DownloadFileSB.ExecuteAsync() in /src/tools-local/tasks/Microsoft.DotNet.SourceBuild.Tasks.XPlat/DownloadFileSB.cs:line 122
2020-11-05T18:30:51.4036129Z   DownloadFileSB.Downloading Complete! Elapsed: 00:00:15.9260242
2020-11-05T18:30:51.4066338Z 
2020-11-05T18:30:51.4066816Z Build FAILED.
```

**Comment by dseefeld** [comment]
Seems like flakiness in AzDo.

**Comment by dagood** [comment]
Hit: https://dev.azure.com/dnceng/public/_build/results?buildId=928703&view=logs&j=344d6db5-f971-535e-f543-4da382b6dce6&t=7d534279-f415-59fc-884e-7dab83f46b8c&l=4382

```
  [20:06:52.58] Building 'known-good' to produce tarball...done
  DownloadFileSB timeout set to 00:10:00
  DownloadFileSB.Downloading https://dotnetfeed.blob.core.windows.net/dotnet-core/assets/Private.SourceBuild.ReferencePackages.1.0.0-beta.20607.1.tar.gz to /src/artifacts/obj/x64/Release/external-tarballs/Private.SourceBuild.ReferencePackages.1.0.0-beta.20607.1.tar.gz
  Progress... 00:00:00.0029921, current file size 00.0% (12,288 / 308,809,304) ~ 4,106.81 kB/s
  Progress... 00:00:05.0012781, current file size 15.3% (47,333,376 / 308,809,304) ~ 9,464.26 kB/s
  Progress... 00:00:09.9982550, current file size 16.7% (51,691,520 / 308,809,304) ~ 5,170.05 kB/s
  Progress... 00:00:14.9985324, current file size 21.9% (67,764,224 / 308,809,304) ~ 4,518.06 kB/s
  Progress... 00:00:20.0029741, current file size 23.3% (72,040,448 / 308,809,304) ~ 3,601.49 kB/s
/src/build.proj(63,5): error : DownloadFileSB.ErrorDownloading https://dotnetfeed.blob.core.windows.net/dotnet-core/assets/Private.SourceBuild.ReferencePackages.1.0.0-beta.20607.1.tar.gz System.IO.IOException: Unable to read data from the transport connection: Connection reset by peer.
/src/build.proj(63,5): error :  ---> System.Net.Sockets.SocketException (104): Connection reset by peer
/src/build.proj(63,5): error :    --- End of inner exception stack trace ---
/src/build.proj(63,5): error :    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
/src/build.proj(63,5): error :    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
/src/build.proj(63,5): error :    at System.Net.Security.SslStream.FillBufferAsync[TIOAdapter](TIOAdapter adapter, Int32 numBytesRequired)
/src/build.proj(63,5): error :    at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
/src/build.proj(63,5): error :    at System.Net.Http.HttpConnection.FillAsync(Boolean async)
/src/build.proj(63,5): error :    at System.Net.Http.HttpConnection.CopyToContentLengthAsync(Stream destination, Boolean async, UInt64 length, Int32 bufferSize, CancellationToken cancellationToken)
/src/build.proj(63,5): error :    at System.Net.Http.HttpConnection.ContentLengthReadStream.CompleteCopyToAsync(Task copyTask, CancellationToken cancellationToken)
/src/build.proj(63,5): error :    at Microsoft.Build.Tasks.DownloadFileSB.DownloadAsync(Uri uri, CancellationToken cancellationToken) in /src/tools-local/tasks/Microsoft.DotNet.SourceBuild.Tasks.XPlat/DownloadFileSB.cs:line 278
/src/build.proj(63,5): error :    at Microsoft.Build.Tasks.DownloadFileSB.ExecuteAsync() in /src/tools-local/tasks/Microsoft.DotNet.SourceBuild.Tasks.XPlat/DownloadFileSB.cs:line 122
  DownloadFileSB.Downloading Complete! Elapsed: 00:00:25.2839754

Build FAILED.
```
