### ISSUE TITLE
Darc warning checking out vstest: "Exception: LibGit2Sharp.NotFoundException: odb: cannot read object: null OID cannot exist"

### ISSUE THREAD

**Issue by dagood** [dotnet/source-build#1877]
This appears to be happening consistently in our builds:

```
  dbug: Microsoft.DotNet.Darc.Operations.Operation[0]
        Reading local repo from /src/artifacts/src/vstest.b195e2589980861425b331e73a859252c3f2b71a
  dbug: Microsoft.DotNet.Darc.Operations.Operation[0]
        Attempting to check out b195e2589980861425b331e73a859252c3f2b71a in /src/artifacts/src/vstest.b195e2589980861425b331e73a859252c3f2b71a
  dbug: Microsoft.DotNet.Darc.Operations.Operation[0]
        Trying safe checkout of /src/artifacts/src/vstest.b195e2589980861425b331e73a859252c3f2b71a/ at b195e2589980861425b331e73a859252c3f2b71a
  info: Microsoft.DotNet.Darc.Operations.Operation[0]
        Checkout of /src/artifacts/src/vstest.b195e2589980861425b331e73a859252c3f2b71a/ at b195e2589980861425b331e73a859252c3f2b71a failed, fetching before attempting individual files.
  dbug: Microsoft.DotNet.Darc.Operations.Operation[0]
        Fetching +refs/heads/*:refs/remotes/origin/* from https://github.com/microsoft/vstest in /src/.git/modules/src/vstest.git/
  dbug: Microsoft.DotNet.Darc.Operations.Operation[0]
        Post-fetch, trying to checkout /src/artifacts/src/vstest.b195e2589980861425b331e73a859252c3f2b71a/ at b195e2589980861425b331e73a859252c3f2b71a again
  warn: Microsoft.DotNet.Darc.Operations.Operation[0]
        Couldn't check out one or more files, possibly due to path length limitations (LibGit2Sharp.NotFoundException: odb: cannot read object: null OID cannot exist
           at LibGit2Sharp.Core.Ensure.HandleError(Int32 result)
           at LibGit2Sharp.Core.Proxy.git_checkout_tree(RepositoryHandle repo, ObjectId treeId, GitCheckoutOpts& opts)
           at LibGit2Sharp.Repository.CheckoutTree(Tree tree, IList`1 paths, IConvertableToGitCheckoutOpts opts)
           at LibGit2Sharp.Commands.Checkout(IRepository repository, Tree tree, CheckoutOptions checkoutOptions, String refLogHeadSpec)
           at LibGit2Sharp.Commands.Checkout(IRepository repository, String committishOrBranchSpec, CheckoutOptions options)
           at Microsoft.DotNet.DarcLib.Helpers.LibGit2SharpHelpers.SafeCheckout(Repository repo, String commit, CheckoutOptions options, ILogger log) in /_/src/Microsoft.DotNet.Darc/src/DarcLib/Helpers/LibGit2SharpHelpers.cs:line 92).  Attempting to checkout by individual files.
  dbug: Microsoft.DotNet.Darc.Operations.Operation[0]
        Beginning individual file checkout for /src/artifacts/src/vstest.b195e2589980861425b331e73a859252c3f2b71a/ at b195e2589980861425b331e73a859252c3f2b71a
  warn: Microsoft.DotNet.Darc.Operations.Operation[0]
        Failed to checkout test in /src/artifacts/src/vstest.b195e2589980861425b331e73a859252c3f2b71a/ at b195e2589980861425b331e73a859252c3f2b71a, skipping.  Exception: LibGit2Sharp.NotFoundException: odb: cannot read object: null OID cannot exist
           at LibGit2Sharp.Core.Ensure.HandleError(Int32 result)
           at LibGit2Sharp.Core.Proxy.git_checkout_tree(RepositoryHandle repo, ObjectId treeId, GitCheckoutOpts& opts)
           at LibGit2Sharp.Repository.CheckoutTree(Tree tree, IList`1 paths, IConvertableToGitCheckoutOpts opts)
           at LibGit2Sharp.Repository.CheckoutPaths(String committishOrBranchSpec, IEnumerable`1 paths, CheckoutOptions checkoutOptions)
           at Microsoft.DotNet.DarcLib.Helpers.LibGit2SharpHelpers.SafeCheckoutTreeByIndividualFiles(Repository repo, Tree tree, String treePath, String commit, CheckoutOptions options, ILogger log) in /_/src/Microsoft.DotNet.Darc/src/DarcLib/Helpers/LibGit2SharpHelpers.cs:line 160
  warn: Microsoft.DotNet.Darc.Operations.Operation[0]
        Failed to checkout test/TestAssets in /src/artifacts/src/vstest.b195e2589980861425b331e73a859252c3f2b71a/ at b195e2589980861425b331e73a859252c3f2b71a, skipping.  Exception: LibGit2Sharp.NotFoundException: odb: cannot read object: null OID cannot exist
           at LibGit2Sharp.Core.Ensure.HandleError(Int32 result)
           at LibGit2Sharp.Core.Proxy.git_checkout_tree(RepositoryHandle repo, ObjectId treeId, GitCheckoutOpts& opts)
           at LibGit2Sharp.Repository.CheckoutTree(Tree tree, IList`1 paths, IConvertableToGitCheckoutOpts opts)
           at LibGit2Sharp.Repository.CheckoutPaths(String committishOrBranchSpec, IEnumerable`1 paths, CheckoutOptions checkoutOptions)
           at Microsoft.DotNet.DarcLib.Helpers.LibGit2SharpHelpers.SafeCheckoutTreeByIndividualFiles(Repository repo, Tree tree, String treePath, String commit, CheckoutOptions options, ILogger log) in /_/src/Microsoft.DotNet.Darc/src/DarcLib/Helpers/LibGit2SharpHelpers.cs:line 160
  warn: Microsoft.DotNet.Darc.Operations.Operation[0]
        Failed to checkout test/TestAssets/TestAssets.sln in /src/artifacts/src/vstest.b195e2589980861425b331e73a859252c3f2b71a/ at b195e2589980861425b331e73a859252c3f2b71a, skipping.  Exception: LibGit2Sharp.NotFoundException: odb: cannot read object: null OID cannot exist
           at LibGit2Sharp.Core.Ensure.HandleError(Int32 result)
           at LibGit2Sharp.Core.Proxy.git_checkout_tree(RepositoryHandle repo, ObjectId treeId, GitCheckoutOpts& opts)
           at LibGit2Sharp.Repository.CheckoutTree(Tree tree, IList`1 paths, IConvertableToGitCheckoutOpts opts)
           at LibGit2Sharp.Repository.CheckoutPaths(String committishOrBranchSpec, IEnumerable`1 paths, CheckoutOptions checkoutOptions)
           at Microsoft.DotNet.DarcLib.Helpers.LibGit2SharpHelpers.SafeCheckoutTreeByIndividualFiles(Repository repo, Tree tree, String treePath, String commit, CheckoutOptions options, ILogger log) in /_/src/Microsoft.DotNet.Darc/src/DarcLib/Helpers/LibGit2SharpHelpers.cs:line 160
  dbug: Microsoft.DotNet.Darc.Operations.Operation[0]
        Beginning clean of /src/artifacts/src/vstest.b195e2589980861425b331e73a859252c3f2b71a/ and 0 submodules
```

https://dev.azure.com/dnceng/internal/_build/results?buildId=880938&view=logs&j=d1c9fada-8432-5a85-5ee6-208e70d6b9f2&t=6a0e5b4f-e0ba-56e4-e16f-f65744d4efa3&l=1644

Some specific parts that could be looked at:

* `Failed to checkout test`
* `Failed to checkout test/TestAssets`
* `Failed to checkout test/TestAssets/TestAssets.sln`

I haven't seen anything bad happening because of it (maybe it's fine since we don't build tests anyway?), but this is weird.

**Comment by omajid** [comment]
I looked at the history for this in one of my machines and I am seeing this at least since Sep 24.

**Comment by dagood** [comment]
Maybe darc (or libgit2sharp (or libgit2)) is tripping up on this somewhat unusual path?

https://github.com/microsoft/vstest/blob/b195e2589980861425b331e73a859252c3f2b71a/test/TestAssets/TestAssets.sln/TestAssets.sln

Specifically: a dir with a file in it that has the same name as the dir.

**Comment by dagood** [comment]
Triage: We think this is another low-priority infra issue. The worst case seems to be that this file isn't being checked out, but since it's a test asset, it probably doesn't matter.

**Comment by MichaelSimons** [comment]
Darc is no longer utilized in source-build.  This issue is obsolete.
