### ISSUE TITLE
"LibGit2Sharp.LibGit2SharpException : SSL error : unknown error" during Darc clone

### ISSUE THREAD

**Issue by dagood** [dotnet/source-build#1894]
This has seemed to happen fairly often recently:

```
  dbug: Microsoft.DotNet.Darc.Operations.Operation[0]
        Cloning https://github.com/dotnet/roslyn to /src/artifacts/src/roslyn
  fail: Microsoft.DotNet.Darc.Operations.Operation[0]
        Something failed while cloning.
  System.Exception: Something went wrong when cloning repo https://github.com/dotnet/roslyn at <default branch> into /src/artifacts/src/roslyn
---> LibGit2Sharp.LibGit2SharpException : SSL error : unknown error [/src/tools-local/init-build.proj]
     at LibGit2Sharp.Core.Ensure.HandleError(Int32 result)
     at LibGit2Sharp.Core.Proxy.git_clone(String url, String workdir, GitCloneOptions& opts)
     at LibGit2Sharp.Repository.Clone(String sourceUrl, String workdirPath, CloneOptions options)
     at Microsoft.DotNet.DarcLib.RemoteRepoBase.Clone(String repoUri, String commit, String targetDirectory, ILogger _logger, String pat, String gitDirectory) in /_/src/Microsoft.DotNet.Darc/src/DarcLib/RemoteRepoBase.cs:line 163
     --- End of inner exception stack trace ---
     at Microsoft.DotNet.DarcLib.RemoteRepoBase.Clone(String repoUri, String commit, String targetDirectory, ILogger _logger, String pat, String gitDirectory) in /_/src/Microsoft.DotNet.Darc/src/DarcLib/RemoteRepoBase.cs:line 197
     at Microsoft.DotNet.DarcLib.GitHubClient.Clone(String repoUri, String commit, String targetDirectory, String gitDirectory) in /_/src/Microsoft.DotNet.Darc/src/DarcLib/GitHubClient.cs:line 939
     at Microsoft.DotNet.DarcLib.Remote.Clone(String repoUri, String commit, String targetDirectory, String gitDirectory) in /_/src/Microsoft.DotNet.Darc/src/DarcLib/Actions/Remote.cs:line 1019
     at Microsoft.DotNet.Darc.Operations.CloneOperation.HandleMasterCopyAndCreateGitDir(RemoteFactory remoteFactory, String repoUrl, String masterGitRepoPath, String masterRepoGitDirPath, String gitDirRedirect, ILogger log) in /_/src/Microsoft.DotNet.Darc/src/Darc/Operations/CloneOperation.cs:line 291
     at Microsoft.DotNet.Darc.Operations.CloneOperation.HandleMasterCopyWithGitDirPath(RemoteFactory remoteFactory, String repoUrl, String masterGitRepoPath, String masterRepoGitDirPath, ILogger log) in /_/src/Microsoft.DotNet.Darc/src/Darc/Operations/CloneOperation.cs:line 279
     at Microsoft.DotNet.Darc.Operations.CloneOperation.HandleMasterCopy(RemoteFactory remoteFactory, String repoUrl, String masterGitRepoPath, String masterRepoGitDirPath, ILogger log) in /_/src/Microsoft.DotNet.Darc/src/Darc/Operations/CloneOperation.cs:line 232
     at Microsoft.DotNet.Darc.Operations.CloneOperation.ExecuteAsync() in /_/src/Microsoft.DotNet.Darc/src/Darc/Operations/CloneOperation.cs:line 109
/src/tools-local/init-build.proj(119,5): error MSB3073: The command "/src/.dotnet/dotnet /src/.dotnet/tools/.store/microsoft.dotnet.darc/1.1.0-beta.19568.2/microsoft.dotnet.darc/1.1.0-beta.19568.2/tools/netcoreapp3.0/any/Microsoft.DotNet.Darc.dll clone  --git-dir-folder /src/.git/modules/src/ --include-toolset --ignore-repos ";https://dev.azure.com/dnceng/internal/_git/dotnet-optimization;https://dev.azure.com/devdiv/DevDiv/_git/DotNet-Trusted;https://devdiv.visualstudio.com/DevDiv/_git/DotNet-Trusted;https://dnceng@dev.azure.com/dnceng/internal/_git/dotnet-optimization;https://dev.azure.com/dnceng/internal/_git/dotnet-core-setup;***-reference-packages" --debug --azdev-pat bogus --github-pat bogus --depth 0 --repos-folder /src/artifacts/src/" exited with code 42.
```

https://dev.azure.com/dnceng/public/_build/results?buildId=888964&view=logs&j=9b3a01c3-0241-5c9d-d323-be413e779cbc&t=1257c5f8-e57f-517e-a4d8-ba42d8577ca9&l=735 (CentOS 7.1)

For now I've been hitting retry, and it doesn't seem *extremely* flaky.

It would be nice to get [runfo](https://github.com/jaredpar/runfo/tree/master/runfo) tracking this, but I haven't worked with it yet.

**Comment by dagood** [comment]
Triage notes: Consider adding retries somewhere in Darc itself.

**Comment by MichaelSimons** [comment]
Darc is no longer utilized in source-build. This issue is obsolete.
