### ISSUE TITLE
[release/5.0] sos's ip2md leads to an error: Could not load file or assembly: System.Memory...

### ISSUE THREAD

**Issue by omajid** [dotnet/source-build#1938]
I built source-build commit  337413b on Fedora 33 and tried running this SOS+LLDB test against it:

https://github.com/redhat-developer/dotnet-regular-tests/blob/main/debugging-sos-lldb-via-core/test.sh

This failed with an error:

```
+ lldb --batch -c coredump.584202 --one-line 'ip2md 00007f6369ece60b'
warning: (x86_64) /usr/lib64/dotnet/dotnet unsupported DW_FORM values: 0x1f20 0x1f21
warning: (x86_64) /usr/lib64/dotnet/host/fxr/5.0.0/libhostfxr.so unsupported DW_FORM values: 0x1f20 0x1f21
warning: (x86_64) /usr/lib64/dotnet/shared/Microsoft.NETCore.App/5.0.0/libhostpolicy.so unsupported DW_FORM values: 0x1f20 0x1f21
warning: (x86_64) /usr/lib64/dotnet/shared/Microsoft.NETCore.App/5.0.0/libcoreclr.so unsupported DW_FORM values: 0x1f20 0x1f21
warning: (x86_64) /usr/lib64/dotnet/shared/Microsoft.NETCore.App/5.0.0/libcoreclrtraceptprovider.so unsupported DW_FORM values: 0x1f20 0x1f21
warning: (x86_64) /usr/lib64/dotnet/shared/Microsoft.NETCore.App/5.0.0/libclrjit.so unsupported DW_FORM values: 0x1f20 0x1f21
warning: (x86_64) /usr/lib64/dotnet/shared/Microsoft.NETCore.App/5.0.0/libSystem.Native.so unsupported DW_FORM values: 0x1f20 0x1f21
Unhandled exception. System.IO.FileLoadException: Could not load file or assembly 'System.Memory, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
File name: 'System.Memory, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
   at System.Linq.EnumerableSorter`2.QuickSort(Int32[] keys, Int32 lo, Int32 hi)
   at System.Linq.EnumerableSorter`1.Sort(TElement[] elements, Int32 count)
   at System.Linq.OrderedEnumerable`1.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Microsoft.FileFormats.LayoutManagerExtensions.GetTStructLayout(Type tStructType, LayoutManager layoutManager, IEnumerable`1 enabledDefines, Type requiredBaseType)
   at Microsoft.FileFormats.LayoutManagerExtensions.<>c__DisplayClass10_0.<AddReflectionTypes>b__0(Type type, LayoutManager layoutManager)
   at Microsoft.FileFormats.LayoutManager.GetLayout(Type t)
   at Microsoft.FileFormats.LayoutManager.GetLayout[T]()
   at Microsoft.FileFormats.Reader.SizeOf[T]()
   at Microsoft.FileFormats.ELF.ELFFile.IsValid()
   at Microsoft.SymbolStore.KeyGenerators.ELFFileKeyGenerator.IsValid()
   at Microsoft.SymbolStore.KeyGenerators.ELFFileKeyGenerator.GetKeys(KeyTypeFlags flags)+MoveNext()
   at SOS.SymbolReader.LoadNativeSymbols(SymbolFileCallback callback, IntPtr parameter, RuntimeConfiguration config, String moduleFilePath, UInt64 address, Int32 size, ReadMemoryDelegate readMemory)
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace.
Stack dump:
0.      Program arguments: lldb --batch -c coredump.584202 --one-line ip2md 00007f6369ece60b 
1.      HandleCommand(command = "ip2md 00007f6369ece60b")
 #0 0x00007fd847e8627a llvm::sys::PrintStackTrace(llvm::raw_ostream&) (/lib64/libLLVM-11.so+0xa8b27a)
 #1 0x00007fd847e844e4 llvm::sys::RunSignalHandlers() (/lib64/libLLVM-11.so+0xa894e4)
 #2 0x00007fd847e84676 (/lib64/libLLVM-11.so+0xa89676)
 #3 0x00007fd847085a60 __restore_rt (/lib64/libc.so.6+0x3da60)
 #4 0x00007fd8470859d5 raise (/lib64/libc.so.6+0x3d9d5)
 #5 0x00007fd84706e8a4 abort (/lib64/libc.so.6+0x268a4)
 #6 0x00007fd84344f44e /usr/src/debug/dotnet5.0-5.0.100-0.5.20201202git337413b.fc34.x86_64/src/runtime.cf258a14b70ad9069470a108f13765e0e5988f51/src/coreclr/src/pal/src/thread/process.cpp:3474:5
 #7 0x00007fd84344f39c /usr/src/debug/dotnet5.0-5.0.100-0.5.20201202git337413b.fc34.x86_64/src/runtime.cf258a14b70ad9069470a108f13765e0e5988f51/src/coreclr/src/pal/src/thread/process.cpp:1472:13
 #8 0x00007fd84323c9cd /usr/src/debug/dotnet5.0-5.0.100-0.5.20201202git337413b.fc34.x86_64/src/runtime.cf258a14b70ad9069470a108f13765e0e5988f51/src/coreclr/src/vm/exceptionhandling.cpp:0:0
 #9 0x00007fd84323ca13 /usr/src/debug/dotnet5.0-5.0.100-0.5.20201202git337413b.fc34.x86_64/src/runtime.cf258a14b70ad9069470a108f13765e0e5988f51/src/coreclr/src/vm/exceptionhandling.cpp:0:17
#10 0x00007fd8430d4003 /usr/src/debug/dotnet5.0-5.0.100-0.5.20201202git337413b.fc34.x86_64/src/runtime.cf258a14b70ad9069470a108f13765e0e5988f51/src/coreclr/src/vm/prestub.cpp:0:9
#11 0x00007fd8432dca0c /usr/src/debug/dotnet5.0-5.0.100-0.5.20201202git337413b.fc34.x86_64/src/runtime.cf258a14b70ad9069470a108f13765e0e5988f51/src/coreclr/src/vm/amd64/theprestubamd64.S:18:0
#12 0x00007fd7ca908dac 
./test.sh: line 19: 584443 Aborted                 (core dumped) lldb --batch -c "${coredump}" "${commands[@]}"
```

I see similar errors on RHEL 8 too.

**Comment by omajid** [comment]
cc @tmds

**Comment by tmds** [comment]
Looks like there is an issue with the finding the expected `System.Memory` assembly.

Can I install your packages?

**Comment by tmds** [comment]
This test also fails with the Microsoft sdk, but not at the same place. So it has a different root cause.
```
(lldb) ip2md 00007f18a12fe75b
MethodDesc:   00007f18a227f770
Method Name:          ILStubClass.IL_STUB_PInvoke(System.Runtime.InteropServices.SafeHandle, Byte*, Int32)
Class:                00007f18a1ed8af0
MethodTable:          00007f18a1ed8b58
mdToken:              0000000006000000
Module:               00007f18a1762b80
IsJitted:             yes
Current CodeAddr:     00007f18a12fe6c0
Version History:
  ILCodeVersion:      0000000000000000
  ReJIT ID:           0
  IL Addr:            0000000000000000
     CodeAddr:           00007f18a12fe6c0  (Optimized)
     NativeCodeVersion:  0000000000000000
+ grep IsJitted lldb.out
IsJitted:             yes
+ echo '[clru]'
[clru]
+ lldb-core 'clru 00007f18a12fe75b'
+ commands=()
+ [[ 1 -ne 0 ]]
+ command='clru 00007f18a12fe75b'
+ commands+=('--one-line' "${command}")
+ shift
+ [[ 0 -ne 0 ]]
+ lldb --batch -c coredump.65672 --one-line 'clru 00007f18a12fe75b'
Exit Code: 1
# Standard Error:
```

**Comment by omajid** [comment]
> Can I install your packages?

Can you try with the latest copr build? https://copr.fedorainfracloud.org/coprs/g/dotnet-sig/dotnet-preview/build/1810599/

A self built build should also reproduce.

**Comment by tmds** [comment]
I've installed the rpms:
```
dotnet-apphost-pack-5.0.x86_64                         5.0.0-0.5.20201202git337413b.fc33~bootstrap   @@commandline                                                  
dotnet-apphost-pack-5.0-debuginfo.x86_64               5.0.0-0.5.20201202git337413b.fc33~bootstrap   @@commandline                                                  
dotnet-host.x86_64                                     5.0.0-0.5.20201202git337413b.fc33~bootstrap   @copr:copr.fedorainfracloud.org:group_dotnet-sig:dotnet-preview
dotnet-host-debuginfo.x86_64                           5.0.0-0.5.20201202git337413b.fc33~bootstrap   @@commandline                                                  
dotnet-hostfxr-5.0.x86_64                              5.0.0-0.5.20201202git337413b.fc33~bootstrap   @@commandline                                                  
dotnet-hostfxr-5.0-debuginfo.x86_64                    5.0.0-0.5.20201202git337413b.fc33~bootstrap   @@commandline                                                  
dotnet-runtime-5.0.x86_64                              5.0.0-0.5.20201202git337413b.fc33~bootstrap   @@commandline                                                  
dotnet-runtime-5.0-debuginfo.x86_64                    5.0.0-0.5.20201202git337413b.fc33~bootstrap   @@commandline                                                  
dotnet-sdk-5.0.x86_64                                  5.0.100-0.5.20201202git337413b.fc33~bootstrap @@commandline                                                  
dotnet-sdk-5.0-debuginfo.x86_64                        5.0.100-0.5.20201202git337413b.fc33~bootstrap @@commandline                                                  
dotnet-targeting-pack-5.0.x86_64                       5.0.0-0.5.20201202git337413b.fc33~bootstrap   @@commandline                                                  
dotnet-templates-5.0.x86_64                            5.0.100-0.5.20201202git337413b.fc33~bootstrap @@commandline                                                  
dotnet5.0-debuginfo.x86_64                             5.0.100-0.5.20201202git337413b.fc33~bootstrap @copr:copr.fedorainfracloud.org:group_dotnet-sig:dotnet-preview
dotnet5.0-debugsource.x86_64                           5.0.100-0.5.20201202git337413b.fc33~bootstrap @copr:copr.fedorainfracloud.org:group_dotnet-sig:dotnet-preview
netstandard-targeting-pack-2.1.x86_64                  5.0.100-0.5.20201202git337413b.fc33~bootstrap @copr:copr.fedorainfracloud.org:group_dotnet-sig:dotnet-preview

```
When running the test, I don't get the exception about the `System.Memory` assembly:
```
...
+ lldb --batch -c coredump.108899 --one-line 'ip2md 00007f3588cfe60b'
warning: (x86_64) /usr/lib64/dotnet/dotnet unsupported DW_FORM values: 0x1f20 0x1f21
warning: (x86_64) /usr/lib64/dotnet/host/fxr/5.0.0/libhostfxr.so unsupported DW_FORM values: 0x1f20 0x1f21
warning: (x86_64) /usr/lib64/dotnet/shared/Microsoft.NETCore.App/5.0.0/libhostpolicy.so unsupported DW_FORM values: 0x1f20 0x1f21
warning: (x86_64) /usr/lib64/dotnet/shared/Microsoft.NETCore.App/5.0.0/libcoreclr.so unsupported DW_FORM values: 0x1f20 0x1f21
warning: (x86_64) /usr/lib64/dotnet/shared/Microsoft.NETCore.App/5.0.0/libcoreclrtraceptprovider.so unsupported DW_FORM values: 0x1f20 0x1f21
warning: (x86_64) /usr/lib64/dotnet/shared/Microsoft.NETCore.App/5.0.0/libclrjit.so unsupported DW_FORM values: 0x1f20 0x1f21
warning: (x86_64) /usr/lib64/dotnet/shared/Microsoft.NETCore.App/5.0.0/libSystem.Native.so unsupported DW_FORM values: 0x1f20 0x1f21
+ cat lldb.out
Added Microsoft public symbol server
(lldb) target create --core "coredump.108899"
Core file '/home/tmds/repos/dotnet-regular-tests/debugging-sos-lldb-via-core/TestDir/coredump.108899' (x86_64) was loaded.

(lldb) ip2md 00007f3588cfe60b
MethodDesc:   00007f3589c7e848
Method Name:          ILStubClass.IL_STUB_PInvoke(System.Runtime.InteropServices.SafeHandle, Byte*, Int32)
Class:                00007f35898d8af0
MethodTable:          00007f35898d8b58
mdToken:              0000000006000000
Module:               00007f3589162b80
IsJitted:             yes
Current CodeAddr:     00007f3588cfe570
Version History:
  ILCodeVersion:      0000000000000000
  ReJIT ID:           0
  IL Addr:            0000000000000000
     CodeAddr:           00007f3588cfe570  (Optimized)
     NativeCodeVersion:  0000000000000000
+ grep IsJitted lldb.out
IsJitted:             yes
+ echo '[clru]'
[clru]
+ lldb-core 'clru 00007f3588cfe60b'
+ commands=()
+ [[ 1 -ne 0 ]]
+ command='clru 00007f3588cfe60b'
+ commands+=('--one-line' "${command}")
+ shift
+ [[ 0 -ne 0 ]]
+ lldb --batch -c coredump.108899 --one-line 'clru 00007f3588cfe60b'
warning: (x86_64) /usr/lib64/dotnet/dotnet unsupported DW_FORM values: 0x1f20 0x1f21
warning: (x86_64) /usr/lib64/dotnet/host/fxr/5.0.0/libhostfxr.so unsupported DW_FORM values: 0x1f20 0x1f21
warning: (x86_64) /usr/lib64/dotnet/shared/Microsoft.NETCore.App/5.0.0/libhostpolicy.so unsupported DW_FORM values: 0x1f20 0x1f21
warning: (x86_64) /usr/lib64/dotnet/shared/Microsoft.NETCore.App/5.0.0/libcoreclr.so unsupported DW_FORM values: 0x1f20 0x1f21
warning: (x86_64) /usr/lib64/dotnet/shared/Microsoft.NETCore.App/5.0.0/libcoreclrtraceptprovider.so unsupported DW_FORM values: 0x1f20 0x1f21
warning: (x86_64) /usr/lib64/dotnet/shared/Microsoft.NETCore.App/5.0.0/libclrjit.so unsupported DW_FORM values: 0x1f20 0x1f21
warning: (x86_64) /usr/lib64/dotnet/shared/Microsoft.NETCore.App/5.0.0/libSystem.Native.so unsupported DW_FORM values: 0x1f20 0x1f21
```

**Comment by dseefeld** [comment]
@omajid Is this still a problem?

**Comment by omajid** [comment]
I don't see these errors on RHEL 8 anymore. I am going to re-try on Fedora next week.

**Comment by omajid** [comment]
> This test also fails with the Microsoft sdk, but not at the same place. So it has a different root cause.
>
>     + lldb --batch -c coredump.65672 --one-line 'clru 00007f18a12fe75b'
>     Exit Code: 1

I reported this one as https://github.com/dotnet/diagnostics/issues/1907

**Comment by omajid** [comment]
The System.Memory issues do not reproduce for me anymore.
