### ISSUE TITLE
Error cloning ApplicationInsights-dotnet in 3.1 and 5.0

### ISSUE THREAD

**Issue by omajid** [dotnet/source-build#2227]
I am seeing this in a build machine:

5.0:

```
  [40m[37mdbug[39m[22m[49m: Microsoft.DotNet.Darc.Operations.Operation[0]
        Fetching +refs/heads/*:refs/remotes/origin/* from https://github.com/Microsoft/ApplicationInsights-dotnet in /home/tester/source-build/.git/modules/src/ApplicationInsights-dotnet.git/
  [40m[37mdbug[39m[22m[49m: Microsoft.DotNet.Darc.Operations.Operation[0]
        Post-fetch, trying to checkout /home/tester/source-build/artifacts/src/ApplicationInsights-dotnet.53b80940842204f78708a538628288ff5d741a1d/ at 53b80940842204f78708a538628288ff5d741a1d again
  [40m[1m[33mwarn[39m[22m[49m: Microsoft.DotNet.Darc.Operations.Operation[0]
        Couldn't check out one or more files, possibly due to path length limitations (LibGit2Sharp.NotFoundException: No valid git object identified by '53b80940842204f78708a538628288ff5d741a1d' exists in the repository.
           at LibGit2Sharp.Core.Ensure.GitObjectIsNotNull(GitObject gitObject, String identifier)
           at LibGit2Sharp.Repository.RevParse(String revision, Reference& reference, GitObject& obj)
           at LibGit2Sharp.Commands.Checkout(IRepository repository, String committishOrBranchSpec, CheckoutOptions options)
           at Microsoft.DotNet.DarcLib.Helpers.LibGit2SharpHelpers.SafeCheckout(Repository repo, String commit, CheckoutOptions options, ILogger log) in /_/src/Microsoft.DotNet.Darc/src/DarcLib/Helpers/LibGit2SharpHelpers.cs:line 35).  Attempting to checkout by individual files.
  [40m[37mdbug[39m[22m[49m: Microsoft.DotNet.Darc.Operations.Operation[0]
        Beginning individual file checkout for /home/tester/source-build/artifacts/src/ApplicationInsights-dotnet.53b80940842204f78708a538628288ff5d741a1d/ at 53b80940842204f78708a538628288ff5d741a1d
  [41m[30mfail[39m[22m[49m: Microsoft.DotNet.Darc.Operations.Operation[0]
        Something failed while cloning.
  System.Exception: Something went wrong when checking out 53b80940842204f78708a538628288ff5d741a1d in /home/tester/source-build/artifacts/src/ApplicationInsights-dotnet.53b80940842204f78708a538628288ff5d741a1d
   ---> System.NullReferenceException: Object reference not set to an instance of an object.
     at Microsoft.DotNet.DarcLib.Helpers.LibGit2SharpHelpers.SafeCheckoutByIndividualFiles(Repository repo, String commit, CheckoutOptions options, ILogger log) in /_/src/Microsoft.DotNet.Darc/src/DarcLib/Helpers/LibGit2SharpHelpers.cs:line 136
     at Microsoft.DotNet.DarcLib.Helpers.LibGit2SharpHelpers.SafeCheckout(Repository repo, String commit, CheckoutOptions options, ILogger log) in /_/src/Microsoft.DotNet.Darc/src/DarcLib/Helpers/LibGit2SharpHelpers.cs:line 52
     at Microsoft.DotNet.DarcLib.LocalGitClient.Checkout(String repoDir, String commit, Boolean force) in /_/src/Microsoft.DotNet.Darc/src/DarcLib/LocalGitClient.cs:line 320
     --- End of inner exception stack trace ---
     at Microsoft.DotNet.DarcLib.LocalGitClient.Checkout(String repoDir, String commit, Boolean force) in /_/src/Microsoft.DotNet.Darc/src/DarcLib/LocalGitClient.cs:line 362
     at Microsoft.DotNet.DarcLib.Local.Checkout(String commit, Boolean force) in /_/src/Microsoft.DotNet.Darc/src/DarcLib/Actions/Local.cs:line 141
     at Microsoft.DotNet.Darc.Operations.CloneOperation.HandleRepoAtSpecificHash(String repoPath, String commit, String masterRepoGitDirPath, ILogger log) in /_/src/Microsoft.DotNet.Darc/src/Darc/Operations/CloneOperation.cs:line 222
     at Microsoft.DotNet.Darc.Operations.CloneOperation.ExecuteAsync() in /_/src/Microsoft.DotNet.Darc/src/Darc/Operations/CloneOperation.cs:line 113
/home/tester/source-build/tools-local/init-build.proj(149,5): error MSB3073: The command "/home/tester/source-build/.dotnet/dotnet /home/tester/source-build/.dotnet/tools/.store/microsoft.dotnet.darc/1.1.0-beta.19568.2/microsoft.dotnet.darc/1.1.0-beta.19568.2/tools/netcoreapp3.0/any/Microsoft.DotNet.Darc.dll clone  --git-dir-folder /home/tester/source-build/.git/modules/src/ --include-toolset --ignore-repos ";https://dev.azure.com/dnceng/internal/_git/dotnet-optimization;https://dev.azure.com/devdiv/DevDiv/_git/DotNet-Trusted;https://devdiv.visualstudio.com/DevDiv/_git/DotNet-Trusted;https://dnceng@dev.azure.com/dnceng/internal/_git/dotnet-optimization;https://dev.azure.com/dnceng/internal/_git/dotnet-core-setup;https://github.com/dotnet/source-build-reference-packages" --debug --azdev-pat bogus --github-pat bogus --depth 0 --repos-folder /home/tester/source-build/artifacts/src/" exited with code 42.
```

Similar errors on 3.1:

```
 [40m[37mdbug[39m[22m[49m: Microsoft.DotNet.Darc.Operations.Operation[0]
        Fetching +refs/heads/*:refs/remotes/origin/* from https://github.com/Microsoft/ApplicationInsights-dotnet in /home/tester/source-build/.git/modules/src/ApplicationInsights-dotnet.git/
  [40m[37mdbug[39m[22m[49m: Microsoft.DotNet.Darc.Operations.Operation[0]
        Post-fetch, trying to checkout /home/tester/source-build/artifacts/src/ApplicationInsights-dotnet.53b80940842204f78708a538628288ff5d741a1d/ at 53b80940842204f78708a538628288ff5d741a1d again
  [40m[1m[33mwarn[39m[22m[49m: Microsoft.DotNet.Darc.Operations.Operation[0]
        Couldn't check out one or more files, possibly due to path length limitations (LibGit2Sharp.NotFoundException: No valid git object identified by '53b80940842204f78708a538628288ff5d741a1d' exists in the repository.
           at LibGit2Sharp.Core.Ensure.GitObjectIsNotNull(GitObject gitObject, String identifier)
           at LibGit2Sharp.Repository.RevParse(String revision, Reference& reference, GitObject& obj)
           at LibGit2Sharp.Commands.Checkout(IRepository repository, String committishOrBranchSpec, CheckoutOptions options)
           at Microsoft.DotNet.DarcLib.Helpers.LibGit2SharpHelpers.SafeCheckout(Repository repo, String commit, CheckoutOptions options, ILogger log) in /_/src/Microsoft.DotNet.Darc/src/DarcLib/Helpers/LibGit2SharpHelpers.cs:line 92).  Attempting to checkout by individual files.
  [40m[37mdbug[39m[22m[49m: Microsoft.DotNet.Darc.Operations.Operation[0]
        Beginning individual file checkout for /home/tester/source-build/artifacts/src/ApplicationInsights-dotnet.53b80940842204f78708a538628288ff5d741a1d/ at 53b80940842204f78708a538628288ff5d741a1d
  [41m[30mfail[39m[22m[49m: Microsoft.DotNet.Darc.Operations.Operation[0]
        Something failed while cloning.
  System.Exception: Something went wrong when checking out 53b80940842204f78708a538628288ff5d741a1d in /home/tester/source-build/artifacts/src/ApplicationInsights-dotnet.53b80940842204f78708a538628288ff5d741a1d
   ---> System.NullReferenceException: Object reference not set to an instance of an object.
     at Microsoft.DotNet.DarcLib.Helpers.LibGit2SharpHelpers.SafeCheckoutByIndividualFiles(Repository repo, String commit, CheckoutOptions options, ILogger log) in /_/src/Microsoft.DotNet.Darc/src/DarcLib/Helpers/LibGit2SharpHelpers.cs:line 136
     at Microsoft.DotNet.DarcLib.Helpers.LibGit2SharpHelpers.SafeCheckout(Repository repo, String commit, CheckoutOptions options, ILogger log) in /_/src/Microsoft.DotNet.Darc/src/DarcLib/Helpers/LibGit2SharpHelpers.cs:line 92
     at Microsoft.DotNet.DarcLib.LocalGitClient.Checkout(String repoDir, String commit, Boolean force) in /_/src/Microsoft.DotNet.Darc/src/DarcLib/LocalGitClient.cs:line 320
     --- End of inner exception stack trace ---
     at Microsoft.DotNet.DarcLib.LocalGitClient.Checkout(String repoDir, String commit, Boolean force) in /_/src/Microsoft.DotNet.Darc/src/DarcLib/LocalGitClient.cs:line 362
     at Microsoft.DotNet.DarcLib.Local.Checkout(String commit, Boolean force) in /_/src/Microsoft.DotNet.Darc/src/DarcLib/Actions/Local.cs:line 141
     at Microsoft.DotNet.Darc.Operations.CloneOperation.HandleRepoAtSpecificHash(String repoPath, String commit, String masterRepoGitDirPath, ILogger log) in /_/src/Microsoft.DotNet.Darc/src/Darc/Operations/CloneOperation.cs:line 222
     at Microsoft.DotNet.Darc.Operations.CloneOperation.ExecuteAsync() in /_/src/Microsoft.DotNet.Darc/src/Darc/Operations/CloneOperation.cs:line 113
/home/tester/source-build/tools-local/init-build.proj(204,5): error MSB3073: The command "/home/tester/source-build/.dotnet/dotnet /home/tester/source-build/.dotnet/tools/.store/microsoft.dotnet.darc/1.1.0-beta.19568.2/microsoft.dotnet.darc/1.1.0-beta.19568.2/tools/netcoreapp3.0/any/Microsoft.DotNet.Darc.dll clone  --git-dir-folder /home/tester/source-build/.git/modules/src/ --include-toolset --ignore-repos ";https://dev.azure.com/dnceng/internal/_git/dotnet-optimization;https://dev.azure.com/devdiv/DevDiv/_git/DotNet-Trusted;https://devdiv.visualstudio.com/DevDiv/_git/DotNet-Trusted;https://dnceng@dev.azure.com/dnceng/internal/_git/dotnet-optimization;https://github.com/dotnet/source-build-reference-packages" --debug --azdev-pat bogus --github-pat bogus --depth 0 --repos-folder /home/tester/source-build/artifacts/src/" exited with code 42.
```

https://github.com/microsoft/ApplicationInsights-dotnet/commit/53b80940842204f78708a538628288ff5d741a1d says:

> This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.

Which explains why git clone isn't seeing it. Sounds like ApplicationInsights-dotnet did a rebase or otherwise re-wrote history in a way that's now breaking source-build.

- Is there some way we can tell them to stop doing that?
- Can we make source-build more robust? Can we fetch specfic commits from github when cloning via darc?

**Comment by dseefeld** [comment]
Triage: #1642 addresses fetching commits via darc.  @dseefeld to follow up with App insights team to make sure the branch we need is protected.

**Comment by MichaelSimons** [comment]
[Triage] Closing as obsolete.
