### ISSUE TITLE
Cannot build Windows 10

### ISSUE THREAD

**Issue by mfilippov** [dotnet/source-build#232]
Cannot build on Windows 10
```
Done building target "WriteVersions" in project "repository.proj".
Target "BuildRepositoryAndDependencies" in project "C:\Work\source-build\targets\repository.proj" (entry point):
Done building target "BuildRepositoryAndDependencies" in project "repository.proj".
Done Building Project "C:\Work\source-build\targets\repository.proj" (BuildRepositoryAndDependencies target(s)).
Done executing task "MSBuild" -- FAILED.
Done building target "BuildRepositoryReferences" in project "repository.proj" -- FAILED.
Done Building Project "C:\Work\source-build\targets\repository.proj" (BuildRepositoryAndDependencies target(s)) -- FAILED.
Done executing task "MSBuild" -- FAILED.
Done building target "Build" in project "build.proj" -- FAILED.
Done Building Project "C:\Work\source-build\build.proj" (default targets) -- FAILED.

Build FAILED.

"C:\Work\source-build\build.proj" (default target) (1) ->
"C:\Work\source-build\tools-local\init-build.proj" (default target) (2) ->
"C:\Work\source-build\targets\repository.proj" (ApplyPatches target) (3:9) ->
(ApplyPatches target) ->
  EXEC : warning : scripts/build.sh has type 100644, expected 100755 [C:\Work\source-build\targets\repository.proj]


"C:\Work\source-build\build.proj" (default target) (1) ->
"C:\Work\source-build\tools-local\init-build.proj" (default target) (2) ->
"C:\Work\source-build\targets\repository.proj" (ApplyPatches target) (3:9) ->
  EXEC : warning : scripts/build.sh has type 100644, expected 100755 [C:\Work\source-build\targets\repository.proj]


"C:\Work\source-build\build.proj" (default target) (1) ->
"C:\Work\source-build\tools-local\init-build.proj" (default target) (2) ->
"C:\Work\source-build\targets\repository.proj" (ApplyPatches target) (3:9) ->
  EXEC : warning : scripts/build.sh has type 100644, expected 100755 [C:\Work\source-build\targets\repository.proj]


"C:\Work\source-build\build.proj" (default target) (1) ->
"C:\Work\source-build\tools-local\init-build.proj" (default target) (2) ->
"C:\Work\source-build\targets\repository.proj" (ApplyPatches target) (3:9) ->
  EXEC : warning : scripts/build.sh has type 100644, expected 100755 [C:\Work\source-build\targets\repository.proj]


"C:\Work\source-build\build.proj" (default target) (1) ->
"C:\Work\source-build\tools-local\init-build.proj" (default target) (2) ->
"C:\Work\source-build\targets\repository.proj" (ApplyPatches target) (3:9) ->
  EXEC : warning : scripts/build.sh has type 100644, expected 100755 [C:\Work\source-build\targets\repository.proj]


"C:\Work\source-build\build.proj" (default target) (1) ->
"C:\Work\source-build\tools-local\init-build.proj" (default target) (2) ->
"C:\Work\source-build\targets\repository.proj" (ApplyPatches target) (3:9) ->
  EXEC : warning : scripts/build.sh has type 100644, expected 100755 [C:\Work\source-build\targets\repository.proj]


"C:\Work\source-build\build.proj" (default target) (1) ->
"C:\Work\source-build\tools-local\init-build.proj" (default target) (2) ->
"C:\Work\source-build\targets\repository.proj" (ApplyPatches target) (3:12) ->
  EXEC : warning : build.sh has type 100644, expected 100755 [C:\Work\source-build\targets\repository.proj]
  EXEC : warning : tools/Build.sh has type 100644, expected 100755 [C:\Work\source-build\targets\repository.proj]


"C:\Work\source-build\build.proj" (default target) (1) ->
"C:\Work\source-build\tools-local\init-build.proj" (default target) (2) ->
"C:\Work\source-build\targets\repository.proj" (ApplyPatches target) (3:12) ->
  EXEC : warning : build-core.sh has type 100644, expected 100755 [C:\Work\source-build\targets\repository.proj]


"C:\Work\source-build\build.proj" (default target) (1) ->
"C:\Work\source-build\tools-local\init-build.proj" (default target) (2) ->
"C:\Work\source-build\targets\repository.proj" (ApplyPatches target) (3:14) ->
  EXEC : warning : build_projects/update-dependencies/update-dependencies.sh has type 100644, expected 100755 [C:\Work\source-build\targets\repository.proj]
  EXEC : warning : run-build.sh has type 100644, expected 100755 [C:\Work\source-build\targets\repository.proj]


"C:\Work\source-build\build.proj" (default target) (1) ->
"C:\Work\source-build\tools-local\init-build.proj" (default target) (2) ->
"C:\Work\source-build\targets\repository.proj" (ApplyPatches target) (3:14) ->
  EXEC : warning : build_projects/update-dependencies/update-dependencies.sh has type 100644, expected 100755 [C:\Work\source-build\targets\repository.proj]


"C:\Work\source-build\build.proj" (default target) (1) ->
"C:\Work\source-build\tools-local\init-build.proj" (default target) (2) ->
"C:\Work\source-build\targets\repository.proj" (ApplyPatches target) (3:17) ->
  EXEC : warning : src/buildfromsource.sh has type 100644, expected 100755 [C:\Work\source-build\targets\repository.proj]


"C:\Work\source-build\build.proj" (default target) (1) ->
"C:\Work\source-build\tools-local\init-build.proj" (default target) (2) ->
"C:\Work\source-build\targets\repository.proj" (ApplyPatches target) (3:17) ->
  EXEC : warning : src/buildfromsource.sh has type 100644, expected 100755 [C:\Work\source-build\targets\repository.proj]


"C:\Work\source-build\build.proj" (default target) (1) ->
"C:\Work\source-build\targets\repository.proj" (BuildRepositoryAndDependencies target) (3:25) ->
"C:\Work\source-build\targets\repository.proj" (BuildRepositoryAndDependencies target) (3:27) ->
"C:\Work\source-build\targets\repository.proj" (BuildRepositoryAndDependencies target) (3:29) ->
(Build target) ->
  MASM : warning A4018: invalid command-line option : /Yustdafx.h [C:\Work\source-build\src\coreclr\bin\obj\Windows_NT.x64.Release\src\debug\di\cordbdi.vcxproj] [C:\Work\source-build\targets\repository.proj]
  MASM : warning A4018: invalid command-line option : /FpC:/Work/source-build/src/coreclr/bin/obj/Windows_NT.x64.Release/src/debug/di/Release/stdafx.pch [C:\Work\source-build\src\coreclr\bin\obj\Windows_NT.x64.Release\src\debug\di\cordbdi.vcxproj] [C:\Work\source-build\targets\repository.proj]
  PGOMGR : warning PG0188: No .PGC files matching 'C:\Work\source-build\packages\optimization.windows_nt-x64.pgo.coreclr\2.0.0-release-20170711-0120\data\clrjit!*.pgc' were found. [C:\Work\source-build\src\coreclr\bin\obj\Windows_NT.x64.Release\src\jit\standalone\clrjit.vcxproj] [C:\Work\source-build\targets\repository.proj]
  PGOMGR : warning PG0188: No .PGC files matching 'C:\Work\source-build\packages\optimization.windows_nt-x64.pgo.coreclr\2.0.0-release-20170711-0120\data\coreclr!*.pgc' were found. [C:\Work\source-build\src\coreclr\bin\obj\Windows_NT.x64.Release\src\dlls\mscoree\coreclr\coreclr.vcxproj] [C:\Work\source-build\targets\repository.proj]
  MASM : warning A4018: invalid command-line option : /Yustdafx.h [C:\Work\source-build\src\coreclr\bin\obj\Windows_NT.x64.Release\src\debug\di\cordbdi.vcxproj] [C:\Work\source-build\targets\repository.proj]
  MASM : warning A4018: invalid command-line option : /FpC:/Work/source-build/src/coreclr/bin/obj/Windows_NT.x64.Release/src/debug/di/Release/stdafx.pch [C:\Work\source-build\src\coreclr\bin\obj\Windows_NT.x64.Release\src\debug\di\cordbdi.vcxproj] [C:\Work\source-build\targets\repository.proj]
  PGOMGR : warning PG0188: No .PGC files matching 'C:\Work\source-build\packages\optimization.windows_nt-x64.pgo.coreclr\2.0.0-release-20170711-0120\data\clrjit!*.pgc' were found. [C:\Work\source-build\src\coreclr\bin\obj\Windows_NT.x64.Release\src\jit\standalone\clrjit.vcxproj] [C:\Work\source-build\targets\repository.proj]
  PGOMGR : warning PG0188: No .PGC files matching 'C:\Work\source-build\packages\optimization.windows_nt-x64.pgo.coreclr\2.0.0-release-20170711-0120\data\coreclr!*.pgc' were found. [C:\Work\source-build\src\coreclr\bin\obj\Windows_NT.x64.Release\src\dlls\mscoree\coreclr\coreclr.vcxproj] [C:\Work\source-build\targets\repository.proj]


"C:\Work\source-build\build.proj" (default target) (1) ->
"C:\Work\source-build\targets\repository.proj" (BuildRepositoryAndDependencies target) (3:25) ->
"C:\Work\source-build\targets\repository.proj" (BuildRepositoryAndDependencies target) (3:34) ->
"C:\Work\source-build\targets\repository.proj" (BuildRepositoryAndDependencies target) (3:36) ->
  RestoreCommand\RequestFactory\NoOpRestoreResult.cs(27,36): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread. [C:\Work\source-build\src\nuget-client\src\NuGet.Core\NuGet.Commands\NuGet.Commands.csproj] [C:\Work\source-build\targets\repository.proj]


"C:\Work\source-build\build.proj" (default target) (1) ->
"C:\Work\source-build\targets\repository.proj" (BuildRepositoryAndDependencies target) (3:25) ->
"C:\Work\source-build\targets\repository.proj" (BuildRepositoryAndDependencies target) (3:27) ->
"C:\Work\source-build\targets\repository.proj" (BuildRepositoryAndDependencies target) (3:29) ->
(Build target) ->
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" exited with code 1. [C:\Work\source-build\src\coreclr\bin\obj\Windows_NT.x64.Release\src\dlls\mscoree\coreclr\inject_debug_resources.vcxproj] [C:\Work\source-build\targets\repository.proj]
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" exited with code 1. [C:\Work\source-build\src\coreclr\bin\obj\Windows_NT.x64.Release\src\dlls\mscoree\coreclr\inject_debug_resources.vcxproj] [C:\Work\source-build\targets\repository.proj]
  BUILD : error : native component build failed. Refer to the build log files for details: [C:\Work\source-build\targets\repository.proj]
  C:\Work\source-build\targets\repository.proj(125,5): error MSB3073: The command "C:\Work\source-build\src/coreclr//build.cmd x64 Release skiptests -PortableBuild=false  " exited with code 1.

    23 Warning(s)
    4 Error(s)

Time Elapsed 00:38:17.64
Command failed to execute:  & "$CLIPATH\dotnet" "$SDKPATH/MSBuild.dll" "$SCRIPT_ROOT/build.proj" /flp:v=detailed
/clp:v=detailed $captured_args
At C:\Work\source-build\build.ps1:20 char:9
+         throw "Command failed to execute: $cmd"
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Command failed ...$captured_args :String) [], RuntimeException
    + FullyQualifiedErrorId : Command failed to execute:  & "$CLIPATH\dotnet" "$SDKPATH/MSBuild.dll" "$SCRIPT_ROOT/bui
   ld.proj" /flp:v=detailed /clp:v=detailed $captured_args
```

**Comment by weshaggard** [comment]
@mfilippov what branch are you building from? currently only the dev/release/2.0 branch builds for windows.

**Comment by mfilippov** [comment]
@weshaggard Yes I ty to build branch dev/release/2.0 on revision 6f32a197a37c08d17994002a35f00da75c7d4731

**Comment by weshaggard** [comment]
Can you sync to the tip of dev/release/2.0.0 branch and try again? I suspect you might be missing some of the coreclr build dependencies (https://github.com/dotnet/coreclr/blob/master/Documentation/building/windows-instructions.md).

**Comment by mfilippov** [comment]
@weshaggard I check VS2017 installation clean pull rebuild.  Error:
```
[23:48:22.95] Building 'cli-deps-satellites'...done
  'cli' failed during build see 'D:\Work\source-build\bin/logs/cli.log' for more information
Command failed to execute:  & "$CLIPATH\dotnet" "$SDKPATH/MSBuild.dll" "$SCRIPT_ROOT/build.proj" /flp:v=diag /bl
/clp:v=m $captured_args
At D:\Work\source-build\build.ps1:20 char:9
+         throw "Command failed to execute: $cmd"
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Command failed ...$captured_args :String) [], RuntimeException
    + FullyQualifiedErrorId : Command failed to execute:  & "$CLIPATH\dotnet" "$SDKPATH/MSBuild.dll" "$SCRIPT_ROOT/bui
   ld.proj" /flp:v=diag /bl /clp:v=m $captured_args
```
I see link on log file: 'D:\Work\source-build\bin/logs/cli.log' but this file not exists.

**Comment by weshaggard** [comment]
@mfilippov take a look at the msbuild.log file that gets produced in the repo root to see if you can find the specific error.

**Comment by mfilippov** [comment]
I check msbuild.log and found not reported error:
```
MDIFF;-DFEATURE_UNIX_AMD64_STRUCT_PASSING_ITF;-DFEATURE_USE_ASM_GC_WRITE_BARRIERS;-DFEATURE_VERSIONING_LOG;-DFEATURE_WIN32_REGISTRY;-DFEATURE_LEGACYNETCF_DBG_HOST_CONTROL;-DFEATURE_WINDOWSPHONE;-DFEATURE_WINMD_RESILIENT;-D_SECURE_SCL=0;-DUNICODE;-D_UNICODE  /FiD:/Work/source-build/src/coreclr/bin/obj/Windows_NT.x64.Release/src/dlls/mscoree/coreclr/coreclr.def  D:/Work/source-build/src/coreclr/src/dlls/mscoree/mscorwks_ntdef.src
    Microsoft (R) C/C++ Optimizing Compiler Version 19.11.25547 for x64
    Copyright (C) Microsoft Corporation.  All rights reserved.
    
    mscorwks_ntdef.src
    mscoree.cpp
    unixinterface.cpp
    comcallunmarshal.cpp
  PGOMGR : warning PG0188: No .PGC files matching 'D:\Work\source-build\packages\optimization.windows_nt-x64.pgo.coreclr\2.0.0-release-20170711-0120\data\coreclr!*.pgc' were found. [D:\Work\source-build\src\coreclr\bin\obj\Windows_NT.x64.Release\src\dlls\mscoree\coreclr\coreclr.vcxproj]
      Reading PGD file 1: D:\Work\source-build\packages\optimization.windows_nt-x64.pgo.coreclr\2.0.0-release-20170711-0120\data\coreclr.pgd
       Creating library D:/Work/source-build/src/coreclr/bin/obj/Windows_NT.x64.Release/src/dlls/mscoree/coreclr/Release/coreclr.lib and object D:/Work/source-build/src/coreclr/bin/obj/Windows_NT.x64.Release/src/dlls/mscoree/coreclr/Release/coreclr.exp
    Generating code
    
    952 of 979 (97.2%) original invalid call sites were matched.
    1249 new call sites were added.
    251 of 35389 (  0.71%) profiled functions will be compiled for speed, and the rest of the functions will be compiled for size
    57597 of 317880 inline instances were from dead/cold paths 
    35324 of 35444 functions (99.7%) were optimized using profile data, and the rest of the functions were optimized without using profile data
    17269549912 of 17358913696 instructions (99.5%) were optimized using profile data, and the rest of the instructions were optimized without using profile data
    Finished generating code
    coreclr.vcxproj -> D:\Work\source-build\src\coreclr\bin\obj\Windows_NT.x64.Release\src\dlls\mscoree\coreclr\Release\coreclr.dll
    Building Custom Rule D:/Work/source-build/src/coreclr/src/ildasm/exe/CMakeLists.txt
    Building Custom Rule D:/Work/source-build/src/coreclr/src/dlls/mscoree/coreclr/CMakeLists.txt
    CMake does not need to re-run because D:/Work/source-build/src/coreclr/bin/obj/Windows_NT.x64.Release/src/ildasm/exe/CMakeFiles/generate.stamp is up-to-date.
    CMake does not need to re-run because D:/Work/source-build/src/coreclr/bin/obj/Windows_NT.x64.Release/src/dlls/mscoree/coreclr/CMakeFiles/generate.stamp is up-to-date.
    coreclr
    Microsoft (R) C/C++ Optimizing Compiler Version 19.11.25547 for x64
    Copyright (C) Microsoft Corporation.  All rights reserved.
    
    daccess.cpp
    ceeload.cpp
    dasm.cpp
    dasm_formattype.cpp
    dasm_mi.cpp
    Microsoft (R) CLR External Data Access Data Table Generator Version 0.3
    Copyright (C) Microsoft Corp.  All rights reserved.
    
    dasm_sz.cpp
    BUILDMSG: System.Runtime.InteropServices.COMException (0x80040154): Retrieving the COM class factory for component with CLSID {3BFCEA48-620F-4B6B-81F7-B9AF75454C7D} failed due to the following error: 80040154 Class not registered (Exception from HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG)).
       at Dia.Util.DiaFile..ctor(String pdbFile, String dllFile)
       at PdbSymbolProvider..ctor(String symbolFilename, String dllFilename)
       at Shell.DoMain(String[] args)
       at Shell.Main(String[] args)
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" exited with code 1. [D:\Work\source-build\src\coreclr\bin\obj\Windows_NT.x64.Release\src\dlls\mscoree\coreclr\inject_debug_resources.vcxproj]
    Building Custom Rule D:/Work/source-build/src/coreclr/src/ilasm/CMakeLists.txt
    CMake does not need to re-run because D:/Work/source-build/src/coreclr/bin/obj/Windows_NT.x64.Release/src/ilasm/CMakeFiles/generate.stamp is up-to-date.
    assem.cpp
    writer.cpp
    writer_enc.cpp
    method.cpp
    dis.cpp
    dman.cpp
    dres.cpp
    ildasmpch.cpp
    asmman.cpp
    main.cpp
    assembler.cpp
    asmparse.cpp
    windasm.cpp
    Generating code
    Generating code
    Finished generating code
    ildasm.vcxproj -> D:\Work\source-build\src\coreclr\bin\obj\Windows_NT.x64.Release\src\ildasm\exe\Release\ildasm.exe
    Finished generating code
    ilasm.vcxproj -> D:\Work\source-build\src\coreclr\bin\obj\Windows_NT.x64.Release\src\ilasm\Release\ilasm.exe
  
  Build FAILED.
  
  MASM : warning A4018: invalid command-line option : /Yustdafx.h [D:\Work\source-build\src\coreclr\bin\obj\Windows_NT.x64.Release\src\debug\di\cordbdi.vcxproj]
  MASM : warning A4018: invalid command-line option : /FpD:/Work/source-build/src/coreclr/bin/obj/Windows_NT.x64.Release/src/debug/di/Release/stdafx.pch [D:\Work\source-build\src\coreclr\bin\obj\Windows_NT.x64.Release\src\debug\di\cordbdi.vcxproj]
  PGOMGR : warning PG0188: No .PGC files matching 'D:\Work\source-build\packages\optimization.windows_nt-x64.pgo.coreclr\2.0.0-release-20170711-0120\data\clrjit!*.pgc' were found. [D:\Work\source-build\src\coreclr\bin\obj\Windows_NT.x64.Release\src\jit\standalone\clrjit.vcxproj]
  PGOMGR : warning PG0188: No .PGC files matching 'D:\Work\source-build\packages\optimization.windows_nt-x64.pgo.coreclr\2.0.0-release-20170711-0120\data\coreclr!*.pgc' were found. [D:\Work\source-build\src\coreclr\bin\obj\Windows_NT.x64.Release\src\dlls\mscoree\coreclr\coreclr.vcxproj]
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" exited with code 1. [D:\Work\source-build\src\coreclr\bin\obj\Windows_NT.x64.Release\src\dlls\mscoree\coreclr\inject_debug_resources.vcxproj]
      4 Warning(s)
      1 Error(s)
```

**Comment by weshaggard** [comment]
I think you are hitting the same issue recently discussed in our gitter room (https://gitter.im/dotnet/source-build?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) where you need to registry msdia120.dll. See https://github.com/dotnet/coreclr/blob/master/Documentation/building/windows-instructions.md and search for msdia.

**Comment by mfilippov** [comment]
@weshaggard Great thanks. It's worked!
