### ISSUE TITLE
darc fails to resolve root directory properly

### ISSUE THREAD

**Issue by panekj** [dotnet/source-build#2531]
When trying to build, Darc finds `.git` earlier than expected and stops there

```none
  info: Microsoft.DotNet.Darc.Operations.Operation[0]
        Getting a collection of dependencies from 'eng/Version.Details.xml' in repo '/home/pj/Development/gitlab.alpinelinux.org/alpine/aports'...
  info: Microsoft.DotNet.Darc.Operations.Operation[0]
        Reading 'eng/Version.Details.xml' in repo '/home/pj/Development/gitlab.alpinelinux.org/alpine/aports' and branch ''...
  fail: Microsoft.DotNet.Darc.Operations.Operation[0]
        Something failed while cloning.
  System.IO.DirectoryNotFoundException: Could not find a part of the path '/home/pj/Development/gitlab.alpinelinux.org/alpine/aports/eng/Version.Details.xml'.
```

<details>
<summary>Log</summary>

```none
>>> dotnet5-SDK: Checking sanity of /home/pj/Development/gitlab.alpinelinux.org/alpine/aports/testing/dotnet5/APKBUILD...
>>> dotnet5-SDK: Cleaning up srcdir
>>> dotnet5-SDK: Cleaning up pkgdir
>>> dotnet5-SDK: Fetching dotnet5-5.0.207.tar.gz::https://github.com/dotnet/source-build/archive/refs/tags/v5.0.207-SDK.tar.gz
>>> dotnet5-SDK: Fetching dotnet5-5.0.207.tar.gz::https://github.com/dotnet/source-build/archive/refs/tags/v5.0.207-SDK.tar.gz
>>> dotnet5-SDK: Checking sha512sums...
dotnet5-5.0.207.tar.gz: OK
>>> dotnet5-SDK: Preparing build chroot...
fetch http://dl-cdn.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/edge/community/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/edge/testing/x86_64/APKINDEX.tar.gz
(1/142) Installing musl (1.2.2-r7)
(2/142) Installing fakeroot (1.25.3-r3)
(3/142) Installing scanelf (1.3.3-r0)
(4/142) Installing libcrypto3 (3.0.0-r2)
(5/142) Installing libssl3 (3.0.0-r2)
(6/142) Installing openssl (3.0.0-r2)
(7/142) Installing ca-certificates-bundle (20191127-r7)
(8/142) Installing libcrypto1.1 (1.1.1l-r4)
(9/142) Installing libssl1.1 (1.1.1l-r4)
(10/142) Installing zlib (1.2.11-r3)
(11/142) Installing apk-tools (2.12.7-r3)
(12/142) Installing musl-utils (1.2.2-r7)
(13/142) Installing libc-utils (0.7.2-r3)
(14/142) Installing libattr (2.5.1-r0)
(15/142) Installing attr (2.5.1-r0)
(16/142) Installing libacl (2.2.53-r0)
(17/142) Installing tar (1.34-r0)
(18/142) Installing pkgconf (1.8.0-r0)
(19/142) Installing patch (2.7.6-r7)
(20/142) Installing libgcc (10.3.1_git20210921-r1)
(21/142) Installing libstdc++ (10.3.1_git20210921-r1)
(22/142) Installing lzip (1.22-r1)
(23/142) Installing busybox (1.34.1-r1)
Executing busybox-1.34.1-r1.post-install
(24/142) Installing ca-certificates (20191127-r7)
(25/142) Installing brotli-libs (1.0.9-r5)
(26/142) Installing nghttp2-libs (1.44.0-r2)
(27/142) Installing libcurl (7.79.1-r0)
(28/142) Installing curl (7.79.1-r0)
(29/142) Installing abuild (3.9.0_rc2-r1)
Executing abuild-3.9.0_rc2-r1.pre-install
(30/142) Installing alpine-baselayout (3.2.0-r18)
Executing alpine-baselayout-3.2.0-r18.pre-install
Executing alpine-baselayout-3.2.0-r18.post-install
(31/142) Installing ifupdown-ng (0.11.3-r0)
(32/142) Installing openrc (0.44.6-r1)
Executing openrc-0.44.6-r1.post-install
(33/142) Installing alpine-conf (3.12.0-r0)
(34/142) Installing busybox-suid (1.34.1-r1)
(35/142) Installing busybox-initscripts (3.3-r1)
Executing busybox-initscripts-3.3-r1.post-install
(36/142) Installing alpine-keys (2.3-r1)
(37/142) Installing alpine-base (3.15.0_alpha20210804-r0)
(38/142) Installing ncurses-terminfo-base (6.2_p20211009-r0)
(39/142) Installing ncurses-libs (6.2_p20211009-r0)
(40/142) Installing readline (8.1.1-r0)
(41/142) Installing bash (5.1.8-r0)
Executing bash-5.1.8-r0.post-install
(42/142) Installing binutils (2.37-r3)
(43/142) Installing libmagic (5.40-r1)
(44/142) Installing file (5.40-r1)
(45/142) Installing libgomp (10.3.1_git20210921-r1)
(46/142) Installing libatomic (10.3.1_git20210921-r1)
(47/142) Installing libgphobos (10.3.1_git20210921-r1)
(48/142) Installing gmp (6.2.1-r0)
(49/142) Installing isl22 (0.22-r0)
(50/142) Installing mpfr4 (4.1.0-r0)
(51/142) Installing mpc1 (1.2.1-r0)
(52/142) Installing gcc (10.3.1_git20210921-r1)
(53/142) Installing musl-dev (1.2.2-r7)
(54/142) Installing libc-dev (0.7.2-r3)
(55/142) Installing g++ (10.3.1_git20210921-r1)
(56/142) Installing make (4.3-r0)
(57/142) Installing fortify-headers (1.1-r1)
(58/142) Installing build-base (0.5-r2)
(59/142) Installing libffi (3.4.2-r1)
(60/142) Installing xz-libs (5.2.5-r0)
(61/142) Installing libxml2 (2.9.12-r1)
(62/142) Installing llvm11-libs (11.1.0-r3)
(63/142) Installing clang-libs (11.1.0-r2)
(64/142) Installing clang (11.1.0-r2)
(65/142) Installing libbz2 (1.0.8-r1)
(66/142) Installing expat (2.4.1-r0)
(67/142) Installing lz4-libs (1.9.3-r0)
(68/142) Installing zstd-libs (1.5.0-r0)
(69/142) Installing libarchive (3.5.2-r2)
(70/142) Installing rhash-libs (1.4.2-r2)
(71/142) Installing libuv (1.42.0-r0)
(72/142) Installing cmake (3.21.3-r0)
(73/142) Installing libintl (0.21-r0)
(74/142) Installing libunistring (0.9.10-r1)
(75/142) Installing gettext-libs (0.21-r0)
(76/142) Installing gettext (0.21-r0)
(77/142) Installing pcre2 (10.37-r0)
(78/142) Installing git (2.33.1-r0)
(79/142) Installing icu-libs (69.1-r0)
(80/142) Installing icu (69.1-r0)
(81/142) Installing icu-dev (69.1-r0)
(82/142) Installing util-linux (2.37.2-r1)
(83/142) Installing libblkid (2.37.2-r1)
(84/142) Installing libeconf (0.4.1-r0)
(85/142) Installing libuuid (2.37.2-r1)
(86/142) Installing libfdisk (2.37.2-r1)
(87/142) Installing libmount (2.37.2-r1)
(88/142) Installing libsmartcols (2.37.2-r1)
(89/142) Installing util-linux-misc (2.37.2-r1)
(90/142) Installing linux-pam (1.5.2-r0)
(91/142) Installing runuser (2.37.2-r1)
(92/142) Installing hexdump (2.37.2-r1)
(93/142) Installing uuidgen (2.37.2-r1)
(94/142) Installing blkid (2.37.2-r1)
(95/142) Installing sfdisk (2.37.2-r1)
(96/142) Installing mcookie (2.37.2-r1)
(97/142) Installing wipefs (2.37.2-r1)
(98/142) Installing cfdisk (2.37.2-r1)
(99/142) Installing util-linux-openrc (2.37.2-r1)
(100/142) Installing flock (2.37.2-r1)
(101/142) Installing lsblk (2.37.2-r1)
(102/142) Installing libcap-ng (0.8.2-r0)
(103/142) Installing setpriv (2.37.2-r1)
(104/142) Installing logger (2.37.2-r1)
(105/142) Installing partx (2.37.2-r1)
(106/142) Installing findmnt (2.37.2-r1)
(107/142) Installing util-linux-dev (2.37.2-r1)
(108/142) Installing gawk (5.1.0-r0)
(109/142) Installing libcom_err (1.46.4-r0)
(110/142) Installing e2fsprogs-libs (1.46.4-r0)
(111/142) Installing e2fsprogs-dev (1.46.4-r0)
(112/142) Installing krb5-conf (1.0-r2)
(113/142) Installing keyutils-libs (1.6.3-r0)
(114/142) Installing libverto (0.3.2-r0)
(115/142) Installing krb5-libs (1.19.2-r2)
(116/142) Installing gdbm (1.20-r2)
(117/142) Installing libsasl (2.1.27-r14)
(118/142) Installing libldap (2.4.59-r3)
(119/142) Installing krb5-server-ldap (1.19.2-r2)
(120/142) Installing krb5-dev (1.19.2-r2)
(121/142) Installing libltdl (2.4.6-r7)
(122/142) Installing libtool (2.4.6-r7)
(123/142) Installing libucontext (1.1-r0)
(124/142) Installing libucontext-dev (1.1-r0)
(125/142) Installing libunwind (1.5.0-r1)
(126/142) Installing libunwind-dev (1.5.0-r1)
(127/142) Installing linux-headers (5.10.41-r0)
(128/142) Installing libedit (20210910.3.1-r0)
(129/142) Installing mpdecimal (2.5.1-r1)
(130/142) Installing sqlite-libs (3.36.0-r0)
(131/142) Installing python3 (3.9.7-r3)
(132/142) Installing lldb (11.1.0-r3)
(133/142) Installing lldb-dev (11.1.0-r3)
(134/142) Installing llvm11 (11.1.0-r3)
(135/142) Installing llvm11-dev (11.1.0-r3)
(136/142) Installing userspace-rcu (0.12.2-r0)
(137/142) Installing lttng-ust (2.12.0-r3)
(138/142) Installing userspace-rcu-dev (0.12.2-r0)
(139/142) Installing py3-lttng (2.12.0-r3)
(140/142) Installing lttng-ust-dev (2.12.0-r3)
(141/142) Installing openssl1.1-compat-dev (1.1.1l-r4)
(142/142) Installing zlib-dev (1.2.11-r3)
Executing busybox-1.34.1-r1.trigger
Executing ca-certificates-20191127-r7.trigger
OK: 688 MiB in 142 packages
>>> dotnet5-SDK: Fetching dotnet5-5.0.207.tar.gz::https://github.com/dotnet/source-build/archive/refs/tags/v5.0.207-SDK.tar.gz
>>> dotnet5-SDK: Checking sha512sums...
dotnet5-5.0.207.tar.gz: OK
>>> dotnet5-SDK: Unpacking /var/cache/distfiles/dotnet5-5.0.207.tar.gz...
Found bootstrap SDK 5.0.206, bootstrap Arcade 5.0.0-beta.20426.4
+++ dirname ./build.sh
++ cd -P .
++ pwd
+ scriptroot=/home/pj/Development/gitlab.alpinelinux.org/alpine/aports/testing/dotnet5/src/source-build-5.0.207-SDK
+ /home/pj/Development/gitlab.alpinelinux.org/alpine/aports/testing/dotnet5/src/source-build-5.0.207-SDK/eng/common/dotnet-install.sh -runtime dotnet -version 3.1.1
Downloading 'https://dot.net/v1/dotnet-install.sh'
dotnet-install: Note that the intended use of this script is for Continuous Integration (CI) scenarios, where:
dotnet-install: - The SDK needs to be installed without user interaction and without admin rights.
dotnet-install: - The SDK installation doesn't need to persist across multiple CI runs.
dotnet-install: To set up a development environment or to run apps, use installers rather than this script. Visit https://dotnet.microsoft.com/download to get the installer.

dotnet-install: Downloading primary link https://dotnetcli.azureedge.net/dotnet/Runtime/3.1.1/dotnet-runtime-3.1.1-linux-musl-x64.tar.gz
dotnet-install: Extracting zip from https://dotnetcli.azureedge.net/dotnet/Runtime/3.1.1/dotnet-runtime-3.1.1-linux-musl-x64.tar.gz
dotnet-install: Adding to current process PATH: `/home/pj/Development/gitlab.alpinelinux.org/alpine/aports/testing/dotnet5/src/source-build-5.0.207-SDK/.dotnet`. Note: This change will be visible only when sourcing script.
dotnet-install: Note that the script does not resolve dependencies during installation.
dotnet-install: To check the list of dependencies, go to https://docs.microsoft.com/dotnet/core/install, select your operating system and check the "Dependencies" section.
dotnet-install: Installation finished successfully.
+ '[' false == true ']'
++ date +%m%d%H%M%S
+ /home/pj/Development/gitlab.alpinelinux.org/alpine/aports/testing/dotnet5/src/source-build-5.0.207-SDK/eng/common/build.sh --restore --build -c Release --warnaserror false /bl:/home/pj/Development/gitlab.alpinelinux.org/alpine/aports/testing/dotnet5/src/source-build-5.0.207-SDK/artifacts/log/Debug/Build_1018043431.binlog /flp:v=diag /p:UseSystemLibraries=true /p:UseSystemLibunwind=true /p:RuntimeOS=linux-musl /p:OutputRid=linux-musl-x64 /p:MicrosoftNetCoreIlasmPackageRuntimeId=linux-musl-x64 /p:SkipPortableRuntimeBuild=true /p:EnableSourceLink=false
dotnet-install: Note that the intended use of this script is for Continuous Integration (CI) scenarios, where:
dotnet-install: - The SDK needs to be installed without user interaction and without admin rights.
dotnet-install: - The SDK installation doesn't need to persist across multiple CI runs.
dotnet-install: To set up a development environment or to run apps, use installers rather than this script. Visit https://dotnet.microsoft.com/download to get the installer.

dotnet-install: Downloading primary link https://dotnetcli.azureedge.net/dotnet/Sdk/5.0.206/dotnet-sdk-5.0.206-linux-musl-x64.tar.gz
dotnet-install: Extracting zip from https://dotnetcli.azureedge.net/dotnet/Sdk/5.0.206/dotnet-sdk-5.0.206-linux-musl-x64.tar.gz
dotnet-install: Adding to current process PATH: `/home/pj/Development/gitlab.alpinelinux.org/alpine/aports/testing/dotnet5/src/source-build-5.0.207-SDK/.dotnet`. Note: This change will be visible only when sourcing script.
dotnet-install: Note that the script does not resolve dependencies during installation.
dotnet-install: To check the list of dependencies, go to https://docs.microsoft.com/dotnet/core/install, select your operating system and check the "Dependencies" section.
dotnet-install: Installation finished successfully.

Welcome to .NET 5.0!
---------------------
SDK Version: 5.0.206

----------------
Installed an ASP.NET Core HTTPS development certificate.
To trust the certificate run 'dotnet dev-certs https --trust' (Windows and macOS only).
Learn about HTTPS: https://aka.ms/dotnet-https
----------------
Write your first app: https://aka.ms/dotnet-hello-world
Find out what's new: https://aka.ms/dotnet-whats-new
Explore documentation: https://aka.ms/dotnet-docs
Report issues and find source on GitHub: https://github.com/dotnet/core
Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli
--------------------------------------------------------------------------------------
/home/pj/Development/gitlab.alpinelinux.org/alpine/aports/testing/dotnet5/src/source-build-5.0.207-SDK/.dotnet/sdk/5.0.206/MSBuild.dll /nologo -maxcpucount /m -verbosity:m /v:minimal /bl:/home/pj/Development/gitlab.alpinelinux.org/alpine/aports/testing/dotnet5/src/source-build-5.0.207-SDK/artifacts/log/Debug/Build_1018043431.binlog /clp:Summary /flp:v=diag /nr:true /p:TreatWarningsAsErrors=false /p:ContinuousIntegrationBuild=false /p:Configuration=Release /p:RepoRoot=/home/pj/Development/gitlab.alpinelinux.org/alpine/aports/testing/dotnet5/src/source-build-5.0.207-SDK /p:Restore=true /p:Build=true /p:Rebuild=false /p:Test=false /p:Pack=false /p:IntegrationTest=false /p:PerformanceTest=false /p:Sign=false /p:Publish=false /p:UseSystemLibraries=true /p:UseSystemLibunwind=true /p:RuntimeOS=linux-musl /p:OutputRid=linux-musl-x64 /p:MicrosoftNetCoreIlasmPackageRuntimeId=linux-musl-x64 /p:SkipPortableRuntimeBuild=true /p:EnableSourceLink=false /home/pj/Development/gitlab.alpinelinux.org/alpine/aports/testing/dotnet5/src/source-build-5.0.207-SDK/packages/restored/microsoft.dotnet.arcade.sdk/5.0.0-beta.20426.4/tools/Build.proj
/home/pj/Development/gitlab.alpinelinux.org/alpine/aports/testing/dotnet5/src/source-build-5.0.207-SDK/packages/restored/microsoft.dotnet.arcade.sdk/5.0.0-beta.20426.4/tools/ProjectLayout.props(8,3): warning MSB4011: "/home/pj/Development/gitlab.alpinelinux.org/alpine/aports/testing/dotnet5/src/source-build-5.0.207-SDK/packages/restored/microsoft.dotnet.arcade.sdk/5.0.0-beta.20426.4/tools/RepoLayout.props" cannot be imported again. It was already imported at "/home/pj/Development/gitlab.alpinelinux.org/alpine/aports/testing/dotnet5/src/source-build-5.0.207-SDK/packages/restored/microsoft.dotnet.arcade.sdk/5.0.0-beta.20426.4/tools/Build.proj (49,3)". This is most likely a build authoring error. This subsequent import will be ignored. 
  Determining projects to restore...
  Restored /home/pj/Development/gitlab.alpinelinux.org/alpine/aports/testing/dotnet5/src/source-build-5.0.207-SDK/packages/restored/microsoft.dotnet.arcade.sdk/5.0.0-beta.20426.4/tools/Tools.proj (in 4.9 sec).
  Determining projects to restore...
  Restored /home/pj/Development/gitlab.alpinelinux.org/alpine/aports/testing/dotnet5/src/source-build-5.0.207-SDK/build.proj (in 3.88 sec).
  Determining projects to restore...
  Restored /home/pj/Development/gitlab.alpinelinux.org/alpine/aports/testing/dotnet5/src/source-build-5.0.207-SDK/tools-local/tasks/Microsoft.DotNet.SourceBuild.Tasks.XPlat/Microsoft.DotNet.SourceBuild.Tasks.XPlat.csproj (in 8.94 sec).
  Determining projects to restore...
  Restored /home/pj/Development/gitlab.alpinelinux.org/alpine/aports/testing/dotnet5/src/source-build-5.0.207-SDK/tools-local/tasks/SourceBuild.MSBuildSdkResolver/SourceBuild.MSBuildSdkResolver.csproj (in 100 ms).
/home/pj/Development/gitlab.alpinelinux.org/alpine/aports/testing/dotnet5/src/source-build-5.0.207-SDK/tools-local/tasks/Microsoft.DotNet.SourceBuild.Tasks.XPlat/DownloadFileSB.cs(397,35): warning CS0108: 'DownloadFileSB.CustomHttpRequestException.StatusCode' hides inherited member 'HttpRequestException.StatusCode'. Use the new keyword if hiding was intended. [/home/pj/Development/gitlab.alpinelinux.org/alpine/aports/testing/dotnet5/src/source-build-5.0.207-SDK/tools-local/tasks/Microsoft.DotNet.SourceBuild.Tasks.XPlat/Microsoft.DotNet.SourceBuild.Tasks.XPlat.csproj]
  Microsoft.DotNet.SourceBuild.Tasks.XPlat -> /home/pj/Development/gitlab.alpinelinux.org/alpine/aports/testing/dotnet5/src/source-build-5.0.207-SDK/tools-local/tasks/Microsoft.DotNet.SourceBuild.Tasks.XPlat/bin/Release/Microsoft.DotNet.SourceBuild.Tasks.XPlat.dll
  SourceBuild.MSBuildSdkResolver -> /home/pj/Development/gitlab.alpinelinux.org/alpine/aports/testing/dotnet5/src/source-build-5.0.207-SDK/artifacts/x64/Release/SourceBuild.MSBuildSdkResolver.dll
  Adding resolver to SDK: SourceBuild.MSBuildSdkResolver -> /home/pj/Development/gitlab.alpinelinux.org/alpine/aports/testing/dotnet5/src/source-build-5.0.207-SDK/.dotnet/sdk/5.0.206/SdkResolvers/SourceBuild.MSBuildSdkResolver/SourceBuild.MSBuildSdkResolver.dll
  [04:35:05.06] Installing Darc.
  Tool path '/home/pj/Development/gitlab.alpinelinux.org/alpine/aports/testing/dotnet5/src/source-build-5.0.207-SDK/.dotnet/tools/' does not exist.
  Installing Darc CLI version 1.1.0-beta.19568.2...
  You may need to restart your command shell if this is the first dotnet tool you have installed.
  Determining projects to restore... Restored /tmp/ppw0vv02.dzz/restore.csproj (in 4.92 sec). You can invoke the tool using the following command: darc
   Tool 'microsoft.dotnet.darc' (version '1.1.0-beta.19568.2') was successfully installed.
  [04:35:11.68] Done installing Darc.
  [04:35:11.69] Getting source code for repos in Version.Details.xml.
  [04:35:11.69] Running Darc command: '/home/pj/Development/gitlab.alpinelinux.org/alpine/aports/testing/dotnet5/src/source-build-5.0.207-SDK/.dotnet/dotnet /home/pj/Development/gitlab.alpinelinux.org/alpine/aports/testing/dotnet5/src/source-build-5.0.207-SDK/.dotnet/tools/.store/microsoft.dotnet.darc/1.1.0-beta.19568.2/microsoft.dotnet.darc/1.1.0-beta.19568.2/tools/netcoreapp3.0/any/Microsoft.DotNet.Darc.dll clone  --git-dir-folder /home/pj/Development/gitlab.alpinelinux.org/alpine/aports/testing/dotnet5/src/source-build-5.0.207-SDK/.git/modules/src/ --include-toolset --ignore-repos ";https://dev.azure.com/dnceng/internal/_git/dotnet-optimization;https://dev.azure.com/devdiv/DevDiv/_git/DotNet-Trusted;https://devdiv.visualstudio.com/DevDiv/_git/DotNet-Trusted;https://dnceng@dev.azure.com/dnceng/internal/_git/dotnet-optimization;https://dev.azure.com/dnceng/internal/_git/dotnet-core-setup;https://github.com/dotnet/source-build-reference-packages" --debug --azdev-pat bogus --github-pat bogus --depth 0' from working dir /home/pj/Development/gitlab.alpinelinux.org/alpine/aports/testing/dotnet5/src/source-build-5.0.207-SDK/
  [40m[32minfo[39m[22m[49m: Microsoft.DotNet.Darc.Operations.Operation[0]
        Getting a collection of dependencies from 'eng/Version.Details.xml' in repo '/home/pj/Development/gitlab.alpinelinux.org/alpine/aports'...
  [40m[32minfo[39m[22m[49m: Microsoft.DotNet.Darc.Operations.Operation[0]
        Reading 'eng/Version.Details.xml' in repo '/home/pj/Development/gitlab.alpinelinux.org/alpine/aports' and branch ''...
  [41m[30mfail[39m[22m[49m: Microsoft.DotNet.Darc.Operations.Operation[0]
        Something failed while cloning.
  System.IO.DirectoryNotFoundException: Could not find a part of the path '/home/pj/Development/gitlab.alpinelinux.org/alpine/aports/eng/Version.Details.xml'.
     at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
     at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
     at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)
     at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
     at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
     at System.IO.StreamReader..ctor(String path)
     at Microsoft.DotNet.DarcLib.LocalGitClient.GetFileContentsAsync(String relativeFilePath, String repoUri, String branch) in /_/src/Microsoft.DotNet.Darc/src/DarcLib/LocalGitClient.cs:line 60
     at Microsoft.DotNet.DarcLib.GitFileManager.ReadXmlFileAsync(String filePath, String repoUri, String branch) in /_/src/Microsoft.DotNet.Darc/src/DarcLib/Helpers/GitFileManager.cs:line 569
     at Microsoft.DotNet.DarcLib.GitFileManager.ReadVersionDetailsXmlAsync(String repoUri, String branch) in /_/src/Microsoft.DotNet.Darc/src/DarcLib/Helpers/GitFileManager.cs:line 62
     at Microsoft.DotNet.DarcLib.GitFileManager.ParseVersionDetailsXmlAsync(String repoUri, String branch, Boolean includePinned) in /_/src/Microsoft.DotNet.Darc/src/DarcLib/Helpers/GitFileManager.cs:line 118
     at Microsoft.DotNet.DarcLib.Local.GetDependenciesAsync(String name, Boolean includePinned) in /_/src/Microsoft.DotNet.Darc/src/DarcLib/Actions/Local.cs:line 113
     at Microsoft.DotNet.Darc.Operations.CloneOperation.ExecuteAsync() in /_/src/Microsoft.DotNet.Darc/src/Darc/Operations/CloneOperation.cs:line 61
/home/pj/Development/gitlab.alpinelinux.org/alpine/aports/testing/dotnet5/src/source-build-5.0.207-SDK/tools-local/init-build.proj(149,5): error MSB3073: The command "/home/pj/Development/gitlab.alpinelinux.org/alpine/aports/testing/dotnet5/src/source-build-5.0.207-SDK/.dotnet/dotnet /home/pj/Development/gitlab.alpinelinux.org/alpine/aports/testing/dotnet5/src/source-build-5.0.207-SDK/.dotnet/tools/.store/microsoft.dotnet.darc/1.1.0-beta.19568.2/microsoft.dotnet.darc/1.1.0-beta.19568.2/tools/netcoreapp3.0/any/Microsoft.DotNet.Darc.dll clone  --git-dir-folder /home/pj/Development/gitlab.alpinelinux.org/alpine/aports/testing/dotnet5/src/source-build-5.0.207-SDK/.git/modules/src/ --include-toolset --ignore-repos ";https://dev.azure.com/dnceng/internal/_git/dotnet-optimization;https://dev.azure.com/devdiv/DevDiv/_git/DotNet-Trusted;https://devdiv.visualstudio.com/DevDiv/_git/DotNet-Trusted;https://dnceng@dev.azure.com/dnceng/internal/_git/dotnet-optimization;https://dev.azure.com/dnceng/internal/_git/dotnet-core-setup;https://github.com/dotnet/source-build-reference-packages" --debug --azdev-pat bogus --github-pat bogus --depth 0 --repos-folder /home/pj/Development/gitlab.alpinelinux.org/alpine/aports/testing/dotnet5/src/source-build-5.0.207-SDK/artifacts/src/" exited with code 42.

Build FAILED.

/home/pj/Development/gitlab.alpinelinux.org/alpine/aports/testing/dotnet5/src/source-build-5.0.207-SDK/packages/restored/microsoft.dotnet.arcade.sdk/5.0.0-beta.20426.4/tools/ProjectLayout.props(8,3): warning MSB4011: "/home/pj/Development/gitlab.alpinelinux.org/alpine/aports/testing/dotnet5/src/source-build-5.0.207-SDK/packages/restored/microsoft.dotnet.arcade.sdk/5.0.0-beta.20426.4/tools/RepoLayout.props" cannot be imported again. It was already imported at "/home/pj/Development/gitlab.alpinelinux.org/alpine/aports/testing/dotnet5/src/source-build-5.0.207-SDK/packages/restored/microsoft.dotnet.arcade.sdk/5.0.0-beta.20426.4/tools/Build.proj (49,3)". This is most likely a build authoring error. This subsequent import will be ignored. 
/home/pj/Development/gitlab.alpinelinux.org/alpine/aports/testing/dotnet5/src/source-build-5.0.207-SDK/tools-local/tasks/Microsoft.DotNet.SourceBuild.Tasks.XPlat/DownloadFileSB.cs(397,35): warning CS0108: 'DownloadFileSB.CustomHttpRequestException.StatusCode' hides inherited member 'HttpRequestException.StatusCode'. Use the new keyword if hiding was intended. [/home/pj/Development/gitlab.alpinelinux.org/alpine/aports/testing/dotnet5/src/source-build-5.0.207-SDK/tools-local/tasks/Microsoft.DotNet.SourceBuild.Tasks.XPlat/Microsoft.DotNet.SourceBuild.Tasks.XPlat.csproj]
/home/pj/Development/gitlab.alpinelinux.org/alpine/aports/testing/dotnet5/src/source-build-5.0.207-SDK/tools-local/init-build.proj(149,5): error MSB3073: The command "/home/pj/Development/gitlab.alpinelinux.org/alpine/aports/testing/dotnet5/src/source-build-5.0.207-SDK/.dotnet/dotnet /home/pj/Development/gitlab.alpinelinux.org/alpine/aports/testing/dotnet5/src/source-build-5.0.207-SDK/.dotnet/tools/.store/microsoft.dotnet.darc/1.1.0-beta.19568.2/microsoft.dotnet.darc/1.1.0-beta.19568.2/tools/netcoreapp3.0/any/Microsoft.DotNet.Darc.dll clone  --git-dir-folder /home/pj/Development/gitlab.alpinelinux.org/alpine/aports/testing/dotnet5/src/source-build-5.0.207-SDK/.git/modules/src/ --include-toolset --ignore-repos ";https://dev.azure.com/dnceng/internal/_git/dotnet-optimization;https://dev.azure.com/devdiv/DevDiv/_git/DotNet-Trusted;https://devdiv.visualstudio.com/DevDiv/_git/DotNet-Trusted;https://dnceng@dev.azure.com/dnceng/internal/_git/dotnet-optimization;https://dev.azure.com/dnceng/internal/_git/dotnet-core-setup;https://github.com/dotnet/source-build-reference-packages" --debug --azdev-pat bogus --github-pat bogus --depth 0 --repos-folder /home/pj/Development/gitlab.alpinelinux.org/alpine/aports/testing/dotnet5/src/source-build-5.0.207-SDK/artifacts/src/" exited with code 42.
    2 Warning(s)
    1 Error(s)

Time Elapsed 00:00:28.45
Build failed (exit code '1').
>>> ERROR: dotnet5-SDK: build failed
>>> ERROR: dotnet5-SDK: rootbld failed
>>> dotnet5-SDK: Cleaning up build chroot
```

</details>

**Comment by panekj** [comment]
right, I failed to realise that it requires git submodules
