### ISSUE TITLE
Potential threading issues in SmokeTests.ExecuteHelper

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/source-build#2823]
The following test failure occurred in CI.

```
Failed Microsoft.DotNet.SourceBuild.SmokeTests.DotNetWatchTests.WatchTests [37 s]

EXEC : error Message: [/tarball/build.proj]

System.ArgumentOutOfRangeException : Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'chunkLength')

Stack Trace:

at System.Text.StringBuilder.ToString()

at Microsoft.DotNet.SourceBuild.SmokeTests.ExecuteHelper.ExecuteProcess(String fileName, String args, ITestOutputHelper outputHelper, Boolean logOutput, Action`1 configure, Int32 millisecondTimeout) in /tarball/test/Microsoft.DotNet.SourceBuild.SmokeTests/ExecuteHelper.cs:line 64

at Microsoft.DotNet.SourceBuild.SmokeTests.DotNetHelper.ExecuteCmd(String args, String workingDirectory, Action`1 additionalProcessConfigCallback, Int32 expectedExitCode, Int32 millisecondTimeout) in /tarball/test/Microsoft.DotNet.SourceBuild.SmokeTests/DotNetHelper.cs:line 93

at Microsoft.DotNet.SourceBuild.SmokeTests.DotNetWatchTests.WatchTests() in /tarball/test/Microsoft.DotNet.SourceBuild.SmokeTests/DotNetWatchTests.cs:line 23
```

StringBuilder is not thread safe and appears to be accessed across threads in ExecuteHelper - https://github.com/dotnet/installer/blob/release/6.0.1xx/src/SourceBuild/tarball/content/test/Microsoft.DotNet.SourceBuild.SmokeTests/ExecuteHelper.cs#L47

**Comment by lbussell** [comment]
This has happened again here: https://dev.azure.com/dnceng/internal/_build/results?buildId=2046480&view=ms.vss-test-web.build-test-results-tab&runId=51026226&resultId=100029&paneView=debug (internal link)
