### ISSUE TITLE
Fedora CI timeouts and other issues

### ISSUE THREAD

**Issue by crummel** [dotnet/source-build#287]
Fedora build has been timing out and other builds are taking longer.  Some builds being aborted for non-specific reasons: https://ci.dot.net/job/dotnet_source-build/job/dev_release_2.0/job/Fedora24_Debug/9/.
```
17:24:57 java.io.EOFException
17:24:57 	at java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2675)
17:24:57 	at java.io.ObjectInputStream$BlockDataInputStream.readShort(ObjectInputStream.java:3150)
17:24:57 	at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:859)
17:24:57 	at java.io.ObjectInputStream.<init>(ObjectInputStream.java:355)
17:24:57 	at hudson.remoting.ObjectInputStreamEx.<init>(ObjectInputStreamEx.java:48)
17:24:57 	at hudson.remoting.AbstractSynchronousByteArrayCommandTransport.read(AbstractSynchronousByteArrayCommandTransport.java:35)
17:24:57 	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:59)
17:24:57 Caused: java.io.IOException: Unexpected termination of the channel
17:24:57 	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:73)
17:24:57 Caused: java.io.IOException: Backing channel 'fedora24-20171005-964f80' is disconnected.
17:24:57 	at hudson.remoting.RemoteInvocationHandler.channelOrFail(RemoteInvocationHandler.java:192)
17:24:57 	at hudson.remoting.RemoteInvocationHandler.invoke(RemoteInvocationHandler.java:257)
17:24:57 	at com.sun.proxy.$Proxy197.isAlive(Unknown Source)
17:24:57 	at hudson.Launcher$RemoteLauncher$ProcImpl.isAlive(Launcher.java:1138)
17:24:57 	at hudson.Launcher$RemoteLauncher$ProcImpl.join(Launcher.java:1130)
17:24:57 	at hudson.tasks.CommandInterpreter.join(CommandInterpreter.java:155)
17:24:57 	at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:109)
17:24:57 	at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:66)
17:24:57 	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
17:24:57 	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:736)
17:24:57 	at hudson.model.Build$BuildExecution.build(Build.java:206)
17:24:57 	at hudson.model.Build$BuildExecution.doRun(Build.java:163)
17:24:57 	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:496)
17:24:57 	at hudson.model.Run.execute(Run.java:1737)
17:24:57 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
17:24:57 	at hudson.model.ResourceController.execute(ResourceController.java:97)
17:24:57 	at hudson.model.Executor.run(Executor.java:421)
```

CoreRT is seeing something similar, so may be a Jenkins issue.

**Comment by crummel** [comment]
Wes is seeing similar issues, might be related to VS version.  https://github.com/dotnet/coreclr/pull/14892

**Comment by weshaggard** [comment]
VS version is only interesting on Windows builds.

**Comment by crummel** [comment]
Fixed in https://github.com/dotnet/core-eng/issues/2138.
