### ISSUE TITLE
DotNetWatchTests are failing

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/source-build#2961]
Tests appear to have started failing with https://github.com/dotnet/installer/commit/f763288a5783ec32dcbb3351a0bf58813fd32c1b

```
System.InvalidOperationException : Failed to execute /tarball/test/Microsoft.DotNet.SourceBuild.SmokeTests/bin/Release/net7.0/.dotnet/dotnet watch run
Exit code: 137
dotnet watch \ud83d\udd25 Hot reload enabled. For a list of supported edits, see https://aka.ms/dotnet/hot-reload.
\ud83d\udca1 Press "Ctrl + R" to restart.
dotnet watch \ud83d\udd27 Building...
Determining projects to restore...
All projects are up-to-date for restore.
/tarball/test/Microsoft.DotNet.SourceBuild.SmokeTests/bin/Release/net7.0/.dotnet/sdk/7.0.100-rc.1.22405.1/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.RuntimeIdentifierInference.targets(219,5): message NETSDK1057: You are using a preview version of .NET. See: https://aka.ms/dotnet-support-policy [/tarball/test/Microsoft.DotNet.SourceBuild.SmokeTests/bin/Release/net7.0/projects-202208050954586202/DotNetWatchTests/DotNetWatchTests.csproj]
DotNetWatchTests -> /tarball/test/Microsoft.DotNet.SourceBuild.SmokeTests/bin/Release/net7.0/projects-202208050954586202/DotNetWatchTests/bin/Debug/net7.0/DotNetWatchTests.dll
dotnet watch \ud83d\ude80 Started
Hello, World!
dotnet watch ⌚ Exited
dotnet watch ⏳ Waiting for a file to change before restarting dotnet...
dotnet watch \ud83d\udd27 Building...
/tarball/test/Microsoft.DotNet.SourceBuild.SmokeTests/bin/Release/net7.0/.dotnet/sdk/7.0.100-rc.1.22405.1/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.RuntimeIdentifierInference.targets(219,5): message NETSDK1057: You are using a preview version of .NET. See: https://aka.ms/dotnet-support-policy [/tarball/test/Microsoft.DotNet.SourceBuild.SmokeTests/bin/Release/net7.0/projects-202208050954586202/DotNetWatchTests/DotNetWatchTests.csproj]
DotNetWatchTests -> /tarball/test/Microsoft.DotNet.SourceBuild.SmokeTests/bin/Release/net7.0/projects-202208050954586202/DotNetWatchTests/bin/Debug/net7.0/DotNetWatchTests.dll
dotnet watch \ud83d\ude80 Started
Hello from dotnet watch!
dotnet watch ⌚ Exited
dotnet watch ⏳ Waiting for a file to change before restarting dotnet...


Stack trace
   at Microsoft.DotNet.SourceBuild.SmokeTests.ExecuteHelper.ValidateExitCode(ValueTuple`3 result, Int32 expectedExitCode) in /tarball/test/Microsoft.DotNet.SourceBuild.SmokeTests/ExecuteHelper.cs:line 110
   at Microsoft.DotNet.SourceBuild.SmokeTests.DotNetHelper.ExecuteCmd(String args, String workingDirectory, Action`1 additionalProcessConfigCallback, Int32 expectedExitCode, Int32 millisecondTimeout) in /tarball/test/Microsoft.DotNet.SourceBuild.SmokeTests/DotNetHelper.cs:line 90
   at Microsoft.DotNet.SourceBuild.SmokeTests.DotNetWatchTests.WatchTests() in /tarball/test/Microsoft.DotNet.SourceBuild.SmokeTests/DotNetWatchTests.cs:line 23
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

**Comment by lbussell** [comment]
Fixed by https://github.com/dotnet/installer/pull/14367 and https://github.com/dotnet/installer/pull/14738
