### ISSUE TITLE
dotnet-watch failure in release/7.0.2xx

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/source-build#3123]
The DotNetWatchTests tests started failing with 

```
Error message
Assert.True() Failure
Expected: True
Actual:   False


Stack trace
   at Microsoft.DotNet.SourceBuild.SmokeTests.DotNetWatchTests.WatchTests() in /tarball/test/Microsoft.DotNet.SourceBuild.SmokeTests/DotNetWatchTests.cs:line 29
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

Testing locally I see the following when running dotnet watch run on a new console app.
```
dotnet watch ❌ System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.DotNet.Cli.EnvironmentVariableNames.TryParseArchitecture(String runtimeIdentifier, Architecture& architecture)
   at Microsoft.DotNet.Cli.EnvironmentVariableNames.TryGetDotNetRootVariableNameImpl(String runtimeIdentifier, String defaultAppHostRuntimeIdentifier, Version targetFrameworkVersion, Architecture currentArchitecture, Boolean is64bit)
   at Microsoft.DotNet.Cli.EnvironmentVariableNames.TryGetDotNetRootVariableName(String runtimeIdentifier, String defaultAppHostRuntimeIdentifier, Version targetFrameworkVersion)
   at Microsoft.DotNet.Watcher.HotReloadDotNetWatcher.ConfigureExecutable(DotNetWatchContext context, ProcessSpec processSpec)
   at Microsoft.DotNet.Watcher.HotReloadDotNetWatcher.WatchAsync(DotNetWatchContext context, CancellationToken cancellationToken)
   at Microsoft.DotNet.Watcher.Program.MainInternalAsync(CommandLineOptions options, CancellationToken cancellationToken)
   at Microsoft.DotNet.Watcher.Program.MainInternalAsync(CommandLineOptions options, CancellationToken cancellationToken)
   at Microsoft.DotNet.Watcher.Program.HandleWatch(CommandLineOptions options)
dotnet watch ❌ An unexpected error occurred
```

As part of fixing this, it would be if the exception would be surfaced by the DotNetWatchTests (Assuming it is failing for the same reason.

**Comment by MichaelSimons** [comment]
This issue reproduces in the MSFT build and is tracked with https://github.com/dotnet/sdk/issues/29085.  Once fixed, the DotNetWatchTests should be re-enabled.  Also investigate if the underlying exception can be captured in the test output.
