### ISSUE TITLE
Cannot generate SBRP for a multi-assembly package

### ISSUE THREAD

**Issue by oleksandr-didyk** [dotnet/source-build#3340]
Steps to reproduce - [e1b6b6](https://github.com/dotnet/source-build-reference-packages/tree/e1b6b6ae61a710e96f5278188379bb496318fae4):
```bash
./generate.sh --pkg microsoft.net.stringtools,17.3.2
```

The exception:
```
 The "GenerateProject" task failed unexpectedly.
 System.InvalidOperationException: Sequence contains more than one element
    at System.Linq.ThrowHelper.ThrowMoreThanOneElementException()
    at System.Linq.Enumerable.TryGetSingle[TSource](IEnumerable`1 source, Boolean& found)
    at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source)
    at Microsoft.DotNet.SourceBuild.Tasks.GenerateProject.Execute() in ./GenerateProject.cs:line 132
    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask)
```

The failing [line](https://github.com/dotnet/source-build-reference-packages/blob/e1b6b6ae61a710e96f5278188379bb496318fae4/src/packageSourceGenerator/PackageSourceGeneratorTask/GenerateProject.cs#L132):
```csharp
            // Calculate the assembly name from the compile items assembly name metadata. If more than one
            // distinct name is found (i.e. multi assembly package), use the PackageId instead.
            projectContent = projectContent.Replace("$$AssemblyName$$",
                CompileItems.Select(compileItem => compileItem.GetMetadata(SharedMetadata.AssemblyNameMetadataName))
                    .Distinct()
                    .SingleOrDefault() ?? PackageId!);
```

CC: @ViktorHofer - the comment refers to the situation of the collection containing multiple entries, but `SingleOrDefault` will throw if the collection [contains more than 1 element](https://learn.microsoft.com/en-us/dotnet/api/system.linq.enumerable.singleordefault?view=net-8.0#system-linq-enumerable-singleordefault-1(system-collections-generic-ienumerable((-0)))) (hence the exception above). Wanted to verify that this is indeed the issue, hence the ping

**Comment by ViktorHofer** [comment]
My fault... Will submit a fix

**Comment by oleksandr-didyk** [comment]
Thank you for the quick fix
