### ISSUE TITLE
No strong name key mapping for Newtonsoft.Json in SBRP generator

### ISSUE THREAD

**Issue by mthalman** [dotnet/source-build#3364]
When attempting to generate an SBRP package for Newtonsoft.Json, or a package that has a dependency on it, it results in the following exception:

```
The "GetPackageItems" task failed unexpectedly.
System.ArgumentException: Found strong name key that doesn't map: Key=30ad4fe6b2a6aeed, Assembly=Newtonsoft.Json
   at Microsoft.DotNet.SourceBuild.Tasks.GetPackageItems.TryGetStrongNameData(AssemblyName assemblyName, StrongNameData& strongNameData) in C:\repos\source - build - reference - packages\src\packageSourceGenerator\PackageSourceGeneratorTask\GetPackageItems.cs:line 241
   at Microsoft.DotNet.SourceBuild.Tasks.GetPackageItems.SetCompileItems(PackageArchiveReader packageArchiveReader, TargetFrameworkRegexFilter targetFrameworkRegexFilter) in C:\repos\source - build - reference - packages\src\packageSourceGenerator\PackageSourceGeneratorTask\GetPackageItems.cs:line 153
   at Microsoft.DotNet.SourceBuild.Tasks.GetPackageItems.Execute() in C:\repos\source - build - reference - packages\src\packageSourceGenerator\PackageSourceGeneratorTask\GetPackageItems.cs:line 84
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask)
```

Repro:

```
.\generate.cmd -p NuGet.Packaging,6.5.0
```
or
```
.\generate.cmd -p Newtonsoft.Json,13.0.1
```

**Comment by ViktorHofer** [comment]
You would need to add the strong name key here: https://github.com/dotnet/source-build-reference-packages/blob/02ee87c8a232a9786b56cd2102cf318559e72210/src/packageSourceGenerator/PackageSourceGeneratorTask/GetPackageItems.cs#L23-L30

That said, should we add Newtonsoft.Json to SBRP? That sounds a bit concerning. How did we handle that dependency in the past? cc @MichaelSimons

**Comment by mthalman** [comment]
Good point. It should be included from source-build-externals. In that case, should the generator detect that and exclude that from the output?

**Comment by ViktorHofer** [comment]
> In that case, should the generator detect that and exclude that from the output?

Probably yes. Do we have other MSFT packages that depend on non MSFT nuget packages? If so, then we should probably define all of them in the package exclusion list: https://github.com/dotnet/source-build-reference-packages/blob/02ee87c8a232a9786b56cd2102cf318559e72210/src/packageSourceGenerator/PackageSourceGenerator.proj#L334

**Comment by MichaelSimons** [comment]
I tend to think Newtonsoft.Json is a bit of a special case here.  I like the idea of adding the exclusion for this one.  If we encounter others, we can follow this same pattern.
