### ISSUE TITLE
[smoke-tests] SourceBuiltSdkContainsNativeDebugSymbols test is failing in local build of latest VMR [release/8.0.1xx]

### ISSUE THREAD

**Issue by NikolaMilosavljevic** [dotnet/source-build#3596]
Latest VMR sha (4865a1568a19f5ac4faf150160ff9ed7218adc55) in `release/8.0.1xx` branch - local build on Fedora 36 is failing the smoke-tests, with `SourceBuiltSdkContainsNativeDebugSymbols` test failing.

```
 [xUnit.net 00:00:04.67]     Microsoft.DotNet.SourceBuild.SmokeTests.DebugTests.SourceBuiltSdkContainsNativeDebugSymbols [FAIL]
  [xUnit.net 00:00:04.68]       System.ComponentModel.Win32Exception : An error occurred trying to start process 'file' with working directory '/src/git/dotnet3/test/Microsoft.DotNet.SourceBuild.SmokeTests/bin/Release/net8.0'. No such file or directory
  [xUnit.net 00:00:04.68]       Stack Trace:
  [xUnit.net 00:00:04.68]            at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo startInfo, String resolvedFilename, String[] argv, String[] envp, String cwd, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
  [xUnit.net 00:00:04.68]            at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
  [xUnit.net 00:00:04.68]         /src/git/dotnet3/test/Microsoft.DotNet.SourceBuild.SmokeTests/ExecuteHelper.cs(68,0): at Microsoft.DotNet.SourceBuild.SmokeTests.ExecuteHelper.ExecuteProcess(String fileName, String args, ITestOutputHelper outputHelper, Boolean logOutput, Action`1 configureCallback, Int32 millisecondTimeout)
  [xUnit.net 00:00:04.68]         /src/git/dotnet3/test/Microsoft.DotNet.SourceBuild.SmokeTests/ExecuteHelper.cs(111,0): at Microsoft.DotNet.SourceBuild.SmokeTests.ExecuteHelper.ExecuteProcessValidateExitCode(String fileName, String args, ITestOutputHelper outputHelper)
  [xUnit.net 00:00:04.68]         /src/git/dotnet3/test/Microsoft.DotNet.SourceBuild.SmokeTests/DebugTests.cs(69,0): at Microsoft.DotNet.SourceBuild.SmokeTests.DebugTests.IsElfFile(String fileName)
  [xUnit.net 00:00:04.68]         /src/git/dotnet3/test/Microsoft.DotNet.SourceBuild.SmokeTests/DebugTests.cs(33,0): at Microsoft.DotNet.SourceBuild.SmokeTests.DebugTests.SourceBuiltSdkContainsNativeDebugSymbols()
  [xUnit.net 00:00:04.68]            at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
  [xUnit.net 00:00:04.68]            at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
```

**Comment by MichaelSimons** [comment]
If you are using our Docker images, you may need to pull latest as there were a couple new packages added for this new test.  See https://github.com/dotnet/dotnet-buildtools-prereqs-docker/pull/891/

**Comment by NikolaMilosavljevic** [comment]
Closing - this did not repro with latest Fedora 38 image: `mcr.microsoft.com/dotnet-buildtools/prereqs:fedora-38`
