### ISSUE TITLE
[VMR] Issue with cross built tarball for Ppc64le

### ISSUE THREAD

**Issue by Swapnali911** [dotnet/source-build#3797]
Relates to : #3671

VM details : RHEL9.3 ppc64le
 
Deployment steps:
- Untar sdk tarball generated by cross building dotnet/dotnet repo
\# tar -xf dotnet-sdk-8.0.100-linux-x64.tar.gz -C .dotnet
- Set DOTNET_ROOT
\# export DOTNET_ROOT=$(pwd)/.dotnet
- Add .NET path to PATH
\# export PATH=$DOTNET_ROOT:$PATH
- Check installed .NET
\# dotnet --info
- Create and run sample HelloWorld program using deployed .NET tarball
\# dotnet new-console
\# dotnet run

Actual Result:
Getting exception when running dotnet run 
```
# dotnet run
Unhandled exception: System.ComponentModel.Win32Exception (8): An error occurred trying to start process '/root/check_cross/temp_hello/hello' with working directory '/root/check_cross/temp_hello'. Exec format error
   at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo startInfo, String resolvedFilename, String[] argv, String[] envp, tCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, B
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Microsoft.DotNet.Cli.Utils.Command.Execute(Action`1 processStarted)
   at Microsoft.DotNet.Cli.Utils.Command.Execute()
   at Microsoft.DotNet.Tools.Run.RunCommand.Execute()
   at Microsoft.DotNet.Tools.Run.RunCommand.Run(ParseResult parseResult)
   at System.CommandLine.Invocation.AnonymousCliAction.Invoke(ParseResult parseResult)
   at System.CommandLine.Invocation.InvocationPipeline.Invoke(ParseResult parseResult)
   at System.CommandLine.ParseResult.Invoke()
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, TimeSpan startupTime, ITelemetry telemetryClient)
```

Expected: HelloWorld program should run

cc : @janani66 @Sapana-Khemkar

**Comment by Swapnali911** [comment]
@directhex Below are details for the tarball

**Steps to build tarball:**
Clone dotnet/dotnet repo
Checkout to GA tag
Apply [GA_36_new.patch](https://github.com/dotnet/source-build/files/13683671/GA_36_new.patch) for ppc64le arch 
prep.sh
export CROSSCOMPILE=1
export ROOTFS_DIR=/crossrootfs/ppc64le
./build.sh --use-mono-runtime --online -- /p:OverrideTargetRid=linux-ppc64le

**Tarball is generated for ppc64le as follows:**
```
root@dotnet-x86-ub20-04-ghatwala-node1:~/swapnali/dotnet/artifacts/x64/Release# ll
total 942176
drwxr-xr-x 2 root root      4096 Dec 14 16:55 ./
drwxr-xr-x 3 root root      4096 Dec 14 16:01 ../
-rw-r--r-- 1 root root 373596678 Dec 14 16:54 Private.SourceBuilt.Artifacts.8.0.100-rtm.23551.1.linux-x64.tar.gz
-rw-r--r-- 1 root root  28563439 Dec 14 16:55 Private.SourceBuilt.Prebuilts.8.0.100-rtm.23551.1.linux-x64.tar.gz
-rw-r--r-- 1 root root     32284 Dec 14 16:01 SourceBuild.MSBuildSdkResolver.deps.json
-rw-r--r-- 1 root root     11264 Dec 14 16:01 SourceBuild.MSBuildSdkResolver.dll
-rw-r--r-- 1 root root     10124 Dec 14 16:01 SourceBuild.MSBuildSdkResolver.pdb
-rw-r--r-- 1 root root   4164580 Dec 14 16:35 aspnetcore-runtime-8.0.0-linux-ppc64le.tar.gz
-rw-r--r-- 1 root root         6 Dec 14 16:35 aspnetcore_base_runtime.version
-rw-r--r-- 1 root root    720597 Dec 14 16:25 dotnet-apphost-pack-8.0.0-linux-ppc64le.tar.gz
-rw-r--r-- 1 root root    490697 Dec 14 16:25 dotnet-nethost-8.0.0-linux-ppc64le.tar.gz
-rw-r--r-- 1 root root  21196895 Dec 14 16:25 dotnet-runtime-8.0.0-linux-ppc64le.tar.gz
-rw-r--r-- 1 root root  19753037 Dec 14 16:25 dotnet-runtime-internal-8.0.0-linux-ppc64le.tar.gz
-rw-r--r-- 1 root root  16809132 Dec 14 16:25 dotnet-runtime-symbols-linux-ppc64le-8.0.0.tar.gz
-rw-r--r-- 1 root root 111430144 Dec 14 16:53 dotnet-sdk-8.0.100-linux-x64.tar.gz
-rw-r--r-- 1 root root 192053999 Dec 14 16:54 dotnet-symbols-all-8.0.100-rtm.23551.1-linux-x64.tar.gz
-rw-r--r-- 1 root root 124816986 Dec 14 16:55 dotnet-symbols-sdk-8.0.100-rtm.23551.1-linux-x64.tar.gz
-rw-r--r-- 1 root root  71078632 Dec 14 16:52 dotnet-toolset-internal-8.0.100-rtm.23551.6.zip
root@dotnet-x86-ub20-04-ghatwala-node1:~/swapnali/dotnet/artifacts/x64/Release#
```

**Comment by Swapnali911** [comment]
After analyzing logs found that for sdk x64 is getting used instead of ppc64le

 Task Parameter:Command=/home/swapnali/dotnet/src/sdk/build.sh  --ci --configuration Release --restore --build --pack --publish -bl /p:ArcadeBuildFromSource=true /p:CopyWipIntoInnerSourceBuildRepo=true /p:DotNetBuildOffline=true /p:CopySrcInsteadOfClone=true /p:DotNetPackageVersionPropsPath="/home/swapnali/dotnet/artifacts/obj/x64/Release/PackageVersions.sdk.props" /p:AdditionalSourceBuiltNupkgCacheDir="/home/swapnali/dotnet/artifacts/obj/x64/Release/blob-feed/packages/" /p:ReferencePackageNupkgCacheDir="/home/swapnali/dotnet/prereqs/packages/reference/" /p:PreviouslySourceBuiltNupkgCacheDir="/home/swapnali/dotnet/prereqs/packages/previously-source-built/" /p:SourceBuildUseMonoRuntime=true --nodereuse false /p:PackageProjectUrl=https://github.com/dotnet/sdk /p:PublishCompressedFilesPathPrefix=/home/swapnali/dotnet/artifacts/obj/x64/Release/blobs/Sdk/ **/p:PortableRid=linux-x64** **/p:TargetRid=linux-x64** -v minimal >> /home/swapnali/dotnet/artifacts/logs/sdk.log 2>&1



Tried with below 

# git diff repo-projects/sdk.proj
diff --git a/repo-projects/sdk.proj b/repo-projects/sdk.proj
index 79b1ef0607..cee46c1284 100644
--- a/repo-projects/sdk.proj
+++ b/repo-projects/sdk.proj
@@ -2,6 +2,11 @@
   <Import Project="Sdk.props" Sdk="Microsoft.NET.Sdk" />

   <PropertyGroup>
+    <OverrideTargetRid>$(TargetRid)</OverrideTargetRid>
+    <OverrideTargetRid Condition="'$(TargetOS)' == 'OSX'">osx-$(Platform)</OverrideTargetRid>
+    <OverrideTargetRid Condition="'$(TargetOS)' == 'FreeBSD'">freebsd-$(Platform)</OverrideTargetRid>
+    <OverrideTargetRid Condition="'$(TargetOS)' == 'Windows_NT'">win-$(Platform)</OverrideTargetRid>
+
     <BuildCommandArgs>$(StandardSourceBuildArgs)</BuildCommandArgs>
     <BuildCommandArgs>$(BuildCommandArgs) $(FlagParameterPrefix)nodereuse $(ArcadeFalseBoolBuildArg)</BuildCommandArgs>
     <BuildCommandArgs>$(BuildCommandArgs) /p:PackageProjectUrl=https://github.com/dotnet/sdk</BuildCommandArgs>
@@ -10,8 +15,8 @@
     
     <_platformIndex>$(NETCoreSdkPortableRuntimeIdentifier.LastIndexOf('-'))</_platformIndex>
     <_baseOS>$(NETCoreSdkPortableRuntimeIdentifier.Substring(0, $(_platformIndex)))</_baseOS>
-    <BuildCommandArgs>$(BuildCommandArgs) /p:PortableRid=$(_baseOS)-$(Platform)</BuildCommandArgs>
-    <BuildCommandArgs>$(BuildCommandArgs) /p:TargetRid=$(TargetRid)</BuildCommandArgs>
+    <BuildCommandArgs>$(BuildCommandArgs) /p:PortableRid=$(_baseOS)-ppc64le</BuildCommandArgs>
+    <BuildCommandArgs>$(BuildCommandArgs) /p:TargetRid=$(OverrideTargetRid)</BuildCommandArgs>

     
     <BuildCommandArgs Condition="'$(BuildArchitecture)' == 'arm'">$(BuildCommandArgs) /p:NativeAotSupported=false</BuildCommandArgs>

Build cmd after this change :
Task Parameter:Command=/home/swapnali/dotnet/src/sdk/build.sh  --ci --configuration Release --restore --build --pack --publish -bl /p:ArcadeBuildFromSource=true /p:CopyWipIntoInnerSourceBuildRepo=true /p:DotNetBuildOffline=true /p:CopySrcInsteadOfClone=true /p:DotNetPackageVersionPropsPath="/home/swapnali/dotnet/artifacts/obj/x64/Release/PackageVersions.sdk.props" /p:AdditionalSourceBuiltNupkgCacheDir="/home/swapnali/dotnet/artifacts/obj/x64/Release/blob-feed/packages/" /p:ReferencePackageNupkgCacheDir="/home/swapnali/dotnet/prereqs/packages/reference/" /p:PreviouslySourceBuiltNupkgCacheDir="/home/swapnali/dotnet/prereqs/packages/previously-source-built/" /p:SourceBuildUseMonoRuntime=true --nodereuse false /p:PackageProjectUrl=https://github.com/dotnet/sdk /p:PublishCompressedFilesPathPrefix=/home/swapnali/dotnet/artifacts/obj/x64/Release/blobs/Sdk/ **/p:PortableRid=linux-ppc64le** **/p:TargetRid=linux-ppc64le** -v minimal >> /home/swapnali/dotnet/artifacts/logs/sdk.log 

But generated tarball is still not working

[root@ibm-ic922-08 hello]# dotnet run
Unhandled exception: System.ComponentModel.Win32Exception (8): An error occurred trying to start process '/home/hello/bin/Debug/net8.0/hello' with working directory '/home/hello'. Exec format error
   at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo startInfo, String resolvedFilename, String[] argv, String[] envp, String cwd, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Microsoft.DotNet.Cli.Utils.Command.Execute(Action`1 processStarted)
   at Microsoft.DotNet.Cli.Utils.Command.Execute()
   at Microsoft.DotNet.Tools.Run.RunCommand.Execute()
   at Microsoft.DotNet.Tools.Run.RunCommand.Run(ParseResult parseResult)
   at System.CommandLine.Invocation.AnonymousCliAction.Invoke(ParseResult parseResult)
   at System.CommandLine.Invocation.InvocationPipeline.Invoke(ParseResult parseResult)
   at System.CommandLine.ParseResult.Invoke()
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, TimeSpan startupTime, ITelemetry telemetryClient)

**Comment by tmds** [comment]
@Swapnali911 and I have debugged the issue further.

The `Microsoft.NETCoreSdk.BundledVersions.props` is not using the target rids/architecture.

On the ppc64le SDK this is in the file:

```xml
 <NETCoreSdkRuntimeIdentifier>linux-x64</NETCoreSdkRuntimeIdentifier>
 <NETCoreSdkPortableRuntimeIdentifier>linux-x64</NETCoreSdkPortableRuntimeIdentifier>
```

Probably the issue also affects the VMR cross builds that were added recently.

cc @directhex @ViktorHofer @MichaelSimons @omajid

**Comment by tmds** [comment]
In the build log, I see these rids getting passed to `installer/build.sh` as arguments:
```
 --runtime-id linux-ppc64le
 /p:Rid=linux-ppc64le
 /p:AspNetCoreInstallerRid=linux-ppc64le
 /p:CoreSetupRid=linux-ppc64le
```

**Comment by tmds** [comment]
I'm looking into fixing this.

I'm also considering some additional changes that would be meaningful in the "cross-build for source-build" use-case.

**Comment by tmds** [comment]
I've opened these PRs: https://github.com/dotnet/installer/pull/18658 and https://github.com/dotnet/aspnetcore/pull/54031.

(With the cross-build dependencies installed) they enable cross-building a ppc64le .NET SDK using:

```
./prep.sh
./build.sh --use-mono-runtime --source-build -- /p:TargetArchitecture=ppc64le
```
