### ISSUE TITLE
ASP.NET Core node error in CI on Ubuntu2204 legs

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/source-build#3927]
The following build error is occurring in the two Ubutntu2204 CI legs (x64/arm64)

```
    npm ERR! code 1
    npm ERR! path /vmr/src/aspnetcore/artifacts/sb/src/node_modules/puppeteer
    npm ERR! command failed
    npm ERR! command sh -c node install.mjs
    npm ERR! file:///vmr/src/aspnetcore/artifacts/sb/src/node_modules/puppeteer/install.mjs:20
    npm ERR!   const {downloadBrowser} = await (async () => {
    npm ERR!                             ^^^^^
    npm ERR! 
    npm ERR! SyntaxError: Unexpected reserved word
    npm ERR!     at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
    npm ERR!     at async link (internal/modules/esm/module_job.js:42:21)
    
    npm ERR! A complete log of this run can be found in:
    npm ERR!     /root/.npm/_logs/2024-01-11T08_48_17_144Z-debug-0.log
  /vmr/src/aspnetcore/eng/SourceBuild.props(99,5): error MSB3073: The command "npm ci" exited with code 1. [/vmr/artifacts/source-built-sdks/Microsoft.DotNet.Arcade.Sdk/tools/Build.proj]
##[error]/vmr/src/aspnetcore/eng/SourceBuild.props(99,5): error MSB3073: The command "npm ci" exited with code 1.
```

[Failing Build](https://dev.azure.com/dnceng/internal/_build/results?buildId=2351072&view=logs&j=7cdc4ff9-ab77-52f4-4bd0-bd2d93b8182c) (internal microsoft link)

This appears related to https://github.com/dotnet/aspnetcore/pull/53154.

**Comment by MichaelSimons** [comment]
@wtgodbe - can you take a look?

**Comment by MichaelSimons** [comment]
https://github.com/dotnet/source-build/issues/3924#issuecomment-1886811967 seems relevant

**Comment by mthalman** [comment]
Fixed by https://github.com/dotnet/dotnet-buildtools-prereqs-docker/pull/964
