### ISSUE TITLE
Enable signing in the VMR official pipeline

### ISSUE THREAD

**Issue by mmitche** [dotnet/source-build#4062]
Enable the signing infra to function in official VMR pipeline. This means getting the pipeline approved for signing, Ensuring that the microbuild plugins are installed, etc.

**Comment by ellahathaway** [comment]
**T-Shirt Size: S**

Part of this work is handled by other issues (see https://github.com/dotnet/source-build/issues/4678).

**Comment by ellahathaway** [comment]
[Link to changes](https://dev.azure.com/dnceng/internal/_git/dotnet-dotnet/commit/dd3c16a3bf57122eded8dfd9eee2efe44975e124?refName=refs%2Fheads%2Fdev%2Fellahathaway%2Fsigning) (currently internal due to testing in the pipeline)

This is currently blocked on installing Microbuild in the VMR. I am in contact with MicroBuild folks to get perspective on what may be causing the failures.

**Comment by ellahathaway** [comment]
Blocked on https://github.com/microsoft/vstest/issues/10414 for windows builds

**Comment by ellahathaway** [comment]
[tvOS_Shortstack_arm64](https://dev.azure.com/dnceng/internal/_build/results?buildId=2578329&view=logs&j=e13dbbc4-7aea-5f2e-ab6d-4f4074602a95&t=4d357897-5c9a-5996-ce35-3b0079d0f547&l=3664) build is experiencing a timeout while signing runtime artifacts. I filed https://portal.microsofticm.com/imp/v5/incidents/details/564149414/summary in response.

**Comment by ellahathaway** [comment]
SDK signing in the Windows legs is failing with the following error:

```
D:\a\_work\1\s\artifacts\source-built-sdks\Microsoft.DotNet.Arcade.Sdk\tools\Sign.proj(83,5): error : Number of entries expected in End Of Central Directory does not correspond to number of entries in Central Directory.
  D:\a\_work\1\s\artifacts\source-built-sdks\Microsoft.DotNet.Arcade.Sdk\tools\Sign.proj(83,5): error MSB4018: The "Microsoft.DotNet.SignTool.SignToolTask" task failed unexpectedly.
  D:\a\_work\1\s\artifacts\source-built-sdks\Microsoft.DotNet.Arcade.Sdk\tools\Sign.proj(83,5): error MSB4018: System.Collections.Generic.KeyNotFoundException: The given key 'Microsoft.DotNet.SignTool.SignedFileContentKey' was not present in the dictionary.
  D:\a\_work\1\s\artifacts\source-built-sdks\Microsoft.DotNet.Arcade.Sdk\tools\Sign.proj(83,5): error MSB4018:    at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
  D:\a\_work\1\s\artifacts\source-built-sdks\Microsoft.DotNet.Arcade.Sdk\tools\Sign.proj(83,5): error MSB4018:    at Microsoft.DotNet.SignTool.Configuration.TrackFile(PathWithHash file, PathWithHash parentContainer, String collisionPriorityId) in /_/src/arcade/src/Microsoft.DotNet.SignTool/src/Configuration.cs:line 245
  D:\a\_work\1\s\artifacts\source-built-sdks\Microsoft.DotNet.Arcade.Sdk\tools\Sign.proj(83,5): error MSB4018:    at Microsoft.DotNet.SignTool.Configuration.GenerateListOfFiles() in /_/src/arcade/src/Microsoft.DotNet.SignTool/src/Configuration.cs:line 161
  D:\a\_work\1\s\artifacts\source-built-sdks\Microsoft.DotNet.Arcade.Sdk\tools\Sign.proj(83,5): error MSB4018:    at Microsoft.DotNet.SignTool.SignToolTask.ExecuteImpl() in /_/src/arcade/src/Microsoft.DotNet.SignTool/src/SignToolTask.cs:line 271
  D:\a\_work\1\s\artifacts\source-built-sdks\Microsoft.DotNet.Arcade.Sdk\tools\Sign.proj(83,5): error MSB4018:    at Microsoft.DotNet.SignTool.SignToolTask.Execute() in /_/src/arcade/src/Microsoft.DotNet.SignTool/src/SignToolTask.cs:line 175
  D:\a\_work\1\s\artifacts\source-built-sdks\Microsoft.DotNet.Arcade.Sdk\tools\Sign.proj(83,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Execute()
  D:\a\_work\1\s\artifacts\source-built-sdks\Microsoft.DotNet.Arcade.Sdk\tools\Sign.proj(83,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(TaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask)
```

Per dnceng suggestion, I pinged Jacques offline for help (he's OOF until tomorrow)

**Comment by ellahathaway** [comment]
Ubuntu linux build failed in runtime with the following error:

![Image](https://github.com/user-attachments/assets/14891076-2118-4c45-890d-b862a57c2898)

This happens in the source-build build before signing occurs.

@mmitche - have you seen this issue before?

**Comment by ViktorHofer** [comment]
cc @jkoritzinsky @akoeplinger

**Comment by ellahathaway** [comment]
Linux builds are timing out in signing. This is because MicroBuild is shelling out signing tasks consecutively rather than concurrently (signing on windows does not timeout because signing tasks are run concurrently). We have contacted the MicroBuild team to investigate.

**Comment by ellahathaway** [comment]
https://devdiv.visualstudio.com/Engineering/_git/MicroBuild/pullrequest/595202 will resolve issues with installing NuGet in Linux builds. [These lines](https://github.com/ellahathaway/arcade/blob/5fba8f58f9154280cf1f88bfc74bbcc981eeccca/eng/common/core-templates/steps/install-microbuild.yml#L19-L34) can be removed once the linked PR has been merged.

**Comment by ellahathaway** [comment]
I believe that https://devdiv.visualstudio.com/Engineering/_git/MicroBuild/pullrequest/593211 will resolve issues when installing XSignExtension on Mac. [These lines](https://github.com/ellahathaway/arcade/blob/5fba8f58f9154280cf1f88bfc74bbcc981eeccca/eng/common/core-templates/steps/install-microbuild.yml#L36-L43) and [this line](https://github.com/ellahathaway/arcade/blob/5fba8f58f9154280cf1f88bfc74bbcc981eeccca/eng/common/core-templates/steps/install-microbuild.yml#L56) can be removed once the linked PR has been merged.
