### ISSUE TITLE
Full source-build legs using a previously built SourceBuildSdk are failing

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/source-build#4111]
https://dnceng.visualstudio.com/internal/_build/results?buildId=2375891&view=results as an example build

This started happening after Wednesday 9AM (GMT+1) as at that time the full build was still green: https://dnceng.visualstudio.com/internal/_build/results?buildId=2372357&view=results

I looked at all the commits since then and likely the change that regressed this is https://github.com/directhex/installer/blob/64e1ffe1baac9592f27a16636f01064ddc60a2bd/src/SourceBuild/patches/runtime/0002-short-stack-support.patch#L41

@directhex PTAL

**Comment by mthalman** [comment]
It's not related to https://github.com/dotnet/installer/pull/18463. There was a successful build after the changes in that PR came in. Based on the build results of the dotnet-source-build-lite pipeline, this regressions points to just one installer commit: https://github.com/dotnet/installer/commit/bf6f78261f29df8eefb1aed6eec4cb67c81c374b. Unfortunately, that's the big dependency flow from sdk.

**Comment by directhex** [comment]
I'm innocent! What a whirlwind Monday morning

**Comment by mthalman** [comment]
This is ILCompiler-related. The specific error is this:

```
      Unhandled exception. System.CommandLine.CommandLineException: Target OS 'alpine' is not supported
         at System.CommandLine.Helpers.GetTargetOS(String) in /_/src/runtime/src/coreclr/tools/Common/CommandLineHelpers.cs:line 84
         at System.CommandLine.CliArgument`1.<>c__DisplayClass8_0.<set_CustomParser>b__0(ArgumentResult argumentResult, Object& parsedValue)
         at System.CommandLine.Parsing.ArgumentResult.ValidateAndConvert(Boolean)
         at System.CommandLine.Parsing.CommandResult.ValidateOptions(Boolean)
         at System.CommandLine.Parsing.CommandResult.Validate(Boolean)
         at System.CommandLine.Parsing.ParseOperation.Validate()
         at System.CommandLine.Parsing.ParseOperation.Parse()
         at System.CommandLine.Parsing.CliParser.Parse(CliCommand, IReadOnlyList`1, String , CliConfiguration )
         at System.CommandLine.CliConfiguration.Invoke(String[])
         at ILCompiler.Program.Main(String[]) in /_/src/runtime/src/coreclr/tools/aot/ILCompiler/Program.cs:line 753
      Aborted (core dumped)
```

[Example build](https://dev.azure.com/dnceng-public/public/_build/results?buildId=562246&view=logs&j=b9abe003-a5da-5729-0444-865506f15e35&t=3e16c345-0385-5f7a-129a-e4c24e1d773d)

I suspect that this may be due to using a RID-specific SDK (which all of the failing scenarios have in common).

Assuming the break is caused by runtime, the corresponding commit range that this happened is here: https://github.com/dotnet/runtime/compare/d40c654c274fe4f4afe66328f0599130f3eb2ea6..a79c62ddc8089cf2879ed36eac9aa333b32bde5f

/cc @jkotas, @MichalStrehovsky

**Comment by ViktorHofer** [comment]
> I'm innocent! What a whirlwind Monday morning

I wouldn't be so sure about that ;) Your change in runtime that was included as a patch is part of that commit range: https://github.com/dotnet/runtime/commit/6e36330872998c791a2c0d31b688e1bdece2451f

**Comment by ViktorHofer** [comment]
OK, https://github.com/dotnet/dotnet/pull/66 verified that the break really is unrelated to https://github.com/dotnet/installer/pull/18463. Apologies Jo.

**Comment by directhex** [comment]
Yeah! The one time I didn't break the build!! (Probably!)
