### ISSUE TITLE
Smoke test fails on dotnet new console

### ISSUE THREAD

**Issue by dseefeld** [dotnet/source-build#429]
Smoke tests on the source-built cli are encountering the following error:
```
Processing post-creation actions...
Running 'dotnet restore' on /src/sb-cli/testing-smoke/C#_console/C#_console.csproj...
Unhandled Exception: System.TypeInitializationException: The type initializer for 'Microsoft.Build.Shared.BuildEnvironmentHelper' threw an exception. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Build.Shared.BuildEnvironmentHelper.CheckIfRunningTests() in /_/src/Shared/BuildEnvironmentHelper.cs:line 316
   at Microsoft.Build.Shared.BuildEnvironmentHelper..cctor() in /_/src/Shared/BuildEnvironmentHelper.cs:line 391
   --- End of inner exception stack trace ---
   at Microsoft.Build.Shared.BuildEnvironmentHelper.get_Instance() in /_/src/Shared/BuildEnvironmentHelper.cs:line 57
   at Microsoft.Build.CommandLine.MSBuildApp.ConstructArrayArg(String[] args) in /_/src/MSBuild/XMake.cs:line 241
   at Microsoft.Build.CommandLine.MSBuildApp.Main(String[] args) in /_/src/MSBuild/XMake.cs:line 216
```

**Comment by dseefeld** [comment]
This is fixed with https://github.com/dotnet/source-build/pull/439
