### ISSUE TITLE
Scenario Tests hang the build for an unreasonably long time

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/source-build#4371]
During PR validation, the scenario tests are failing and hang the build.

Example PR validation - https://dev.azure.com/dnceng-public/public/_build/results?buildId=664879&view=logs&j=609589e2-4f74-5576-cdb7-914bcaea778b

Scenario tests failed immediately with the following:

```
MSBUILD : error MSB1025: An internal failure occurred while running MSBuild. [/vmr/repo-projects/scenario-tests.proj]
  System.TypeLoadException: Method 'get_Count' in type 'Microsoft.Build.Collections.PropertyDictionary`1' from assembly 'Microsoft.Build, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' does not have an implementation.
     at Microsoft.Build.Evaluation.ProjectCollection..ctor(IDictionary`2 globalProperties, IEnumerable`1 loggers, IEnumerable`1 remoteLoggers, ToolsetDefinitionLocations toolsetDefinitionLocations, Int32 maxNodeCount, Boolean onlyLogCriticalEvents, Boolean loadProjectsReadOnly, Boolean useAsynchronousLogging, Boolean reuseProjectRootElementCache)
     at Microsoft.Build.CommandLine.MSBuildApp.BuildProject(String projectFile, String[] targets, String toolsVersion, Dictionary`2 globalProperties, Dictionary`2 restoreProperties, ILogger[] loggers, LoggerVerbosity verbosity, DistributedLoggerRecord[] distributedLoggerRecords, Int32 cpuCount, Boolean enableNodeReuse, TextWriter preprocessWriter, TextWriter targetsWriter, Boolean detailedSummary, ISet`1 warningsAsErrors, ISet`1 warningsNotAsErrors, ISet`1 warningsAsMessages, Boolean enableRestore, ProfilerLogger profilerLogger, Boolean enableProfiler, Boolean interactive, ProjectIsolationMode isolateProjects, GraphBuildOptions graphBuildOptions, Boolean lowPriority, Boolean question, Boolean isBuildCheckEnabled, String[] inputResultsCaches, String outputResultsCache, Boolean saveProjectResult, BuildResult& result, String[] commandLine)
     at Microsoft.Build.CommandLine.MSBuildApp.Execute(String[] commandLine)
  Unhandled exception: System.TypeLoadException: Method 'get_Count' in type 'Microsoft.Build.Collections.PropertyDictionary`1' from assembly 'Microsoft.Build, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' does not have an implementation.
     at Microsoft.Build.Evaluation.ProjectCollection..ctor(IDictionary`2 globalProperties, IEnumerable`1 loggers, IEnumerable`1 remoteLoggers, ToolsetDefinitionLocations toolsetDefinitionLocations, Int32 maxNodeCount, Boolean onlyLogCriticalEvents, Boolean loadProjectsReadOnly, Boolean useAsynchronousLogging, Boolean reuseProjectRootElementCache)
     at Microsoft.Build.CommandLine.MSBuildApp.BuildProject(String projectFile, String[] targets, String toolsVersion, Dictionary`2 globalProperties, Dictionary`2 restoreProperties, ILogger[] loggers, LoggerVerbosity verbosity, DistributedLoggerRecord[] distributedLoggerRecords, Int32 cpuCount, Boolean enableNodeReuse, TextWriter preprocessWriter, TextWriter targetsWriter, Boolean detailedSummary, ISet`1 warningsAsErrors, ISet`1 warningsNotAsErrors, ISet`1 warningsAsMessages, Boolean enableRestore, ProfilerLogger profilerLogger, Boolean enableProfiler, Boolean interactive, ProjectIsolationMode isolateProjects, GraphBuildOptions graphBuildOptions, Boolean lowPriority, Boolean question, Boolean isBuildCheckEnabled, String[] inputResultsCaches, String outputResultsCache, Boolean saveProjectResult, BuildResult& result, String[] commandLine)
     at Microsoft.Build.CommandLine.MSBuildApp.Execute(String[] commandLine)
     at Microsoft.Build.CommandLine.MSBuildApp.Execute(String[] commandLine)
     at Microsoft.Build.CommandLine.MSBuildApp.Main(String[] args)
     at Microsoft.DotNet.Cli.Utils.MSBuildForwardingAppWithoutLogging.ExecuteInProc(String[] arguments)
  Build failed with exit code 82. Check errors above.
/vmr/repo-projects/scenario-tests.proj(61,5): error MSB3073: The command "/vmr/src/scenario-tests/eng/common/build.sh --restore --test --ci --configuration Release /bl:artifacts/log/Release/Test.binlog" exited with code 82.
```

The Run Tests step continues to run - as of now it has been running 2+ hours and is still running.

I would expect the Run Tests step to fail in a reasonable amount of time and there would be binlogs/logs collected so that the failure can be investigated.

**Comment by ViktorHofer** [comment]
cc @rainersigwald (this is the tracking issue)

**Comment by ViktorHofer** [comment]
Unfortunately this doesn't just affect the scenario tests. I saw that failure in the smoke tests as well: https://github.com/dotnet/installer/pull/19668
