### ISSUE TITLE
`CreateBaselineUpdatePR` failing in SDK Diff Pipeline with HTTP Error

### ISSUE THREAD

**Issue by ellahathaway** [dotnet/source-build#4459]
`CreateBaselineUpdatePR` tool failed for [this build](https://dev.azure.com/dnceng/internal/_build/results?buildId=2470443&view=logs&j=c2a3fba4-babc-5882-e82a-8e0dc9edd6ec&t=05b0bcef-5dd3-54fb-91f3-90c6da6d779a&l=13) (internal Microsoft link) with the following error:

```bash
Unhandled exception: System.FormatException: Cannot add value because header 'Content-Length' does not support multiple values.
   at System.Net.Http.Headers.HttpHeaders.ParseAndAddValue(HeaderDescriptor descriptor, HeaderStoreItemInfo info, String value)
   at System.Net.Http.Headers.HttpHeaders.Add(HeaderDescriptor descriptor, IEnumerable`1 values)
   at Octokit.Internal.HttpClientAdapter.CloneHttpRequestMessageAsync(HttpRequestMessage oldRequest) in /_/Octokit/Http/HttpClientAdapter.cs:line 272
   at Octokit.Internal.HttpClientAdapter.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /_/Octokit/Http/HttpClientAdapter.cs:line 195
   at Octokit.Internal.HttpClientAdapter.Send(IRequest request, CancellationToken cancellationToken, Func`2 preprocessResponseBody) in /_/Octokit/Http/HttpClientAdapter.cs:line 50
   at Octokit.Connection.RunRequest(IRequest request, CancellationToken cancellationToken, Func`2 preprocessResponseBody) in /_/Octokit/Http/Connection.cs:line 760
   at Octokit.Connection.Run[T](IRequest request, CancellationToken cancellationToken, Func`2 preprocessResponseBody) in /_/Octokit/Http/Connection.cs:line 751
   at Octokit.ApiConnection.Post[T](Uri uri, Object data, String accepts, String contentType, CancellationToken cancellationToken)
   at CreateBaselineUpdatePR.PRCreator.CreateBlobAsync(String content) in /mnt/vss/_work/1/s/eng/tools/CreateBaselineUpdatePR/PRCreator.cs:line 213
   at CreateBaselineUpdatePR.PRCreator.UpdateFileAsync(List`1 tree, String content, String searchFileName, String updatedPath) in /mnt/vss/_work/1/s/eng/tools/CreateBaselineUpdatePR/PRCreator.cs:line 200
   at CreateBaselineUpdatePR.PRCreator.UpdateRegularFilesAsync(HashSet`1 updatedFiles, List`1 tree, String compareContent) in /mnt/vss/_work/1/s/eng/tools/CreateBaselineUpdatePR/PRCreator.cs:line 166
   at CreateBaselineUpdatePR.PRCreator.UpdateAllFilesAsync(Dictionary`2 updatedFiles, List`1 tree, Pipelines pipeline) in /mnt/vss/_work/1/s/eng/tools/CreateBaselineUpdatePR/PRCreator.cs:line 89
   at CreateBaselineUpdatePR.PRCreator.ExecuteAsync(String originalFilesDirectory, String updatedFilesDirectory, Int32 buildId, String title, String targetBranch, Pipelines pipeline) in /mnt/vss/_work/1/s/eng/tools/CreateBaselineUpdatePR/PRCreator.cs:line 57
   at CreateBaselineUpdatePR.Program.<>c__DisplayClass11_0.<<SetCommandAction>b__0>d.MoveNext() in /mnt/vss/_work/1/s/eng/tools/CreateBaselineUpdatePR/Program.cs:line 109
--- End of stack trace from previous location ---
   at System.CommandLine.CliCommand.<>c__DisplayClass32_0.<<SetAction>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Invocation.InvocationPipeline.InvokeAsync(ParseResult parseResult, CancellationToken cancellationToken)
```

I tried to repro this locally, but I was unsuccessful. In fact, I was able to successfully create the PR by running the tool with the downloaded files from this build. It produced this PR: https://github.com/dotnet/sdk/pull/41514.

There's not much Octokit documentation on this issue, and nothing has changed to the tool recently that would cause this. It'd be interesting to see if the run of the sdk diff pipeline tomorrow will be able to successfully run the tool without the error.

**Comment by ellahathaway** [comment]
It's possible that a race condition is occurring here... This would help to explain why I cannot repro the issue locally.

**Comment by ellahathaway** [comment]
Added logic to make `Create` calls thread safe, and that did not fix the issue. Now I'm investigating if this is related to the SB bot PAT scopes.
