### ISSUE TITLE
WebScenarioTests is failing in VMR for CentOS9

### ISSUE THREAD

**Issue by Winniexu01** [dotnet/source-build#4478]
main branch: https://dev.azure.com/dnceng/internal/_build/results?buildId=2480808&view=logs&j=2efcdee0-63a0-5f4c-6890-20d889251d12&t=390e181f-697a-535f-ece3-888a6202c16c

 Microsoft.DotNet.SourceBuild.SmokeTests.WebScenarioTests.VerifyScenario failed in `CentOSStream9_Offline_PreviousSourceBuiltSdk_x64` leg:

      Failed Microsoft.DotNet.SourceBuild.SmokeTests.WebScenarioTests.VerifyScenario(scenario: TestScenario { Commands = Build | Run | Publish, Language = CSharp, NoHttps = False, ScenarioName = "WebScenarioTests", Template = BlazorWasm, ··· }) [23 s]
      Error Message:
       System.InvalidOperationException : Failed to execute /vmr/artifacts/bin/Microsoft.DotNet.SourceBuild.SmokeTests/Release/extracted-sdk/dotnet publish  /bl:/vmr/artifacts/TestResults/Release/WebScenarioTests_BlazorWasm_CSharp-publish.binlog -o /vmr/artifacts/bin/Microsoft.DotNet.SourceBuild.SmokeTests/Release/projects-202406240916311927/WebScenarioTests_BlazorWasm_CSharp/bin/publish
    Exit code: 134
    Determining projects to restore...
      All projects are up-to-date for restore.
    /vmr/artifacts/bin/Microsoft.DotNet.SourceBuild.SmokeTests/Release/extracted-sdk/sdk/9.0.100-preview.7.24324.1/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.RuntimeIdentifierInference.targets(326,5): message NETSDK1057: You are using a preview version of .NET. See: https://aka.ms/dotnet-support-policy [/vmr/artifacts/bin/Microsoft.DotNet.SourceBuild.SmokeTests/Release/projects-202406240916311927/WebScenarioTests_BlazorWasm_CSharp/WebScenarioTests_BlazorWasm_CSharp.csproj]
    Unhandled exception. Microsoft.Build.Framework.InternalErrorException: MSB0001: Internal MSBuild Error: must be valid
       at Microsoft.Build.Shared.ErrorUtilities.ThrowInternalError(String message, Exception innerException, Object[] args)
       at Microsoft.Build.BackEnd.Logging.LoggingContext.LogBuildEvent(BuildEventArgs buildEvent)
       at Microsoft.Build.BackEnd.Components.RequestBuilder.AssemblyLoadsTracker.CurrentDomainOnAssemblyLoad(Object sender, AssemblyLoadEventArgs args)
      Stack Trace:
         at Microsoft.DotNet.SourceBuild.SmokeTests.ExecuteHelper.ValidateExitCode(ValueTuple`3 result, Int32 expectedExitCode) in /vmr/test/Microsoft.DotNet.SourceBuild.SmokeTests/ExecuteHelper.cs:line 129
       at Microsoft.DotNet.SourceBuild.SmokeTests.DotNetHelper.ExecuteCmd(String args, String workingDirectory, Action`1 processConfigCallback, Nullable`1 expectedExitCode, Int32 millisecondTimeout) in /vmr/test/Microsoft.DotNet.SourceBuild.SmokeTests/DotNetHelper.cs:line 110
       at Microsoft.DotNet.SourceBuild.SmokeTests.DotNetHelper.ExecutePublish(String projectName, DotNetTemplate template, Nullable`1 selfContained, String rid, Boolean trimmed, Boolean readyToRun) in /vmr/test/Microsoft.DotNet.SourceBuild.SmokeTests/DotNetHelper.cs:line 195
       at Microsoft.DotNet.SourceBuild.SmokeTests.TestScenario.Execute(DotNetHelper dotNetHelper) in /vmr/test/Microsoft.DotNet.SourceBuild.SmokeTests/TestScenario.cs:line 52
       at Microsoft.DotNet.SourceBuild.SmokeTests.WebScenarioTests.VerifyScenario(TestScenario scenario) in /vmr/test/Microsoft.DotNet.SourceBuild.SmokeTests/WebScenarioTests.cs:line 25
       at InvokeStub_WebScenarioTests.VerifyScenario(Object, Span`1)
       at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
      Standard Output Messages:
     Executing: /vmr/artifacts/bin/Microsoft.DotNet.SourceBuild.SmokeTests/Release/extracted-sdk/dotnet new blazorwasm --name WebScenarioTests_BlazorWasm_CSharp --output /vmr/artifacts/bin/Microsoft.DotNet.SourceBuild.SmokeTests/Release/projects-202406240916311927/WebScenarioTests_BlazorWasm_CSharp --language "C#" 
     Executing: /vmr/artifacts/bin/Microsoft.DotNet.SourceBuild.SmokeTests/Release/extracted-sdk/dotnet build /bl:/vmr/artifacts/TestResults/Release/WebScenarioTests_BlazorWasm_CSharp-build.binlog
     Executing: /vmr/artifacts/bin/Microsoft.DotNet.SourceBuild.SmokeTests/Release/extracted-sdk/dotnet run --no-launch-profile /bl:/vmr/artifacts/TestResults/Release/WebScenarioTests_BlazorWasm_CSharp-run.binlog
     Detected app has started. Sending web request to validate...
     Status code returned: OK
     Executing: kill -s TERM 9401
     Executing: /vmr/artifacts/bin/Microsoft.DotNet.SourceBuild.SmokeTests/Release/extracted-sdk/dotnet publish  /bl:/vmr/artifacts/TestResults/Release/WebScenarioTests_BlazorWasm_CSharp-publish.binlog -o /vmr/artifacts/bin/Microsoft.DotNet.SourceBuild.SmokeTests/Release/projects-202406240916311927/WebScenarioTests_BlazorWasm_CSharp/bin/publish

**Comment by Winniexu01** [comment]
Rerun the test and it shows green [CentOSStream9_Offline_PreviousSourceBuiltSdk_x64](https://dev.azure.com/dnceng/internal/_build/results?buildId=2480808&view=logs&j=23b06304-26fe-5f35-596a-a656872ada7a&t=b573433d-94ee-5741-eb0c-efc8c28826c6) (internal Microsoft link). Close the issue.
