### ISSUE TITLE
[SBE] Publish Using Darc failing with `System.InvalidOperationException`

### ISSUE THREAD

**Issue by Winniexu01** [dotnet/source-build#4508]
Related to https://github.com/dotnet/source-build/issues/4507

[SBE failing build](https://dev.azure.com/dnceng/internal/_build/results?buildId=2493009&view=logs&j=226748d0-f812-5437-d3f0-2dd291f5666e&t=b3ecf0d0-598d-5874-6547-0432d3f07f6b&l=85) (internal Microsoft link):

`Publish Using Darc` step failed with below error:

          System.InvalidOperationException: Unable to activate type 'Microsoft.DotNet.DarcLib.AzureDevOpsClient'. The following constructors are ambiguous:
          Void .ctor(Maestro.Common.AzureDevOpsTokens.IAzureDevOpsTokenProvider, Microsoft.DotNet.DarcLib.Helpers.IProcessManager, Microsoft.Extensions.Logging.ILogger`1[Microsoft.DotNet.DarcLib.AzureDevOpsClient])
          Void .ctor(Maestro.Common.AzureDevOpsTokens.IAzureDevOpsTokenProvider, Microsoft.DotNet.DarcLib.Helpers.IProcessManager, Microsoft.Extensions.Logging.ILogger)
             at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(ResultCache lifetime, ServiceIdentifier serviceIdentifier, Type implementationType, CallSiteChain callSiteChain)
             at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, ServiceIdentifier serviceIdentifier, CallSiteChain callSiteChain, Int32 slot)
             at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceIdentifier serviceIdentifier, CallSiteChain callSiteChain)
             at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(ServiceIdentifier serviceIdentifier, CallSiteChain callSiteChain)
             at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.GetCallSite(ServiceIdentifier serviceIdentifier, CallSiteChain callSiteChain)
             at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(ServiceIdentifier serviceIdentifier)
             at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
             at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
             at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
             at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
             at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
             at Microsoft.DotNet.Darc.Operations.AddBuildToChannelOperation.PromoteBuildAsync(Build build, List`1 targetChannels, IBarApiClient barClient) in /_/src/Microsoft.DotNet.Darc/Darc/Operations/AddBuildToChannelOperation.cs:line 223
             at Microsoft.DotNet.Darc.Operations.AddBuildToChannelOperation.ExecuteAsync() in /_/src/Microsoft.DotNet.Darc/Darc/Operations/AddBuildToChannelOperation.cs:line 156
    Problems using Darc to promote build 231451 to default channels. Stopping execution...
    ##[error]Script failed with exit code: 1

**Comment by mthalman** [comment]
This is fixed after getting a new dependency flow of Arcade.
