### ISSUE TITLE
VMR Stage 2 build fails with an internal failure on mono

### ISSUE THREAD

**Issue by Winniexu01** [dotnet/source-build#4519]
[Failing build](https://dev.azure.com/dnceng/internal/_build/results?buildId=2498132&view=logs&j=76d03db3-bc49-53a7-a20b-1050f0eb5e47&t=80dfeb20-733a-54b8-db3c-7b11261d6ba4) (internal Microsoft link)

`symreader` build fails with errors:

    Unhandled exception: Microsoft.Build.Framework.InternalErrorException: MSB0001: Internal MSBuild Error: Cannot acquire required number of nodes.
    =============
    System.AggregateException: One or more errors occurred. (Method has zero rva)
     ---> Microsoft.Build.BackEnd.NodeFailedToLaunchException: Method has zero rva
     ---> System.BadImageFormatException: Method has zero rva
    File name: 'System.Diagnostics.Process'
       at System.Runtime.Serialization.SerializationGuard.ThrowIfDeserializationInProgress(String switchSuffix, Int32& cachedValue)
       at System.Diagnostics.Process.Start()
       at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
       at Microsoft.Build.BackEnd.NodeLauncher.StartInternal(String msbuildLocation, String commandLineArgs)
       --- End of inner exception stack trace ---
       at Microsoft.Build.BackEnd.NodeLauncher.StartInternal(String msbuildLocation, String commandLineArgs)
       at Microsoft.Build.BackEnd.NodeLauncher.<>c__DisplayClass3_0.<Start>b__0()
       at Microsoft.Build.BackEnd.NodeLauncher.DisableMSBuildServer(Func`1 func)
       at Microsoft.Build.BackEnd.NodeLauncher.Start(String msbuildLocation, String commandLineArgs, Int32 nodeId)
       at Microsoft.Build.BackEnd.NodeProviderOutOfProcBase.<>c__DisplayClass14_0.<GetNodes>g__StartNewNode|2(Int32 nodeId)
       at Microsoft.Build.BackEnd.NodeProviderOutOfProcBase.<>c__DisplayClass14_0.<GetNodes>b__0(Int32 nodeId)
       --- End of inner exception stack trace ---
    
    
     ---> System.AggregateException: One or more errors occurred. (Method has zero rva)
     ---> Microsoft.Build.BackEnd.NodeFailedToLaunchException: Method has zero rva
     ---> System.BadImageFormatException: Method has zero rva
    File name: 'System.Diagnostics.Process'
       at System.Runtime.Serialization.SerializationGuard.ThrowIfDeserializationInProgress(String switchSuffix, Int32& cachedValue)
       at System.Diagnostics.Process.Start()
       at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
       at Microsoft.Build.BackEnd.NodeLauncher.StartInternal(String msbuildLocation, String commandLineArgs)
       --- End of inner exception stack trace ---
       at Microsoft.Build.BackEnd.NodeLauncher.StartInternal(String msbuildLocation, String commandLineArgs)
       at Microsoft.Build.BackEnd.NodeLauncher.<>c__DisplayClass3_0.<Start>b__0()
       at Microsoft.Build.BackEnd.NodeLauncher.DisableMSBuildServer(Func`1 func)
       at Microsoft.Build.BackEnd.NodeLauncher.Start(String msbuildLocation, String commandLineArgs, Int32 nodeId)
       at Microsoft.Build.BackEnd.NodeProviderOutOfProcBase.<>c__DisplayClass14_0.<GetNodes>g__StartNewNode|2(Int32 nodeId)
       at Microsoft.Build.BackEnd.NodeProviderOutOfProcBase.<>c__DisplayClass14_0.<GetNodes>b__0(Int32 nodeId)
       --- End of inner exception stack trace ---
       --- End of inner exception stack trace ---
       at Microsoft.Build.Shared.ErrorUtilities.ThrowInternalError(String message, Exception innerException, Object[] args)
       at Microsoft.Build.BackEnd.NodeProviderOutOfProcBase.GetNodes(String msbuildLocation, String commandLineArgs, Int32 nextNodeId, INodePacketFactory factory, Handshake hostHandshake, NodeContextCreatedDelegate createNode, NodeContextTerminateDelegate terminateNode, Int32 numberOfNodesToCreate)
       at Microsoft.Build.BackEnd.NodeProviderOutOfProc.CreateNodes(Int32 nextNodeId, INodePacketFactory factory, Func`2 configurationFactory, Int32 numberOfNodesToCreate)
       at Microsoft.Build.BackEnd.NodeManager.AttemptCreateNode(INodeProvider nodeProvider, NodeConfiguration nodeConfiguration, Int32 numberOfNodesToCreate)
       at Microsoft.Build.BackEnd.NodeManager.CreateNodes(NodeConfiguration configuration, NodeAffinity nodeAffinity, Int32 numberOfNodesToCreate)
       at Microsoft.Build.Execution.BuildManager.PerformSchedulingActions(IEnumerable`1 responses)
       at Microsoft.Build.Execution.BuildManager.HandleNewRequest(Int32 node, BuildRequestBlocker blocker)
       at Microsoft.Build.Execution.BuildManager.ProcessPacket(Int32 node, INodePacket packet)
       at Microsoft.Build.Execution.BuildManager.<>c__DisplayClass81_0.<Microsoft.Build.BackEnd.INodePacketHandler.PacketReceived>b__0()
       at Microsoft.Build.Execution.BuildManager.ProcessWorkQueue(Action action)
    --- End of stack trace from previous location ---
       at Microsoft.Build.CommandLine.MSBuildApp.BuildProject(String projectFile, String[] targets, String toolsVersion, Dictionary`2 globalProperties, Dictionary`2 restoreProperties, ILogger[] loggers, LoggerVerbosity verbosity, DistributedLoggerRecord[] distributedLoggerRecords, Int32 cpuCount, Boolean enableNodeReuse, TextWriter preprocessWriter, TextWriter targetsWriter, Boolean detailedSummary, ISet`1 warningsAsErrors, ISet`1 warningsNotAsErrors, ISet`1 warningsAsMessages, Boolean enableRestore, ProfilerLogger profilerLogger, Boolean enableProfiler, Boolean interactive, ProjectIsolationMode isolateProjects, GraphBuildOptions graphBuildOptions, Boolean lowPriority, Boolean question, Boolean isBuildCheckEnabled, String[] inputResultsCaches, String outputResultsCache, Boolean saveProjectResult, BuildResult& result, String[] commandLine)
       at Microsoft.Build.CommandLine.MSBuildApp.Execute(String[] commandLine)
       at Microsoft.Build.CommandLine.MSBuildApp.Main(String[] args)
       at Microsoft.DotNet.Cli.Utils.MSBuildForwardingAppWithoutLogging.ExecuteInProc(String[] arguments)

[Build.binlog](https://artprodcus3.artifacts.visualstudio.com/Ab55de4ed-4b5a-4215-a8e4-0a0a5f71e7d8/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL2RuY2VuZy9wcm9qZWN0SWQvN2VhOTExNmUtOWZhYy00MDNkLWIyNTgtYjMxZmNmMWJiMjkzL2J1aWxkSWQvMjQ5ODEzMi9hcnRpZmFjdE5hbWUvQ2VudE9TU3RyZWFtOV9Nb25vX09mZmxpbmVfQ3VycmVudFNvdXJjZUJ1aWx0U2RrX3g2NF9CdWlsZExvZ3NfQXR0ZW1wdDE1/content?format=file&subPath=%2Fsrc%2Fsymreader%2Fartifacts%2Flog%2FRelease%2FBuild.binlog)

**Comment by ellahathaway** [comment]
Nothing in [the diff because the last build and this build](https://github.com/dotnet/dotnet/compare/072cde534d08e206e87d0b04e373f49341aa210e...c58501efc104a2e3e0a115c95d8ca69cc57a2ade#diff-9e8c9132e33270f677ac7efc20f54dc1fd37e264461cd9d5a5023fc291d385bf) stands out to me as far as product repo changes that would cause this issue (I would expect to see some changes in msbuild or runtime, but there are no diffs for those repos).

When the rva of a method is zero, it means that the method's il code is not correctly mapped in the executable file, so it's possible that this is a compatibility issue with mono, but I think we might just need to requeue the build and see if this is a consistent error or not. I just requeued so we'll see in ~50 minutes or so.

**Comment by Winniexu01** [comment]
The [latest build](https://dev.azure.com/dnceng/internal/_build/results?buildId=2500578) in VMR is green, close the issue.
