### ISSUE TITLE
Release pipeline doesn't fail in pre-release stage if associated pipeline run has failed

### ISSUE THREAD

**Issue by mthalman** [dotnet/source-build#4532]
Related to https://github.com/dotnet/release/issues/1014#issuecomment-2258531547

When running the release pipeline for 6.0, it ended up failing in the mirror stage trying to download smoke test prereqs because the associated tarball build had failed and no prereq artifacts existed. This should have been caught in the pre-release stage. In fact, it did show up in the `Get associated pipeline runs` step:

```
fail: Microsoft.DotNet.ReleaseCli.Operations.SourceBuild.GetAssociatedBuildOperation[0]
##[error](NETCORE_ENGINEERING_TELEMETRY=ReleaseStaging-Infra) Associated build run has failed. URL: https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_build/results?buildId=2505017
##[debug]Processed:       ##vso[task.logissue type=error;](NETCORE_ENGINEERING_TELEMETRY=ReleaseStaging-Infra) Associated build run has failed. URL: https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_build/results?buildId=2505017
      System.Exception: Associated build run has failed. URL: https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_build/results?buildId=2505017
         at Microsoft.DotNet.ReleaseLib.SourceBuild.SourceBuildManager.GetAssociatedBuild(String pipelineName, SearchBy searchBy, String searchValue, String branchName, Boolean verifySuccedded) in /_/src/Microsoft.DotNet.Release/Microsoft.DotNet.ReleaseLib/SourceBuild/SourceBuildManager.cs:line 125
         at Microsoft.DotNet.ReleaseCli.Operations.SourceBuild.GetAssociatedBuildOperation.ExecuteOperation() in /_/src/Microsoft.DotNet.Release/Microsoft.DotNet.ReleaseCli/src/Operations/SourceBuild/GetAssociatedBuildOperation.cs:line 36
         at Microsoft.DotNet.ReleaseCli.Operations.SourceBuild.SourceBuildBaseOperation.ExecuteAsync() in /_/src/Microsoft.DotNet.Release/Microsoft.DotNet.ReleaseCli/src/Operations/SourceBuild/SourceBuildBaseOperation.cs:line 20
```

However, that execution failure didn't cause the pipeline step to fail. See [example build](https://dev.azure.com/dnceng/internal/_build/results?buildId=2505535&view=results) (internal link).

**Comment by ellahathaway** [comment]
PR: https://dev.azure.com/dnceng/internal/_git/dotnet-release/pullrequest/47316

**Comment by ellahathaway** [comment]
Completed
