### ISSUE TITLE
[main] Synchronize dotnet/dotnet failing with failed to apply the patch root-95dad63-0cc0df0-1.patch to /.

### ISSUE THREAD

**Issue by Winniexu01** [dotnet/source-build#4575]
[Failing build](https://dev.azure.com/dnceng/internal/_build/results?buildId=2522034&view=logs&j=ac868591-5f39-5047-4b1f-0ffa6f6c3268&t=97961c92-5b76-590a-3f4c-bdbad6479e18) (internal Microsoft link)

Error:
```
dbug: Executing command: 'git -C /mnt/vss/_work/1/vmr apply --cached --ignore-space-change /mnt/vss/_work/_temp/root-95dad63-0cc0df0-1.patch'
warn: A new branch was created for the sync and didn't get merged as the sync was interrupted. A new sync should start from main branch.
fail: Failed to synchronize repo sdk
      Failed to apply the patch root-95dad63-0cc0df0-1.patch to /.
      
      Exit code: 1
      Std err:
      error: patch failed: README.md:55
      error: README.md: patch does not apply
      
      
      .
dbug: Microsoft.DotNet.DarcLib.VirtualMonoRepo.PatchApplicationFailedException: Failed to apply the patch root-95dad63-0cc0df0-1.patch to /.
      
      Exit code: 1
      Std err:
      error: patch failed: README.md:55
      error: README.md: patch does not apply
      
      
      
         at Microsoft.DotNet.DarcLib.VirtualMonoRepo.VmrPatchHandler.ApplyPatch(VmrIngestionPatch patch, NativePath targetDirectory, Boolean removePatchAfter, Boolean reverseApply, CancellationToken cancellationToken)
         at Microsoft.DotNet.DarcLib.VirtualMonoRepo.VmrManagerBase.UpdateRepoToRevisionAsync(VmrDependencyUpdate update, ILocalGitRepo repoClone, IReadOnlyCollection`1 additionalRemotes, String fromRevision, Nullable`1 author, String commitMessage, Boolean reapplyVmrPatches, String componentTemplatePath, String tpnTemplatePath, Boolean generateCodeowners, Boolean generateCredScanSuppressions, Boolean discardPatches, CancellationToken cancellationToken)
         at Microsoft.DotNet.DarcLib.VirtualMonoRepo.VmrUpdater.UpdateRepositoryInternal(VmrDependencyUpdate update, Boolean reapplyVmrPatches, IReadOnlyCollection`1 additionalRemotes, String componentTemplatePath, String tpnTemplatePath, Boolean generateCodeowners, Boolean generateCredScanSuppressions, Boolean discardPatches, CancellationToken cancellationToken)
         at Microsoft.DotNet.DarcLib.VirtualMonoRepo.VmrUpdater.UpdateRepositoryRecursively(VmrDependencyUpdate rootUpdate, IReadOnlyCollection`1 additionalRemotes, String componentTemplatePath, String tpnTemplatePath, Boolean generateCodeowners, Boolean generateCredScanSuppressions, Boolean discardPatches, CancellationToken cancellationToken)
         at Microsoft.DotNet.DarcLib.VirtualMonoRepo.VmrUpdater.UpdateRepository(String mappingName, String targetRevision, String targetVersion, Boolean updateDependencies, IReadOnlyCollection`1 additionalRemotes, String componentTemplatePath, String tpnTemplatePath, Boolean generateCodeowners, Boolean generateCredScanSuppressions, Boolean discardPatches, CancellationToken cancellationToken)
         at Microsoft.DotNet.Darc.Operations.VirtualMonoRepo.UpdateOperation.ExecuteInternalAsync(String repoName, String targetRevision, IReadOnlyCollection`1 additionalRemotes, CancellationToken cancellationToken)
         at Microsoft.DotNet.Darc.Operations.VirtualMonoRepo.VmrOperationBase.ExecuteAsync(String repoName, String targetRevision, IReadOnlyCollection`1 additionalRemotes, CancellationToken cancellationToken)
```

**Comment by Winniexu01** [comment]
The [latest build](https://dev.azure.com/dnceng/internal/_build/results?buildId=2522484) (internal Microsoft link) is green, close the issue.
