### ISSUE TITLE
Aspnetcore dev versions build fails to npm install 9.0.0-ci packages

### ISSUE THREAD

**Issue by mmitche** [dotnet/source-build#4616]
```
EXEC : error : Command failed: npm version 9.0.0-ci --no-git-tag-version [C:\d\src\aspnetcore\eng\Npm.Workspace.nodeproj]
  ##vso[task.logissue type=error;sourcepath=EXEC;linenumber=0;columnnumber=0;code=;](NETCORE_ENGINEERING_TELEMETRY=Build) Command failed: npm version 9.0.0-ci --no-git-tag-version
        at genericNodeError (node:internal/errors:984:15)
        at wrappedFn (node:internal/errors:538:14)
        at checkExecSyncError (node:child_process:890:11)
        at execSync (node:child_process:962:15)
        at applyPackageVersion (file:///C:/d/src/aspnetcore/eng/scripts/npm/update-dependency-versions.mjs:55:5)
        at applyVersions (file:///C:/d/src/aspnetcore/eng/scripts/npm/update-dependency-versions.mjs:34:17)
        at file:///C:/d/src/aspnetcore/eng/scripts/npm/pack-workspace.mjs:44:37
        at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
        at async ModuleLoader.import (node:internal/modules/esm/loader:323:24)
        at async loadESM (node:internal/process/esm_loader:28:7) {
      status: 1,
      signal: null,
      output: [ null, null, null ],
      pid: 35360,
      stdout: null,
      stderr: null
    }
    
    Node.js v20.12.0
  C:\d\src\aspnetcore\eng\Npm.Workspace.nodeproj(39,5): error MSB3073: The command "node C:\d\src\aspnetcore\eng\scripts/npm/pack-workspace.mjs --update-versions C:\d\src\aspnetcore\package.json 9.0.0-ci C:\d\src\aspnetcore\artifacts\packages\Release\Shipping\ C:\d\src\aspnetcore\artifacts\obj\Npm.Workspace\Release\" exited with code 1.
  ##vso[task.logissue type=error;sourcepath=C:\d\src\aspnetcore\eng\Npm.Workspace.nodeproj;linenumber=39;columnnumber=5;code=MSB3073;](NETCORE_ENGINEERING_TELEMETRY=Build) The command "node C:\d\src\aspnetcore\eng\scripts/npm/pack-workspace.mjs --update-versions C:\d\src\aspnetcore\package.json 9.0.0-ci C:\d\src\aspnetcore\artifacts\packages\Release\Shipping\ C:\d\src\aspnetcore\artifacts\obj\Npm.Workspace\Release\" exited with code 1.
```

**Comment by mmitche** [comment]
@wtgodbe Still an issue? If not, please close.

**Comment by mmitche** [comment]
Closing, reopen as necessary
