### ISSUE TITLE
Stage 2 .NET 9 RC1 SDK fails to `dotnet build` projects on s390x

### ISSUE THREAD

**Issue by mateusrodrigues** [dotnet/source-build#4638]
### Describe the Bug

I have a [stage 2 .NET 9 RC1 build](https://launchpad.net/~mateus-morais/+archive/ubuntu/dotnet9-rc1-stage2) that was source-built on s390x using a stage 1 .NET 9 RC1 build as well. Both the stage 1 and 2 builds were built using the system zlib, brotli, and rapidjson libraries. This is running on Ubuntu 24.10 Oracular Oriole (devel branch).

Building a Hello World console applications (from the `dotnet new console` template) using this stage 2 .NET 9 RC1 SDK on s390x fails with a `System.OutOfMemoryException`:
```
# dotnet build -v diag
/usr/lib/dotnet/sdk/9.0.100-rc.1.24452.1/MSBuild.dll -nologo -consoleloggerparameters:Summary -maxcpucount -restore -tlp:default=auto -verbosity:m -verbosity:diag ./HelloWorld.csproj
MSBUILD : error MSB1025: An internal failure occurred while running MSBuild.
System.OutOfMemoryException: Insufficient memory to continue the execution of the program.
   at System.Collections.Hashtable.rehash(Int32 newsize) in /_/src/runtime/src/libraries/System.Private.CoreLib/src/System/Collections/Hashtable.cs:line 722
   at System.Collections.Hashtable.expand() in /_/src/runtime/src/libraries/System.Private.CoreLib/src/System/Collections/Hashtable.cs:line 695
   at System.Collections.Hashtable.Insert(Object key, Object nvalue, Boolean add) in /_/src/runtime/src/libraries/System.Private.CoreLib/src/System/Collections/Hashtable.cs:line 836
   at System.Collections.Hashtable.Add(Object key, Object value) in /_/src/runtime/src/libraries/System.Private.CoreLib/src/System/Collections/Hashtable.cs:line 418
   at System.Environment.GetEnvironmentVariables() in /_/src/runtime/src/libraries/System.Private.CoreLib/src/System/Environment.Variables.Unix.cs:line 68
   at Microsoft.Build.Internal.CommunicationsUtilities.GetEnvironmentVariables() in /_/src/msbuild/src/Shared/CommunicationsUtilities.cs:line 401
   at Microsoft.Build.Internal.Utilities.GetEnvironmentProperties(Boolean makeReadOnly) in /_/src/msbuild/src/Build/Utilities/Utilities.cs:line 467
   at Microsoft.Build.Evaluation.ProjectCollection.get_SharedReadOnlyEnvironmentProperties() in /_/src/msbuild/src/Build/Definition/ProjectCollection.cs:line 924
   at Microsoft.Build.Evaluation.ProjectCollection.get_EnvironmentProperties() in /_/src/msbuild/src/Build/Definition/ProjectCollection.cs:line 897
   at Microsoft.Build.Evaluation.ProjectCollection.InitializeToolsetCollection(ToolsetConfigurationReader configReader) in /_/src/msbuild/src/Build/Definition/ProjectCollection.cs:line 1801
   at Microsoft.Build.Evaluation.ProjectCollection..ctor(IDictionary`2 globalProperties, IEnumerable`1 loggers, IEnumerable`1 remoteLoggers, ToolsetDefinitionLocations toolsetDefinitionLocations, Int32 maxNodeCount, Boolean onlyLogCriticalEvents, Boolean loadProjectsReadOnly, Boolean useAsynchronousLogging, Boolean reuseProjectRootElementCache) in /_/src/msbuild/src/Build/Definition/ProjectCollection.cs:line 376
   at Microsoft.Build.CommandLine.MSBuildApp.BuildProject(String projectFile, String[] targets, String toolsVersion, Dictionary`2 globalProperties, Dictionary`2 restoreProperties, ILogger[] loggers, LoggerVerbosity verbosity, DistributedLoggerRecord[] distributedLoggerRecords, Int32 cpuCount, Boolean enableNodeReuse, TextWriter preprocessWriter, TextWriter targetsWriter, Boolean detailedSummary, ISet`1 warningsAsErrors, ISet`1 warningsNotAsErrors, ISet`1 warningsAsMessages, Boolean enableRestore, ProfilerLogger profilerLogger, Boolean enableProfiler, Boolean interactive, ProjectIsolationMode isolateProjects, GraphBuildOptions graphBuildOptions, Boolean lowPriority, Boolean question, Boolean isBuildCheckEnabled, String[] inputResultsCaches, String outputResultsCache, Boolean saveProjectResult, BuildResult& result, String[] commandLine) in /_/src/msbuild/src/MSBuild/XMake.cs:line 1374
   at Microsoft.Build.CommandLine.MSBuildApp.Execute(String[] commandLine) in /_/src/msbuild/src/MSBuild/XMake.cs:line 851
```

The system has plenty of memory available and I was able to reproduce this on different s390x instances. Building the same project with the stage 1 SDK works as expected, so the issue seems to be particular to the stage 2 build.

### Steps to Reproduce

You can easily spin up an Oracular image with LXD:
```
$ lxc launch ubuntu-daily:o oracular
$ lxc shell oracular
```

To install the bits from the provided PPA and reproduce the issue, run these on an Oracular environment:
```
$ add-apt-repository ppa:mateus-morais/dotnet9-rc1-stage2
$ apt install dotnet9
$ dotnet new console -o HelloWorld
```

It should already fail on the `dotnet new` run, when building the project after creation.

cc @dotnet/distro-maintainers

**Comment by omajid** [comment]
Sounds like https://github.com/dotnet/runtime/pull/107559

cc @saitama951 @uweigand

**Comment by mateusrodrigues** [comment]
I just [rebuilt](https://launchpad.net/~mateus-morais/+archive/ubuntu/dotnet9-rc1-stage2-sllg) with the change from dotnet/runtime#107559 and that doesn't seem to fix it, unfortunately.

**Comment by uweigand** [comment]
> I just [rebuilt](https://launchpad.net/~mateus-morais/+archive/ubuntu/dotnet9-rc1-stage2-sllg) with the change from [dotnet/runtime#107559](https://github.com/dotnet/runtime/pull/107559) and that doesn't seem to fix it, unfortunately.

Just to clarify, did you also rebuild the *stage1* with this fix before using it to build stage2?   One possibility is that stage1 is broken due the above problem, and therefore miscompiles stage2.

**Comment by mateusrodrigues** [comment]
> Just to clarify, did you also rebuild the stage1 with this fix before using it to build stage2? One possibility is that stage1 is broken due the above problem, and therefore miscompiles stage2.

Yep, you're right. I had not rebuilt stage 1, but I just rebuilt both with the change from dotnet/runtime#107559, and stage 2 now works as expected.

Thank you @omajid for the pointer!
