### ISSUE TITLE
[internal/8.0.1xx] dotnet-watch tests are failing - timing out

### ISSUE THREAD

**Issue by NikolaMilosavljevic** [dotnet/source-build#4690]
dotnet-watch tests appear to be timing out.

```
  [xUnit.net 00:01:06.76]     Microsoft.DotNet.SourceBuild.SmokeTests.DotNetWatchTests.WatchTests [FAIL]
  [xUnit.net 00:01:06.76]       Assert.True() Failure
  [xUnit.net 00:01:06.76]       Expected: True
  [xUnit.net 00:01:06.76]       Actual:   False
  [xUnit.net 00:01:06.76]       Stack Trace:
  [xUnit.net 00:01:06.76]         /vmr/test/Microsoft.DotNet.SourceBuild.SmokeTests/DotNetWatchTests.cs(29,0): at Microsoft.DotNet.SourceBuild.SmokeTests.DotNetWatchTests.WatchTests()
  [xUnit.net 00:01:06.76]            at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
  [xUnit.net 00:01:06.76]            at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
  [xUnit.net 00:01:06.76]       Output:
  [xUnit.net 00:01:06.76]         Executing: /vmr/test/Microsoft.DotNet.SourceBuild.SmokeTests/bin/Release/net8.0/.dotnet/dotnet new console --name DotNetWatchTests --output /vmr/test/Microsoft.DotNet.SourceBuild.SmokeTests/bin/Release/net8.0/projects-202410212142174064/DotNetWatchTests 
  [xUnit.net 00:01:06.76]         Executing: /vmr/test/Microsoft.DotNet.SourceBuild.SmokeTests/bin/Release/net8.0/.dotnet/dotnet watch run --non-interactive
  [xUnit.net 00:01:06.76]         Process did not exit. Killing /vmr/test/Microsoft.DotNet.SourceBuild.SmokeTests/bin/Release/net8.0/.dotnet/dotnet watch run --non-interactive after waiting 60000 milliseconds.
```

https://dev.azure.com/dnceng/internal/_build/results?buildId=2565843&view=logs&j=315e2bbd-4f2e-5da5-0f7d-95bc4e8ab650&t=4b52f778-0813-5e91-aab5-92303f7c69c2

**Comment by MichaelSimons** [comment]
This issue was resolved.
