### ISSUE TITLE
VMR Build Tagging is Failing

### ISSUE THREAD

**Issue by ellahathaway** [dotnet/source-build#4713]
[Example pipeline run](https://dev.azure.com/dnceng/internal/_build/results?buildId=2572615&view=logs&j=fa5c2909-0e29-5671-d5eb-16d6c40e0c4a&t=22eb0279-f706-5157-2789-5196ba7b00a6&l=13) (internal Microsoft link)

This is the commit that caused the failure: https://github.com/dotnet/sdk/commit/b66c80019ad5d67147186b97e66d59a5c23b28b3

**Comment by ellahathaway** [comment]
This is the error I get when I try to run the darc command locally:

```
/dotnet/src/sdk# ../../.dotnet/dotnet darc vmr get-version --vmr /dotnet sdk
Unhandled exception encountered
System.InvalidOperationException: Unable to resolve service for type 'Microsoft.DotNet.DarcLib.VirtualMonoRepo.IVmrDependencyTracker' while attempting to activate 'Microsoft.DotNet.Darc.Operations.VirtualMonoRepo.GetRepoVersionOperation'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance[T](IServiceProvider provider, Object[] parameters)
   at Microsoft.DotNet.Darc.Options.CommandLineOptions`1.GetOperation(ServiceProvider sp) in /_/src/Microsoft.DotNet.Darc/Darc/Options/CommandLineOptions.cs:line 25
   at Microsoft.DotNet.Darc.Program.RunOperation(CommandLineOptions opts, ServiceProvider sp) in /_/src/Microsoft.DotNet.Darc/Darc/Program.cs:line 68
```

@premun - I believe that you merged https://github.com/dotnet/sdk/pull/44554 which updated darc in sdk. Can you please TAL? Thanks.

**Comment by premun** [comment]
Will do! Sorry about this, I guess we don't have E2E tests for this command

**Comment by Winniexu01** [comment]
Hi , this issue reoccurred with the same error, so I reopened it, [example pipeline run](https://dev.azure.com/dnceng/internal/_build/results?buildId=2574932&view=logs&j=fa5c2909-0e29-5671-d5eb-16d6c40e0c4a&t=22eb0279-f706-5157-2789-5196ba7b00a6) (internal Microsoft link)

@premun @marcpopMSFT , this issue caused by https://github.com/dotnet/sdk/pull/44625, could you please TAL? Thanks.

**Comment by premun** [comment]
Yeah, it's because we reverted an update but then it got merged again here which I didn't notice: https://github.com/dotnet/sdk/pull/44625

I will open a manual PR to bump to the correct version

**Comment by premun** [comment]
Fix is here: https://github.com/dotnet/sdk/pull/44632

**Comment by premun** [comment]
Okay, the pipeline is green after the update: https://dev.azure.com/dnceng/internal/_build/results?buildId=2575516&view=logs&j=fa5c2909-0e29-5671-d5eb-16d6c40e0c4a&t=22eb0279-f706-5157-2789-5196ba7b00a6&l=14
