### ISSUE TITLE
[main] Synchronize VMR failed

### ISSUE THREAD

**Issue by Winniexu01** [dotnet/source-build#4723]
[Failing build](https://dev.azure.com/dnceng/internal/_build/results?buildId=2577672&view=logs&j=ac868591-5f39-5047-4b1f-0ffa6f6c3268&t=97961c92-5b76-590a-3f4c-bdbad6479e18&l=548) (internal Microsoft link)

`Synchronize dotnet/dotnet (Unix)` step failed with `Once you make changes to the conflicting VMR patch, commit it locally and re-run this script.`:

    dbug: Executing command: 'git -C /mnt/vss/_work/1/vmr apply --cached --ignore-space-change --directory src/arcade /mnt/vss/_work/1/vmr/src/sdk/src/SourceBuild/patches/arcade/0001-Update to .NET 10 SDK and TFM to net10.0 in arcade.patch'
    warn: A new branch was created for the sync and didn't get merged as the sync was interrupted. A new sync should start from main branch.
    fail: Failed to synchronize repo sdk
          Failed to apply the patch 0001-Update to .NET 10 SDK and TFM to net10.0 in arcade.patch to src/arcade.
          
          Exit code: 1
          Std err:
          error: patch failed: src/arcade/global.json:1
          error: src/arcade/global.json: patch does not apply
          
          
          .
    dbug: Microsoft.DotNet.DarcLib.VirtualMonoRepo.PatchApplicationFailedException: Failed to apply the patch 0001-Update to .NET 10 SDK and TFM to net10.0 in arcade.patch to src/arcade.
          
          Exit code: 1
          Std err:
          error: patch failed: src/arcade/global.json:1
          error: src/arcade/global.json: patch does not apply
          
          
          
             at Microsoft.DotNet.DarcLib.VirtualMonoRepo.VmrPatchHandler.ApplyPatch(VmrIngestionPatch patch, NativePath targetDirectory, Boolean removePatchAfter, Boolean reverseApply, CancellationToken cancellationToken) in /_/src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrPatchHandler.cs:line 310
             at Microsoft.DotNet.DarcLib.VirtualMonoRepo.VmrManagerBase.ReapplyVmrPatchesAsync(IReadOnlyCollection`1 patches, CancellationToken cancellationToken) in /_/src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrManagerBase.cs:line 190
             at Microsoft.DotNet.DarcLib.VirtualMonoRepo.VmrUpdater.UpdateRepositoryRecursively(VmrDependencyUpdate rootUpdate, IReadOnlyCollection`1 additionalRemotes, String componentTemplatePath, String tpnTemplatePath, Boolean generateCodeowners, Boolean generateCredScanSuppressions, Boolean discardPatches, CancellationToken cancellationToken) in /_/src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrUpdater.cs:line 411
             at Microsoft.DotNet.DarcLib.VirtualMonoRepo.VmrUpdater.UpdateRepository(String mappingName, String targetRevision, String targetVersion, Boolean updateDependencies, IReadOnlyCollection`1 additionalRemotes, String componentTemplatePath, String tpnTemplatePath, Boolean generateCodeowners, Boolean generateCredScanSuppressions, Boolean discardPatches, CancellationToken cancellationToken) in /_/src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrUpdater.cs:line 131
             at Microsoft.DotNet.Darc.Operations.VirtualMonoRepo.UpdateOperation.ExecuteInternalAsync(String repoName, String targetRevision, IReadOnlyCollection`1 additionalRemotes, CancellationToken cancellationToken) in /_/src/Microsoft.DotNet.Darc/Darc/Operations/VirtualMonoRepo/UpdateOperation.cs:line 34
             at Microsoft.DotNet.Darc.Operations.VirtualMonoRepo.VmrOperationBase.ExecuteAsync(String repoName, String targetRevision, IReadOnlyCollection`1 additionalRemotes, CancellationToken cancellationToken) in /_/src/Microsoft.DotNet.Darc/Darc/Operations/VirtualMonoRepo/VmrOperationBase.cs:line 103
    + [[ 42 == 0 ]]

**Comment by mthalman** [comment]
Fixed by https://github.com/dotnet/sdk/pull/44756
