### ISSUE TITLE
FSharp regularly fails to build inside the VMR

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/source-build#4744]
Example PR: https://github.com/dotnet/sdk/pull/44947
Example build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=873300&view=logs&jobId=065f4438-9cad-58b1-e2fc-5943cd245a63

```
##vso[task.setvariable isSecret=False;variable=Artifacts;isOutput=True]D:\a\_work\1\vmr\src\fsharp\artifacts
##vso[task.setvariable isSecret=False;variable=Artifacts.Toolset;isOutput=True]D:\a\_work\1\vmr\src\fsharp\artifacts\toolset
##vso[task.setvariable isSecret=False;variable=Artifacts.Log;isOutput=True]D:\a\_work\1\vmr\src\fsharp\artifacts\log\Release
##vso[task.setvariable isSecret=False;variable=TEMP;isOutput=True]D:\a\_work\1\vmr\src\fsharp\artifacts\tmp\Release
##vso[task.setvariable isSecret=False;variable=TMP;isOutput=True]D:\a\_work\1\vmr\src\fsharp\artifacts\tmp\Release

Downloading vswhere
The process cannot access the file 'C:\Users\cloudtest\AppData\Local\Microsoft\VisualStudio\17.0_24e3c197\sdk.txt' because it is being used by another process.
System.IO.IOException: The process cannot access the file 'C:\Users\cloudtest\AppData\Local\Microsoft\VisualStudio\17.0_24e3c197\sdk.txt' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Microsoft.PowerShell.Commands.FileSystemProvider.ClearContent(String path)
at EnablePreviewSdks, D:\a\_work\1\vmr\src\fsharp\eng\build.ps1: line 512
at <ScriptBlock>, D:\a\_work\1\vmr\src\fsharp\eng\build.ps1: line 539
at <ScriptBlock>, <No file>: line 1
at <ScriptBlock>, <No file>: line 1
##vso[task.logissue type=error](NETCORE_ENGINEERING_TELEMETRY=Build) Failure preparing build

TotalMinutes TotalSeconds
------------ ------------
 0.042810015    2.5686009
```

**Comment by mmitche** [comment]
Haven't seen this in a long time. Good to close @ViktorHofer?
