### ISSUE TITLE
Smoke test failure: Could not load type 'Microsoft.Build.Logging.ProfilerLogger'

### ISSUE THREAD

**Issue by crummel** [dotnet/source-build#508]
```
starting language C#, type console
    running new
The template "Console Application" was created successfully.

Processing post-creation actions...
Running 'dotnet restore' on /home/chris/dotnet_source-build/testing-smoke/C#_console/C#_console.csproj...
Unhandled Exception: System.TypeLoadException: Could not load type 'Microsoft.Build.Logging.ProfilerLogger' from assembly 'Microsoft.Build, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
   at Microsoft.Build.CommandLine.MSBuildApp.Execute(String[] commandLine)
   at Microsoft.Build.CommandLine.MSBuildApp.Main(String[] args)


Restore failed.
Post action failed.
Description: Restore NuGet packages required by this project.
Manual instructions: Run 'dotnet restore'

    new succeeded
    running restore

Unhandled Exception: System.TypeLoadException: Could not load type 'Microsoft.Build.Logging.ProfilerLogger' from assembly 'Microsoft.Build, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
   at Microsoft.Build.CommandLine.MSBuildApp.Execute(String[] commandLine)
   at Microsoft.Build.CommandLine.MSBuildApp.Main(String[] args)
```

**Comment by crummel** [comment]
Confirmed that reverting fe4ae4bd94f332a2970f00d4bf98f4f4c1f5829d. no longer repros the issue.  Tried reverting the output path changes [here](https://github.com/Microsoft/msbuild/compare/1a410f549ea34d2c780b4f8144d928e14ceb31ec...e5cfa78385d0676d770d5242d0a27144919518dd#diff-9002cc0a94d7643cb073436b973a63ebL7) on a hunch with no luck.  Attempting to bisect the msbuild changes now.
